from importlib import import_module

from .attention import (
    FlexAttentionBackwardHighOrderVariable,
    FlexAttentionHigherOrderVariable,
)
from .autograd import (
    AutogradFunctionApplyVariable,
    BaseHOPVariable,
    CheckpointHigherOrderVariable,
    CustomFunctionHigherOrderOperatorVariable,
    DynamoBypassingWrapperHigherOrderVariable,
    FunctionalCallVariable,
    FunctorchHigherOrderVariable,
    HintsWrapperHigherOrderVariable,
    ReparametrizeModuleCallVariable,
    WrapHigherOrderVariable,
    WrapWithAutocastHigherOrderVariable,
    WrapWithSetGradEnabledHigherOrderVariable,
)
from .common import (
    _assert_tensors_nonaliasing,
    _call_function_and_unflatten_output,
    _call_function_with_auto_output_flattening,
    _check_all_tensorvariable,
    _check_supported_callable_arg,
    _get_fake_value,
    _hop_name_to_variable_class,
    _make_inlined,
    add_call_function,
    add_hop_context,
    are_same_graph_modules,
    check_aliasing_and_input_mutation,
    check_meta_consistency_vt,
    collect_intermediate_outputs,
    discard_graph_changes,
    dynamo_allow_side_effects_in_hop,
    dynamo_enable_grad,
    find_mismatched_vars,
    get_hop_args,
    get_tensor_storages,
    make_attr,
    maybe_positional_arg_names,
    move_lifted_freevars_phs_to_end,
    only_consist_of,
    OutputSpec,
    overwrite_tensor_vt_proxy,
    overwrite_tensor_vt_requires_grad,
    speculate_subgraph,
    speculate_subgraph_with_auto_output_flattening,
    StorageAliasingTracker,
    SubgraphTracingInfo,
    TorchHigherOrderOperatorVariable,
    trace_hop_function,
    trace_hop_function_with_auto_output_flattening,
    validate_args_and_maybe_create_graph_inputs,
    validate_subgraph_output_types,
)
from .control_flow import (
    AssociativeScanHigherOrderVariable,
    CondHigherOrderVariable,
    MapHigherOrderVariable,
    ScanHigherOrderVariable,
    WhileLoopHigherOrderVariable,
    WhileLoopStackOutputHigherOrderVariable,
)
from .distributed import (
    ExecutorchCallDelegateHigherOrderVariable,
    LocalMapWrappedHigherOrderVariable,
)
from .misc import (
    AutoFunctionalizeHigherOrderVariable,
    CallTorchbindHigherOrderVariable,
    ExportTracepointHigherOrderVariable,
    InlineAsmElementwiseHigherOrderVariable,
    OutDtypeHigherOrderVariable,
    PrintHigherOrderVariable,
    RunWithRNGStateHigherOrderVariable,
    StrictModeHigherOrderVariable,
    TraceWrappedHigherOrderOperatorVariable,
)


# Late resolution: invoke_subgraph inherits from WrapHigherOrderVariable, so
# autograd must be imported first to avoid a circular import during package init.
InvokeSubgraphHigherOrderVariable = import_module(
    "..invoke_subgraph", __package__
).InvokeSubgraphHigherOrderVariable


_hop_name_to_variable_class.update(
    {
        "cond": CondHigherOrderVariable,
        "while_loop": WhileLoopHigherOrderVariable,
        "while_loop_stack_output": WhileLoopStackOutputHigherOrderVariable,
        "map_impl": MapHigherOrderVariable,
        "executorch_call_delegate": ExecutorchCallDelegateHigherOrderVariable,
        "out_dtype": OutDtypeHigherOrderVariable,
        "wrap": WrapHigherOrderVariable,
        "hints_wrapper": HintsWrapperHigherOrderVariable,
        "flex_attention": FlexAttentionHigherOrderVariable,
        "flex_attention_backward": FlexAttentionBackwardHighOrderVariable,
        "wrap_activation_checkpoint": CheckpointHigherOrderVariable,
        "tag_activation_checkpoint": CheckpointHigherOrderVariable,
        "_export_tracepoint": ExportTracepointHigherOrderVariable,
        "trace_wrapped": TraceWrappedHigherOrderOperatorVariable,
        "strict_mode": StrictModeHigherOrderVariable,
        "run_with_rng_state": RunWithRNGStateHigherOrderVariable,
        "associative_scan": AssociativeScanHigherOrderVariable,
        "scan": ScanHigherOrderVariable,
        "call_torchbind": CallTorchbindHigherOrderVariable,
        "print": PrintHigherOrderVariable,
        "wrap_with_set_grad_enabled": WrapWithSetGradEnabledHigherOrderVariable,
        "wrap_with_autocast": WrapWithAutocastHigherOrderVariable,
        "dynamo_bypassing_wrapper": DynamoBypassingWrapperHigherOrderVariable,
        "auto_functionalized": AutoFunctionalizeHigherOrderVariable,
        "auto_functionalized_v2": AutoFunctionalizeHigherOrderVariable,
        "inline_asm_elementwise": InlineAsmElementwiseHigherOrderVariable,
        "invoke_subgraph": InvokeSubgraphHigherOrderVariable,
        "custom_function_call": CustomFunctionHigherOrderOperatorVariable,
        "local_map_hop": LocalMapWrappedHigherOrderVariable,
    }
)


__all__ = [
    "AssociativeScanHigherOrderVariable",
    "AutogradFunctionApplyVariable",
    "AutoFunctionalizeHigherOrderVariable",
    "BaseHOPVariable",
    "CallTorchbindHigherOrderVariable",
    "CheckpointHigherOrderVariable",
    "CondHigherOrderVariable",
    "CustomFunctionHigherOrderOperatorVariable",
    "DynamoBypassingWrapperHigherOrderVariable",
    "ExecutorchCallDelegateHigherOrderVariable",
    "ExportTracepointHigherOrderVariable",
    "FlexAttentionBackwardHighOrderVariable",
    "FlexAttentionHigherOrderVariable",
    "FunctionalCallVariable",
    "FunctorchHigherOrderVariable",
    "HintsWrapperHigherOrderVariable",
    "InlineAsmElementwiseHigherOrderVariable",
    "InvokeSubgraphHigherOrderVariable",
    "LocalMapWrappedHigherOrderVariable",
    "MapHigherOrderVariable",
    "OutDtypeHigherOrderVariable",
    "OutputSpec",
    "PrintHigherOrderVariable",
    "ReparametrizeModuleCallVariable",
    "RunWithRNGStateHigherOrderVariable",
    "ScanHigherOrderVariable",
    "StorageAliasingTracker",
    "StrictModeHigherOrderVariable",
    "SubgraphTracingInfo",
    "TorchHigherOrderOperatorVariable",
    "TraceWrappedHigherOrderOperatorVariable",
    "WhileLoopHigherOrderVariable",
    "WhileLoopStackOutputHigherOrderVariable",
    "WrapHigherOrderVariable",
    "WrapWithAutocastHigherOrderVariable",
    "WrapWithSetGradEnabledHigherOrderVariable",
    "_assert_tensors_nonaliasing",
    "_call_function_and_unflatten_output",
    "_call_function_with_auto_output_flattening",
    "_check_all_tensorvariable",
    "_check_supported_callable_arg",
    "_get_fake_value",
    "_make_inlined",
    "add_call_function",
    "add_hop_context",
    "are_same_graph_modules",
    "check_aliasing_and_input_mutation",
    "check_meta_consistency_vt",
    "collect_intermediate_outputs",
    "discard_graph_changes",
    "dynamo_allow_side_effects_in_hop",
    "dynamo_enable_grad",
    "find_mismatched_vars",
    "get_hop_args",
    "get_tensor_storages",
    "make_attr",
    "maybe_positional_arg_names",
    "move_lifted_freevars_phs_to_end",
    "only_consist_of",
    "overwrite_tensor_vt_proxy",
    "overwrite_tensor_vt_requires_grad",
    "speculate_subgraph",
    "speculate_subgraph_with_auto_output_flattening",
    "trace_hop_function",
    "trace_hop_function_with_auto_output_flattening",
    "validate_args_and_maybe_create_graph_inputs",
    "validate_subgraph_output_types",
]
