OPT="-DAT_BUILD_ARM_VEC256_WITH_SLEEF -DAT_PER_OPERATOR_HEADERS -DCAFFE2_BUILD_MAIN_LIB -DCAFFE2_PERF_WITH_SVE=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DFLASHATTENTION_DISABLE_ALIBI -DFMT_HEADER_ONLY=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DPYTORCH_JIT_COMPILE_SHADERS -DUSE_EXTERNAL_MZCRC -D_FILE_OFFSET_BITS=64 -Dtorch_cpu_EXPORTS -D_GLIBCXX_USE_CXX11_ABI=1 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_PYTORCH_QNNPACK -DAT_BUILD_ARM_VEC256_WITH_SLEEF -DSYMBOLICATE_MOBILE_DEBUG_HANDLE"

INC="-I/Users/kevinpouget/remoting/pytorch/src/build/aten/src -I/Users/kevinpouget/remoting/pytorch/src/aten/src -I/Users/kevinpouget/remoting/pytorch/src/build -I/Users/kevinpouget/remoting/pytorch/src -I/Users/kevinpouget/remoting/pytorch/src/third_party/onnx -I/Users/kevinpouget/remoting/pytorch/src/build/third_party/onnx -I/Users/kevinpouget/remoting/pytorch/src/nlohmann -I/Users/kevinpouget/remoting/pytorch/src/torch/csrc/api -I/Users/kevinpouget/remoting/pytorch/src/torch/csrc/api/include -I/Users/kevinpouget/remoting/pytorch/src/caffe2/aten/src/TH -I/Users/kevinpouget/remoting/pytorch/src/build/caffe2/aten/src/TH -I/Users/kevinpouget/remoting/pytorch/src/build/caffe2/aten/src -I/Users/kevinpouget/remoting/pytorch/src/build/caffe2/../aten/src -I/Users/kevinpouget/remoting/pytorch/src/torch/csrc -I/Users/kevinpouget/remoting/pytorch/src/third_party/miniz-3.0.2 -I/Users/kevinpouget/remoting/pytorch/src/third_party/kineto/libkineto/include -I/Users/kevinpouget/remoting/pytorch/src/third_party/cpp-httplib -I/Users/kevinpouget/remoting/pytorch/src/aten/src/ATen/.. -I/Users/kevinpouget/remoting/pytorch/src/c10/.. -I/Users/kevinpouget/remoting/pytorch/src/third_party/pthreadpool/include -I/Users/kevinpouget/remoting/pytorch/src/third_party/cpuinfo/include -I/Users/kevinpouget/remoting/pytorch/src/aten/src/ATen/native/quantized/cpu/qnnpack/include -I/Users/kevinpouget/remoting/pytorch/src/aten/src/ATen/native/quantized/cpu/qnnpack/src -I/Users/kevinpouget/remoting/pytorch/src/aten/src/ATen/native/quantized/cpu/qnnpack/deps/clog/include -I/Users/kevinpouget/remoting/pytorch/src/third_party/NNPACK/include -I/Users/kevinpouget/remoting/pytorch/src/third_party/FP16/include -I/Users/kevinpouget/remoting/pytorch/src/third_party/fmt/include -I/Users/kevinpouget/remoting/pytorch/src/third_party/flatbuffers/include -isystem /Users/kevinpouget/remoting/pytorch/src/third_party/protobuf/src -isystem /Users/kevinpouget/remoting/pytorch/src/cmake/../third_party/eigen -isystem /Users/kevinpouget/remoting/pytorch/src/INTERFACE -isystem /Users/kevinpouget/remoting/pytorch/src/third_party/nlohmann/include -isystem /Users/kevinpouget/remoting/pytorch/src/build/include -I/usr/include/python3.12/"

# -Wall -Wextra
WARN="  -Werror=return-type -Werror=non-virtual-dtor -Werror=range-loop-construct -Werror=bool-operation -Wnarrowing -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-strict-overflow -Wno-strict-aliasing -Wno-stringop-overflow -Wsuggest-override -Wno-psabi -Wno-error=old-style-cast -Wno-missing-braces -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-error=dangling-reference -Wno-error=redundant-move -DUSE_MPS -Wno-stringop-overflow -DHAVE_SVE_CPU_DEFINITION -DHAVE_SVE256_CPU_DEFINITION -O3 -DNDEBUG -DNDEBUG -std=gnu++17 -fPIC -D__NEON__ -Wall -Wextra -Wdeprecated -Wno-unused-parameter -Wno-missing-field-initializers -Wno-array-bounds -Wno-unknown-pragmas -Wno-strict-overflow -Wno-strict-aliasing -Wunused-function -Wunused-variable -Wunused-but-set-variable -Wno-maybe-uninitialized"

COMP_OPT="-O2 -fPIC -O2 -pthread -fopenmp -fvisibility=hidden -fvisibility-inlines-hidden"

OUT=caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/mps/remoting/frontend/ops/_batch_norm_with_update_remoting_frontend.cpp.o
#SRC=/Users/kevinpouget/remoting/pytorch/src/build/aten/src/ATen/mps/remoting/frontend/ops/_batch_norm_with_update_remoting_frontend.cpp
SRC=$1

exec c++ $OPTS $INC $WARN $COMP_OPT -o $OUT -c $SRC
