[pytest]
addopts =
    # show summary of all tests that did not pass
    -rEfX
    # Make tracebacks shorter
    --tb=native
    # capture only Python print and C++ py::print, but not C output (low-level Python errors)
    --capture=sys
    # don't suppress warnings, but don't shove them all to the end either
    -p no:warnings
    # Use custom pytest shard located in test/pytest_shard_custom.py instead
    -p no:pytest-shard
    # don't rewrite assertions (usually not a problem in CI due to differences in imports, see #95844)
    --assert=plain
testpaths =
    test
junit_logging_reruns = all
filterwarnings =
    ignore:Module already imported so cannot be rewritten.*hypothesis:pytest.PytestAssertRewriteWarning

xfail_strict = True

log_cli = true
log_cli_level = INFO
log_cli_format = "%(asctime)s %(levelname)s %(filename)s:%(lineno)d: %(message)s"
log_cli_date_format = "%H:%M:%S"

markers =
    serial: marks tests as needs to be run serially (deselect with '-m "not serial"')
    cpu: test only runs on CPU
    cuda: test only runs on CUDA
    mps: test only runs on MPS
    xpu: test only runs on XPU
    hpu: test only runs on HPU
    meta: test only runs on Meta device
    mtia: test only runs on MTIA
    accelerator: test only runs on accelerator devices
