#!/bin/bash
set -x
# Setup the output directory
rm -rf benchmark_logs
mkdir -p benchmark_logs

# Commands for torchbench for device=cuda, dtype=float16 for inference and for performance testing
python benchmarks/dynamo/torchbench.py --performance --float16 -dcuda --output=benchmark_logs/eager_torchbench_float16_inference_cuda_performance.csv --inference --backend=eager   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr
python benchmarks/dynamo/torchbench.py --performance --float16 -dcuda --output=benchmark_logs/aot_eager_torchbench_float16_inference_cuda_performance.csv --inference --backend=aot_eager   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr
python benchmarks/dynamo/torchbench.py --performance --float16 -dcuda --output=benchmark_logs/inductor_torchbench_float16_inference_cuda_performance.csv --inference -n50 --inductor   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr --cold-start-latency
python benchmarks/dynamo/torchbench.py --performance --float16 -dcuda --output=benchmark_logs/inductor_no_cudagraphs_torchbench_float16_inference_cuda_performance.csv --inference -n50 --inductor --disable-cudagraphs   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr --cold-start-latency

# Commands for torchbench for device=cuda, dtype=float16 for inference and for accuracy testing
python benchmarks/dynamo/torchbench.py --accuracy --float16 -dcuda --output=benchmark_logs/eager_torchbench_float16_inference_cuda_accuracy.csv --inference --backend=eager   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr
python benchmarks/dynamo/torchbench.py --accuracy --float16 -dcuda --output=benchmark_logs/aot_eager_torchbench_float16_inference_cuda_accuracy.csv --inference --backend=aot_eager   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr
python benchmarks/dynamo/torchbench.py --accuracy --float16 -dcuda --output=benchmark_logs/inductor_torchbench_float16_inference_cuda_accuracy.csv --inference -n50 --inductor   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr --cold-start-latency
python benchmarks/dynamo/torchbench.py --accuracy --float16 -dcuda --output=benchmark_logs/inductor_no_cudagraphs_torchbench_float16_inference_cuda_accuracy.csv --inference -n50 --inductor --disable-cudagraphs   --no-skip --dashboard -x detectron2_maskrcnn_r_50_fpn -x maml -x detectron2_fasterrcnn_r_101_fpn -x vision_maskrcnn -x detectron2_fasterrcnn_r_101_c4 -x detectron2_fasterrcnn_r_101_dc5 -x detectron2_maskrcnn_r_101_fpn -x detectron2_fasterrcnn_r_50_fpn -x tacotron2 -x detectron2_fasterrcnn_r_50_dc5 -x detectron2_fasterrcnn_r_50_c4 -x pyhpc_equation_of_state -x pyhpc_turbulent_kinetic_energy -x detectron2_maskrcnn_r_101_c4 -x detectron2_maskrcnn -x pyhpc_isoneutral_mixing -x fambench_xlmr --cold-start-latency

