ANDROID_ABI=arm64-v8a \
BUILD_MOBILE_TEST=1 \
./scripts/build_android.sh \
  -DANDROID_CCACHE=$(which ccache) \
  -DBUILD_BINARY=ON \
  -DUSE_VULKAN=ON \
  -DUSE_VULKAN_API=ON \
  -DUSE_ASAN=ON \
  -DUSE_VULKAN_SHADERC_RUNTIME=OFF \
  -DUSE_VULKAN_WRAPPER=ON
