
# Defined in caffe2/proto/caffe2_pb2.h
class DeviceType:
    ...

CPU: DeviceType = ...
CUDA: DeviceType = ...
OPENGL: DeviceType = ...
OPENCL: DeviceType = ...
MKLDNN: DeviceType = ...
IDEEP: DeviceType = ...
HIP: DeviceType = ...

class NetDef:
    ...

class OperatorDef:
    ...