#ifndef CAFFE2_UTILS_MKL_MKL_VERSION_CHECK_H_
#define CAFFE2_UTILS_MKL_MKL_VERSION_CHECK_H_
#ifdef CAFFE2_USE_MKL

#include <mkl.h>

#if INTEL_MKL_VERSION >= 20170000
#define CAFFE2_HAS_MKL_SGEMM_PACK
#define CAFFE2_HAS_MKL_DNN
#endif // INTEL_MKL_VERSION >= 20170000

#endif // CAFFE2_USE_MKL
#endif // CAFFE2_UTILS_MKL_MKL_VERSION_CHECK_H_
