#!/bin/bash
# Script used only in CD pipeline

set -ex

cd /
git clone https://github.com/OpenMathLib/OpenBLAS.git

OPENBLAS_CHECKOUT_DIR="OpenBLAS"
git -C "${OPENBLAS_CHECKOUT_DIR}" checkout 5e43ba948c3cb35864c7b0953b8dd02374dd3967
OPENBLAS_BUILD_FLAGS="
NUM_THREADS=128
USE_OPENMP=1
NO_SHARED=0
DYNAMIC_ARCH=1
TARGET=ARMV8
CFLAGS=-O3
BUILD_BFLOAT16=1
"

make -j8 ${OPENBLAS_BUILD_FLAGS} -C ${OPENBLAS_CHECKOUT_DIR}
make -j8 ${OPENBLAS_BUILD_FLAGS} install -C ${OPENBLAS_CHECKOUT_DIR}
