#pragma once

#include "Scalar.h"
#include "Type.h"
#include "Generator.h"
#include "CPUGenerator.h"
#include "CUDAGenerator.h"
#include "Context.h"
#include "Storage.h"

#include "CPUByteStorage.h"
#include "CPUCharStorage.h"
#include "CPUDoubleStorage.h"
#include "CPUFloatStorage.h"
#include "CPUIntStorage.h"
#include "CPULongStorage.h"
#include "CPUShortStorage.h"
#include "CPUHalfStorage.h"
#include "CUDAByteStorage.h"
#include "CUDACharStorage.h"
#include "CUDADoubleStorage.h"
#include "CUDAFloatStorage.h"
#include "CUDAIntStorage.h"
#include "CUDALongStorage.h"
#include "CUDAShortStorage.h"
#include "CUDAHalfStorage.h"
