from . import compiled_autograd, eval_frame, guards  # noqa: F401

class _PreserveDispatch:
    def __init__(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...
