from . import compiled_autograd, eval_frame, guards  # noqa: F401

def strip_function_call(name: str) -> str: ...
def is_valid_var_name(name: str) -> bool | int: ...

class Stack:
    def __init__(self, capacity: int): ...
    def push(self, value: object) -> None: ...
    def pop(self) -> object: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
    def __getitem__(self, index: int) -> object: ...
    def __setitem__(self, index: int, value: object) -> None: ...
