from typing import Callable, List

from torch import Tensor
from torch._dynamo.compiled_autograd import AutogradCompilerInstance

def set_autograd_compiler(
    autograd_compiler: Callable[[], AutogradCompilerInstance] | None,
) -> Callable[[], AutogradCompilerInstance] | None: ...
def clear_cache() -> None: ...
def is_cache_empty() -> bool: ...
def set_verbose_logger(fn: Callable[[str], None] | None) -> bool: ...
def set_opaque_cpp_node(b: bool) -> bool: ...
def set_fallback_on_error(b: bool) -> bool: ...
def call_lambda(inputs: List[Tensor], idx: int) -> List[Tensor]: ...
