FROM --platform=linux/riscv64 docker.io/ubuntu:24.04 as base

ENV DEBIAN_FRONTEND noninteractive

# Installed needed OS packages. This is to support all
# the binary builds (torch, vision, audio, text, data)
RUN apt update -y
RUN apt upgrade -y
RUN apt install -y \
  sudo \
  gcc-14 \
  g++-14 \
  make \
  libc6-dev \
  autoconf \
  curl \
  ccache \
  cmake \
  git \
  ninja-build \
  libomp-dev \
  libffi-dev \
  libssl-dev \
  zlib1g-dev \
  wget \
  libblas-dev \
  libopenblas-dev \
  liblapack-dev \
  libatlas-base-dev \
  zstd \
  perl \
  python3 \
  python3-dev \
  python3-pip \
  python3-venv \
  python-is-python3

RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 20
RUN update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 20

RUN python -m venv /opt/pyvenv
ENV PATH=/opt/pyvenv/bin:${PATH}
RUN pip install --upgrade pip
RUN pip install pyyaml
RUN pip install setuptools
RUN pip install typing_extensions

# git236+ would refuse to run git commands in repos owned by other users
# Which causes version check to fail, as pytorch repo is bind-mounted into the image
# Override this behaviour by treating every folder as safe
# For more details see https://github.com/pytorch/pytorch/issues/78659#issuecomment-1144107327
RUN git config --global --add safe.directory "*"

FROM base as final
