FROM quay.io/pypa/manylinux_2_39_riscv64 as base

ARG GCCTOOLSET_VERSION=14

# Language variables
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

ARG PIP_EXTRA_INDEX_URL
ENV PIP_EXTRA_INDEX_URL=${PIP_EXTRA_INDEX_URL}
ARG PIP_PREFER_BINARY
ENV PIP_PREFER_BINARY=${PIP_PREFER_BINARY}

# Installed needed OS packages. This is to support all
# the binary builds (torch, vision, audio, text, data)
RUN yum -y update
RUN yum install -y \
  autoconf \
  automake \
  bison \
  bzip2 \
  curl \
  diffutils \
  file \
  git \
  less \
  libffi-devel \
  libgomp \
  make \
  openssl-devel \
  patch \
  perl \
  unzip \
  util-linux \
  wget \
  which \
  xz \
  zstd \
  sudo \
  gcc \
  gcc-c++ \
  gcc-gfortran \
  gdb
RUN yum install -y ninja-build

# git236+ would refuse to run git commands in repos owned by other users
# Which causes version check to fail, as pytorch repo is bind-mounted into the image
# Override this behaviour by treating every folder as safe
# For more details see https://github.com/pytorch/pytorch/issues/78659#issuecomment-1144107327
RUN git config --global --add safe.directory "*"

# Build CPython 3.15.0 / 3.15.0t from source; quay.io/pypa does not ship them yet
COPY ./common/install_cpython.sh install_cpython.sh
RUN CPYTHON_VERSIONS="3.15.0 3.15.0t" bash ./install_cpython.sh && rm install_cpython.sh

FROM base as openblas
# Install openblas
ARG OPENBLAS_VERSION
ADD ./common/install_openblas.sh install_openblas.sh
RUN bash ./install_openblas.sh && rm install_openblas.sh

FROM base as final

# remove unnecessary python versions
COPY --from=openblas     /opt/OpenBLAS/  /opt/OpenBLAS/
