# syntax = docker/dockerfile:experimental
ARG BASE_CUDA_VERSION=12.6
ARG GPU_IMAGE=amd64/almalinux:8
FROM quay.io/pypa/manylinux_2_28_x86_64 as base

ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

ARG DEVTOOLSET_VERSION=13
RUN yum install -y sudo wget curl perl util-linux xz bzip2 git patch which perl zlib-devel yum-utils gcc-toolset-${DEVTOOLSET_VERSION}-gcc gcc-toolset-${DEVTOOLSET_VERSION}-gcc-c++ gcc-toolset-${DEVTOOLSET_VERSION}-gcc-gfortran gcc-toolset-${DEVTOOLSET_VERSION}-gdb
ENV PATH=/opt/rh/gcc-toolset-${DEVTOOLSET_VERSION}/root/usr/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/rh/gcc-toolset-${DEVTOOLSET_VERSION}/root/usr/lib64:/opt/rh/gcc-toolset-${DEVTOOLSET_VERSION}/root/usr/lib:$LD_LIBRARY_PATH

# cmake-3.18.4.post1 from pip
# NS: Apr 1 2026 3.18.4 is gone, reported here https://github.com/scikit-build/cmake-python-distributions/issues/693
RUN yum install -y python3-pip && \
    python3 -mpip install cmake==3.18.4.post1 && \
    ln -s /usr/local/bin/cmake /usr/bin/cmake3

# Build CPython 3.15.0 / 3.15.0t from source; quay.io/pypa does not ship them yet.
# openssl-devel is needed only to build CPython's _ssl module; install and remove
# it in the same layer so it isn't carried into the base stage.
COPY ./common/install_cpython.sh install_cpython.sh
RUN yum install -y openssl-devel && \
    CPYTHON_VERSIONS="3.15.0 3.15.0t" bash ./install_cpython.sh && \
    yum remove -y openssl-devel && \
    yum clean all && \
    rm install_cpython.sh

FROM base as cuda
ARG BASE_CUDA_VERSION=12.6
# Install CUDA
ADD ./common/install_cuda.sh install_cuda.sh
COPY ./common/install_nccl.sh install_nccl.sh
COPY ./ci_commit_pins/nccl* /ci_commit_pins/
COPY ./common/install_cusparselt.sh install_cusparselt.sh
RUN bash ./install_cuda.sh ${BASE_CUDA_VERSION} && rm install_cuda.sh install_nccl.sh ci_commit_pins/nccl* install_cusparselt.sh

FROM base as intel
# MKL
ADD ./common/install_mkl.sh install_mkl.sh
RUN bash ./install_mkl.sh && rm install_mkl.sh

FROM base as magma
ARG BASE_CUDA_VERSION=12.6
# Install magma
ADD ./common/install_magma.sh install_magma.sh
RUN bash ./install_magma.sh ${BASE_CUDA_VERSION} && rm install_magma.sh

FROM base as jni
# Install java jni header
ADD ./common/install_jni.sh install_jni.sh
ADD ./java/jni.h jni.h
RUN bash ./install_jni.sh && rm install_jni.sh

FROM base as libpng
# Install libpng
ADD ./common/install_libpng.sh install_libpng.sh
RUN bash ./install_libpng.sh && rm install_libpng.sh

FROM ${GPU_IMAGE} as common
ARG DEVTOOLSET_VERSION=13
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV PIP_NO_CACHE_DIR=1
RUN yum -y install epel-release
RUN yum -y update
RUN yum install -y \
        autoconf \
        automake \
        bison \
        bzip2 \
        curl \
        diffutils \
        file \
        git \
        make \
        patch \
        perl \
        unzip \
        util-linux \
        wget \
        which \
        xz \
        glibc-langpack-en \
        gcc-toolset-${DEVTOOLSET_VERSION}-gcc \
        gcc-toolset-${DEVTOOLSET_VERSION}-gcc-c++ \
        gcc-toolset-${DEVTOOLSET_VERSION}-gcc-gfortran \
        gcc-toolset-${DEVTOOLSET_VERSION}-gdb

# git236+ would refuse to run git commands in repos owned by other users
# Which causes version check to fail, as pytorch repo is bind-mounted into the image
# Override this behaviour by treating every folder as safe
# For more details see https://github.com/pytorch/pytorch/issues/78659#issuecomment-1144107327
RUN git config --global --add safe.directory "*"

ENV SSL_CERT_FILE=/opt/_internal/certs.pem
# Install LLVM version
COPY --from=base               /opt/python                           /opt/python
COPY --from=base               /usr/local/lib/                       /usr/local/lib/
COPY --from=base               /opt/_internal                        /opt/_internal
COPY --from=base               /usr/local/bin/auditwheel             /usr/local/bin/auditwheel
COPY --from=intel              /opt/intel                            /opt/intel
COPY --from=base               /usr/local/bin/patchelf               /usr/local/bin/patchelf
COPY --from=libpng             /usr/local/bin/png*                   /usr/local/bin/
COPY --from=libpng             /usr/local/bin/libpng*                /usr/local/bin/
COPY --from=libpng             /usr/local/include/png*               /usr/local/include/
COPY --from=libpng             /usr/local/include/libpng*            /usr/local/include/
COPY --from=libpng             /usr/local/lib/libpng*                /usr/local/lib/
COPY --from=libpng             /usr/local/lib/pkgconfig              /usr/local/lib/pkgconfig
COPY --from=jni                /usr/local/include/jni.h              /usr/local/include/jni.h

# Install Rust toolchain (needed to build the torch._rust extension when building
# the Python wheels). In `common` so all *_final wheel-builder targets inherit it.
COPY ./common/install_rust.sh install_rust.sh
COPY ./ci_commit_pins/rust.txt rust.txt
ENV RUSTUP_HOME /opt/rust
ENV CARGO_HOME /opt/rust
ENV PATH /opt/rust/bin:$PATH
RUN bash ./install_rust.sh && rm install_rust.sh rust.txt

FROM common as cpu_final
ARG BASE_CUDA_VERSION=12.6
ARG DEVTOOLSET_VERSION=13
# Ensure the expected devtoolset is used
ENV PATH=/opt/rh/gcc-toolset-${DEVTOOLSET_VERSION}/root/usr/bin:$PATH
ENV LD_LIBRARY_PATH=/opt/rh/gcc-toolset-${DEVTOOLSET_VERSION}/root/usr/lib64:/opt/rh/gcc-toolset-${DEVTOOLSET_VERSION}/root/usr/lib:$LD_LIBRARY_PATH
# Install setuptools and wheel for python 3.12/3.13
RUN for cpython_version in "cp312-cp312" "cp313-cp313"; do \
    /opt/python/${cpython_version}/bin/python -m pip install setuptools wheel; \
    done;
ADD ./common/patch_libstdc.sh patch_libstdc.sh
RUN bash ./patch_libstdc.sh && rm patch_libstdc.sh

# cmake-3.18.4.post1 from pip; force in case cmake3 already exists
RUN yum install -y python3-pip && \
    python3 -mpip install cmake==3.18.4.post1 && \
    ln -sf /usr/local/bin/cmake /usr/bin/cmake3

FROM cpu_final as cuda_final
RUN rm -rf /usr/local/cuda-${BASE_CUDA_VERSION}
COPY --from=cuda     /usr/local/cuda-${BASE_CUDA_VERSION}  /usr/local/cuda-${BASE_CUDA_VERSION}
COPY --from=magma    /usr/local/cuda-${BASE_CUDA_VERSION}  /usr/local/cuda-${BASE_CUDA_VERSION}
# Newer CUPTI headers staged outside the default include path (see CUDA_CUPTI_VERSION in install_cuda.sh)
COPY --from=cuda     /usr/local/cupti-headers-13.3         /usr/local/cupti-headers-13.3
RUN ln -sf /usr/local/cuda-${BASE_CUDA_VERSION} /usr/local/cuda
ENV PATH=/usr/local/cuda/bin:$PATH

FROM cpu_final as rocm_final
ARG PYTORCH_ROCM_ARCH
ENV PYTORCH_ROCM_ARCH ${PYTORCH_ROCM_ARCH}
ARG ROCM_VERSION
# ROCm is installed from the multi-arch TheRock wheel index.
# ROCM_VERSION and THEROCK_INDEX_URL come from
# manywheel/build.sh --build-arg; it pip-installs the ROCm SDK and
# writes /etc/rocm_env.sh pointing at the real _rocm_sdk_* root; build_env_setup.py /
# repair_wheel.py discover ROCM_HOME from there. No /opt/rocm symlink.
ARG THEROCK_INDEX_URL
ENV MKLROOT /opt/intel
# torch's extensions link libatomic.so.1, which the plain AlmaLinux base lacks.
RUN yum install -y libatomic
# cmake-3.28.4 from pip to get enable_language(HIP)
RUN python3 -m pip install --upgrade pip && \
    python3 -mpip install cmake==3.28.4
ADD ./common/install_rocm.sh install_rocm.sh
RUN bash ./install_rocm.sh && rm install_rocm.sh

FROM cpu_final as xpu_final
# XPU CD use rolling driver
ENV XPU_DRIVER_TYPE ROLLING
# cmake-3.28.4 from pip
RUN python3 -m pip install --upgrade pip && \
    python3 -mpip install cmake==3.28.4
ADD ./common/install_xpu.sh install_xpu.sh
ENV XPU_VERSION 2026.1
ENV OMIX_VERSION 0.3.0
RUN bash ./install_xpu.sh && rm install_xpu.sh
RUN pushd /opt/_internal && tar -xJf static-libs-for-embedding-only.tar.xz && popd
