# Stub file for torch.futures
from collections.abc import Callable
from typing import Generic, TypeVar

import torch
from torch._C import Future as _CFuture

__all__ = ["Future", "collect_all", "wait_all"]

_T = TypeVar("_T")
_S = TypeVar("_S")

class Future(_CFuture[_T], Generic[_T]):
    """
    Wrapper around a ``torch._C.Future`` which encapsulates an asynchronous
    execution of a callable.
    """

    def __init__(
        self, *, devices: list[int | str | torch.device] | None = None
    ) -> None: ...
    def done(self) -> bool: ...
    def wait(self) -> _T: ...
    def value(self) -> _T: ...
    def then(self, callback: Callable[[Future[_T]], _S]) -> Future[_S]: ...
    def add_done_callback(self, callback: Callable[[Future[_T]], None]) -> None: ...
    def set_result(self, result: _T) -> None: ...
    def set_exception(self, result: BaseException) -> None: ...

def collect_all(futures: list[Future[_T]]) -> Future[list[Future[_T]]]: ...
def wait_all(futures: list[Future[_T]]) -> list[_T]: ...
