#ifndef MPSCNNTests_h
#define MPSCNNTests_h

bool test_synchronization();
bool test_nchw_to_nc4_cpu();
bool test_copy_nchw_to_metal();
bool test_conv2d();
bool test_depthwiseConv();
bool test_max_pool2d();
bool test_max_pool2d_ceil();
bool test_max_pool2d_padding();
bool test_relu();
bool test_addmm();
bool test_add();
bool test_add_broadcast();
bool test_add_broadcast2();
bool test_sub();
bool test_sub_broadcast();
bool test_sub_broadcast2();
bool test_mul();
bool test_mul_broadcast();
bool test_mul_broadcast2();
bool test_div();
bool test_div_broadcast();
bool test_div_broadcast2();
bool test_t();
bool test_view();
bool test_view2();
bool test_view3();
bool test_view4();
bool test_cat_dim0();
bool test_cat_dim0_nonarray();
bool test_cat_dim1_0();
bool test_cat_dim1_1();
bool test_cat_dim1_nonarray_0();
bool test_cat_dim1_nonarray_1();
bool test_softmax();
bool test_sigmoid();
bool test_hardsigmoid();
bool test_hardswish();
bool test_upsampling_nearest2d_vec();
bool test_adaptive_avg_pool2d();
bool test_hardtanh_();
bool test_reshape();

#endif
