redirects = {
    # Redirects for documents moved from source/ to source/user_guide/torch_compiler/
    "torch.compiler": "user_guide/torch_compiler/torch.compiler.html",
    "torch.compiler.config": "user_guide/torch_compiler/torch.compiler.config.html",
    "torch.compiler_aot_inductor": "user_guide/torch_compiler/torch.compiler_aot_inductor.html",
    "torch.compiler_aot_inductor_debugging_guide": "user_guide/torch_compiler/torch.compiler_aot_inductor_debugging_guide.html",
    "torch.compiler_aot_inductor_minifier": "user_guide/torch_compiler/torch.compiler_aot_inductor_minifier.html",
    "torch.compiler_backward": "user_guide/torch_compiler/torch.compiler_backward.html",
    "torch.compiler_cudagraph_trees": "user_guide/torch_compiler/torch.compiler_cudagraph_trees.html",
    "torch.compiler_custom_backends": "user_guide/torch_compiler/torch.compiler_custom_backends.html",
    "torch.compiler_dynamic_shapes": "user_guide/torch_compiler/torch.compiler_dynamic_shapes.html",
    "torch.compiler_dynamo_deepdive": "user_guide/torch_compiler/torch.compiler_dynamo_deepdive.html",
    "torch.compiler_dynamo_overview": "user_guide/torch_compiler/torch.compiler_dynamo_overview.html",
    "torch.compiler_fake_tensor": "user_guide/torch_compiler/torch.compiler_fake_tensor.html",
    "torch.compiler_faq": "user_guide/torch_compiler/torch.compiler_faq.html",
    "torch.compiler_fine_grain_apis": "user_guide/torch_compiler/torch.compiler_fine_grain_apis.html",
    "torch.compiler_get_started": "user_guide/torch_compiler/torch.compiler_get_started.html",
    "torch.compiler_inductor_profiling": "user_guide/torch_compiler/torch.compiler_inductor_profiling.html",
    "torch.compiler_inductor_provenance": "user_guide/torch_compiler/torch.compiler_inductor_provenance.html",
    "torch.compiler_ir": "user_guide/torch_compiler/torch.compiler_ir.html",
    "torch.compiler_nn_module": "user_guide/torch_compiler/torch.compiler_nn_module.html",
    "torch.compiler_performance_dashboard": "user_guide/torch_compiler/torch.compiler_performance_dashboard.html",
    "torch.compiler_profiling_torch_compile": "user_guide/torch_compiler/torch.compiler_profiling_torch_compile.html",
    "torch.compiler_transformations": "user_guide/torch_compiler/torch.compiler_transformations.html",
    "torch.compiler_troubleshooting": "user_guide/torch_compiler/torch.compiler_troubleshooting.html",
}
