# Owner(s): ["module: ci"]
"""Tests for the PR-comment layer (render_comment + post_comment).

These exercise only the comment pipeline that consumes a diff() result; the tool
itself is tested in test_introspection.py.
"""

import hashlib
import os

from tools.testing.introspection import post_comment, render_comment

from torch.testing._internal.common_utils import run_tests, TestCase


class TestRenderComment(TestCase):
    # Synthetic diff() result: test_plain (same id) added on both jobs -> "all
    # platforms"; test_b_cuda only on the cuda job.
    RES = {
        "from": "a" * 40,
        "to": "b" * 40,
        "per_job": {
            "linux-cpu/default": {
                "scope_reason": "test-only change",
                "n_affected": 1,
                "uncomparable": [],
                "per_file": {
                    "test/test_x.py": {"added": ["C::test_plain"], "removed": []}
                },
            },
            "linux-cuda-sm80/default": {
                "scope_reason": "test-only change",
                "n_affected": 1,
                "uncomparable": ["test/inductor/test_y.py"],
                "per_file": {
                    "test/test_x.py": {
                        "added": ["C::test_plain", "C::test_b_cuda"],
                        "removed": [],
                    }
                },
            },
        },
    }

    def test_render_groups_and_marker(self):
        md = render_comment.render(self.RES)
        self.assertIn(render_comment.MARKER, md)
        self.assertIn("### Test Change Dashboard", md)
        self.assertIn("+2 added", md)  # test_plain + test_b_cuda (distinct ids)
        # test_plain exists on both jobs -> "all platforms"; test_b_cuda only on cuda.
        self.assertIn("all platforms", md)
        self.assertIn("linux-cuda-sm80/default", md)
        self.assertIn("`test/test_x.py::C::test_b_cuda`", md)
        self.assertIn("1 file(s) could not be compared", md)
        self.assertNotIn("tree/main", md)  # no broken source link in the header
        self.assertIn("Generated by testintro", md)

    def test_render_links_pr_diff(self):
        # With a PR number, added tests link into the PR diff view (right side); the
        # file anchor is sha256 of the path.
        res = dict(
            self.RES,
            pr=42,
            added_loc={"test/test_x.py::C::test_plain": ["test/test_x.py", 12]},
        )
        md = render_comment.render(res)
        anchor = "diff-" + hashlib.sha256(b"test/test_x.py").hexdigest()
        self.assertIn(
            f"[`test/test_x.py::C::test_plain`]"
            f"(https://github.com/pytorch/pytorch/pull/42/files#{anchor}R12)",
            md,
        )
        # test_b_cuda has no recorded location -> stays unlinked.
        self.assertIn("- `test/test_x.py::C::test_b_cuda`", md)

    def test_render_links_blob_fallback(self):
        # No PR number (e.g. CLI --json) -> blob link at the head sha.
        res = dict(
            self.RES,
            added_loc={"test/test_x.py::C::test_plain": ["test/test_x.py", 12]},
        )
        md = render_comment.render(res)
        blob = (
            "https://github.com/pytorch/pytorch/blob/"
            + "b" * 40
            + "/test/test_x.py#L12"
        )
        self.assertIn(f"[`test/test_x.py::C::test_plain`]({blob})", md)

    def test_render_platforms_and_runtime(self):
        res = dict(self.RES, elapsed_s=222.0)
        md = render_comment.render(res)
        self.assertIn("Platforms considered (2)", md)
        self.assertNotIn("ran in", md)  # runtime is in the footer, not the dropdown
        self.assertIn("_Generated by testintro in 3m 42s._", md)  # 222s
        self.assertIn("`linux-cpu/default`", md)
        self.assertIn("`linux-cuda-sm80/default`", md)

    def test_render_broad_note(self):
        res = dict(self.RES, broad=True)
        md = render_comment.render(res)
        self.assertIn("limited to", md)
        self.assertIn("linux-cpu", md)

    def test_render_empty(self):
        empty = {
            "from": "a" * 40,
            "to": "b" * 40,
            "per_job": {
                "linux-cpu/default": {
                    "scope_reason": "",
                    "n_affected": 0,
                    "uncomparable": [],
                    "per_file": {},
                }
            },
        }
        md = render_comment.render(empty)
        self.assertIn("No tests added or removed", md)
        # Platforms-considered dropdown shows even when nothing changed.
        self.assertIn("Platforms considered (1)", md)


class TestPostComment(TestCase):
    def test_skipped_is_noop(self):
        # A skipped result posts nothing and needs no token/network.
        post_comment.post({"pr": 1, "skipped": True})

    def test_upsert_posts_when_no_existing(self):
        calls = []

        def fake_api(method, url, token, data=None):
            calls.append((method, data))
            return [] if method == "GET" else {"id": 1}

        orig_api = post_comment._api
        orig_env = {k: os.environ.get(k) for k in ("GITHUB_TOKEN", "GITHUB_REPOSITORY")}
        post_comment._api = fake_api
        os.environ["GITHUB_TOKEN"] = "x"
        os.environ["GITHUB_REPOSITORY"] = "o/r"
        try:
            post_comment.post({**TestRenderComment.RES, "pr": 5, "skipped": False})
        finally:
            post_comment._api = orig_api
            for k, v in orig_env.items():
                if v is None:
                    os.environ.pop(k, None)
                else:
                    os.environ[k] = v
        methods = [m for m, _ in calls]
        self.assertIn("GET", methods)
        self.assertIn("POST", methods)
        posted = next(d for m, d in calls if m == "POST")
        self.assertIn(render_comment.MARKER, posted["body"])


if __name__ == "__main__":
    run_tests()
