default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end
  lane :install_cert do
    puts "Installing Certificates.p12"
    import_certificate(
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"],
      certificate_path: 'Certificates.p12',
      certificate_password: ENV["IOS_CERT_SECRET"] || "default"
    )
  end
end
