ARCHIVE_ROOT_NAME = "package"
ARCHIVE_FORMAT_PATH = "archive_format"
MODELS_DIR = "models/"
MODELS_FILENAME_FORMAT = "models/{}.json"
AOTINDUCTOR_DIR = "data/aotinductor/"
WEIGHTS_DIR = "data/weights/"
WEIGHT_FILENAME_PREFIX = "weight_"
CONSTANTS_DIR = "data/constants/"
TENSOR_CONSTANT_FILENAME_PREFIX = "tensor_"
CUSTOM_OBJ_FILENAME_PREFIX = "custom_obj_"
SAMPLE_INPUTS_DIR = "data/sample_inputs/"
SAMPLE_INPUTS_FILENAME_FORMAT = "data/sample_inputs/{}.pt"
EXTRA_DIR = "extra/"
MODULE_INFO_PATH = "extra/module_info.json"

ARCHIVE_VERSION = 0
