from typing import Optional, Type

from typing_extensions import Self

class Managed:
    @classmethod
    def current(cls: Type[Self], value: Optional[Self] = None, required: bool = True) -> Self: ...

    def __call__(self, func: Self) -> Self: ...

    def __enter__(self: Self) -> Self: ...

class DefaultManaged(Managed): ...
