# CMake generated Testfile for 
# Source directory: /Users/xcheng16/pytorch/android/libs/fbjni/test/jni
# Build directory: /Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ModifiedUTF8Test.pairs "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/modified_utf8_test" "--gtest_filter=ModifiedUTF8Test.pairs")
set_tests_properties(ModifiedUTF8Test.pairs PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;89;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
add_test(ModifiedUTF8Test.conversionFailForTooShortBuffer "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/modified_utf8_test" "--gtest_filter=ModifiedUTF8Test.conversionFailForTooShortBuffer")
set_tests_properties(ModifiedUTF8Test.conversionFailForTooShortBuffer PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;89;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
add_test(Utf16toUTF8_test.nullUtf16String "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/utf16toUTF8_test" "--gtest_filter=Utf16toUTF8_test.nullUtf16String")
set_tests_properties(Utf16toUTF8_test.nullUtf16String PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;101;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
add_test(Utf16toUTF8_test.negativeUtf16StringLength "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/utf16toUTF8_test" "--gtest_filter=Utf16toUTF8_test.negativeUtf16StringLength")
set_tests_properties(Utf16toUTF8_test.negativeUtf16StringLength PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;101;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
add_test(Utf16toUTF8_test.zeroUtf16StringLength "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/utf16toUTF8_test" "--gtest_filter=Utf16toUTF8_test.zeroUtf16StringLength")
set_tests_properties(Utf16toUTF8_test.zeroUtf16StringLength PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;101;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
add_test(Utf16toUTF8_test.badFormedUtf16String "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/utf16toUTF8_test" "--gtest_filter=Utf16toUTF8_test.badFormedUtf16String")
set_tests_properties(Utf16toUTF8_test.badFormedUtf16String PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;101;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
add_test(Utf16toUTF8_test.goodUtf16String "/Users/xcheng16/pytorch/android/pytorch_android/host/build-cmake/fbjni/host/test/jni/utf16toUTF8_test" "--gtest_filter=Utf16toUTF8_test.goodUtf16String")
set_tests_properties(Utf16toUTF8_test.goodUtf16String PROPERTIES  _BACKTRACE_TRIPLES "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.15/Modules/GoogleTest.cmake;353;add_test;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;101;gtest_add_tests;/Users/xcheng16/pytorch/android/libs/fbjni/test/jni/CMakeLists.txt;0;")
