from collections.abc import Iterable
from typing import Iterator

from torch.nn import Module

class ModuleList(Module, Iterable[Module]):
    _modules: dict[str, Module]
    def __init__(self, modules: Iterable[Module] | None = None) -> None: ...
    def __getitem__(self, idx: int) -> Module: ...
    def __getitem__(self, idx: slice) -> ModuleList: ...
    def __setitem__(self, idx: int, module: Module) -> None: ...
    def __delitem__(self, idx: int | slice) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Module]: ...
