from torch.types import _bool, _int

# Defined in torch/csrc/cpu/Module.cpp

def _is_cpu_support_avx2() -> _bool: ...
def _is_cpu_support_avx512() -> _bool: ...
def _is_cpu_support_avx512_vnni() -> _bool: ...
def _is_cpu_support_amx_tile() -> _bool: ...
def _is_cpu_support_amx_fp16() -> _bool: ...
def _init_amx() -> _bool: ...
def _L1d_cache_size() -> _int: ...
def _L2_cache_size() -> _int: ...
