from torch.types import _bool

# Defined in torch/csrc/cpu/Module.cpp

def _is_cpu_support_avx2() -> _bool: ...
def _is_cpu_support_avx512() -> _bool: ...
def _is_cpu_support_avx512_vnni() -> _bool: ...
def _is_cpu_support_amx_tile() -> _bool: ...
def _init_amx() -> _bool: ...
