# This module is defined in torch/csrc/distributed/c10d/watchdog/init.cpp
# It is only registered when PyTorch is built with the libuv backend
# (TORCH_USE_LIBUV); otherwise importing it raises ImportError.
from collections.abc import Callable
from datetime import timedelta

class _WatchdogHandle:
    def cancel(self) -> None: ...
    def completed(self) -> None: ...

class _Watchdog:
    def __init__(self, poll_interval: timedelta = ...) -> None: ...
    @staticmethod
    def _singleton() -> _Watchdog: ...
    def cpu_timeout(
        self, timeout: timedelta, callback: Callable[[], None]
    ) -> _WatchdogHandle: ...
    def stream_timeout(
        self, timeout: timedelta, callback: Callable[[], None]
    ) -> _WatchdogHandle: ...
    def stream_completed(self, callback: Callable[[], None]) -> _WatchdogHandle: ...
    def op_timeout(
        self, timeout: timedelta, callback: Callable[[], None]
    ) -> _WatchdogHandle: ...
    def num_active_stream_timeouts(self) -> int: ...
