from typing import List
from torch.types import _device

#defined in torch/csrc/lazy/python/init.cpp
def _mark_step(device: str, devices: List[str], wait: bool): ...
def _wait_device_ops(devices: List[str]): ...
def _reset_metrics(): ...
def _counter_names() -> List[str]: ...
def _lazy_mode_enter(device: _device): ...
def _lazy_mode_exit(device: _device): ...
