# mypy: allow-untyped-defs
# Defined in torch/csrc/cuda/shared/nvtx.cpp
def rangePushA(message: str) -> int: ...
def rangePop() -> int: ...
def rangeStartA(message: str) -> int: ...
def rangeEnd(int) -> None: ...
def markA(message: str) -> None: ...
def deviceRangeStart(message: str, stream: int) -> object: ...
def deviceRangeEnd(range_handle: object, stream: int) -> None: ...
