# defined in torch/csrc/profiler/python/init.cpp

from typing import Any, Union

class _RecordFunctionFast:
    def __init__(self, name: Union[str, None]) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def set_name(self, name: str) -> None: ...
