# Defined in torch/csrc/symbolic/python_symbolic.cpp
from typing import Any

class NativeUnsupported(Exception): ...

def _assume_rules() -> tuple[
    dict[tuple[str, bool], set[tuple[str, bool]]],
    list[tuple[set[tuple[str, bool]], tuple[str, bool]]],
    dict[tuple[str, bool], set[int]],
    dict[str, set[str]],
]: ...

class _Expr:
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> int: ...

class _Arena:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def from_sympy(self, obj: Any) -> _Expr: ...
    def to_sympy(self, e: _Expr) -> Any: ...
    def integer(self, v: int) -> _Expr: ...
    def rational(self, p: int, q: int) -> _Expr: ...
    def add(self, args: list[_Expr]) -> _Expr: ...
    def mul(self, args: list[_Expr]) -> _Expr: ...
    def pow(self, b: _Expr, e: _Expr) -> _Expr: ...
    def neg(self, a: _Expr) -> _Expr: ...
    def sub(self, a: _Expr, b: _Expr) -> _Expr: ...
    def args(self, e: _Expr) -> list[_Expr]: ...
    def ask(self, e: _Expr, fact: str) -> bool | None: ...
