# Defined in torch/csrc/symbolic/python_symbolic.cpp
from typing import Any

class NativeUnsupported(Exception): ...

def _assume_rules() -> tuple[
    dict[tuple[str, bool], set[tuple[str, bool]]],
    list[tuple[set[tuple[str, bool]], tuple[str, bool]]],
    dict[tuple[str, bool], set[int]],
    dict[str, set[str]],
]: ...

class _Expr:
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> int: ...

class _Arena:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def from_sympy(self, obj: Any) -> _Expr: ...
    def to_sympy(self, e: _Expr) -> Any: ...
    def integer(self, v: int) -> _Expr: ...
    def rational(self, p: int, q: int) -> _Expr: ...
    def add(self, args: list[_Expr]) -> _Expr: ...
    def mul(self, args: list[_Expr]) -> _Expr: ...
    def pow(self, b: _Expr, e: _Expr) -> _Expr: ...
    def neg(self, a: _Expr) -> _Expr: ...
    def sub(self, a: _Expr, b: _Expr) -> _Expr: ...
    def args(self, e: _Expr) -> list[_Expr]: ...
    def ask(self, e: _Expr, fact: str) -> bool | None: ...
    def diff(self, e: _Expr, x: _Expr) -> _Expr: ...
    def as_numer_denom(self, e: _Expr) -> tuple[_Expr, _Expr]: ...
    def is_polynomial(self, e: _Expr) -> bool: ...
    def monotonic_sign(self, e: _Expr) -> _Expr | None: ...
    def boolean(self, v: bool) -> _Expr: ...
    def rel(self, op: str, lhs: _Expr, rhs: _Expr, evaluate: bool = True) -> _Expr: ...
    def function(self, name: str, args: list[_Expr]) -> _Expr: ...
    def ceildiv(self, base: _Expr, divisor: _Expr) -> _Expr: ...
    def lshift(self, base: _Expr, shift: _Expr) -> _Expr: ...
    def rshift(self, base: _Expr, shift: _Expr) -> _Expr: ...
    def logical_not(self, a: _Expr) -> _Expr: ...
    def logical_and(self, args: list[_Expr]) -> _Expr: ...
    def logical_or(self, args: list[_Expr]) -> _Expr: ...
    def is_eq(self, a: _Expr, b: _Expr) -> bool | None: ...
    def is_ge(self, a: _Expr, b: _Expr) -> bool | None: ...
    def reversed(self, r: _Expr) -> _Expr: ...
    def reversedsign(self, r: _Expr) -> _Expr: ...
    def negated(self, r: _Expr) -> _Expr: ...
    def weak(self, r: _Expr) -> _Expr: ...
    def strict(self, r: _Expr) -> _Expr: ...
    def compare(self, a: _Expr, b: _Expr) -> int: ...
    def value_range(
        self, e: _Expr, ranges: list[tuple[_Expr, _Expr, _Expr]]
    ) -> tuple[_Expr, _Expr]: ...
    def bound_sympy(
        self,
        e: _Expr,
        ranges: list[tuple[_Expr, _Expr, _Expr]],
        context_ranges: list[tuple[_Expr, _Expr, _Expr]] = ...,
    ) -> tuple[_Expr, _Expr]: ...
    def sort_key(self, e: _Expr) -> tuple[Any, ...]: ...
    def ordered(self, seq: list[_Expr]) -> list[_Expr]: ...
    def as_ordered_terms(self, e: _Expr) -> list[_Expr]: ...
    def as_ordered_factors(self, e: _Expr) -> list[_Expr]: ...
    def could_extract_minus_sign(self, e: _Expr) -> bool: ...
    def canonical(self, r: _Expr) -> _Expr: ...
    def sstr(self, e: _Expr) -> str: ...
