# Defined in torch/csrc/symbolic/python_symbolic.cpp
from typing import Any

class NativeUnsupported(Exception): ...

def _assume_rules() -> tuple[
    dict[tuple[str, bool], set[tuple[str, bool]]],
    list[tuple[set[tuple[str, bool]], tuple[str, bool]]],
    dict[tuple[str, bool], set[int]],
    dict[str, set[str]],
]: ...
def _native_config_is_default() -> bool: ...
def _native_queries_pending() -> bool: ...
def _set_pre_dispatch_proxy(value: bool) -> None: ...
def _set_suppress_guards(value: bool) -> None: ...
def _suppress_guards() -> bool: ...

class _Expr:
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> int: ...

class _Arena:
    def __init__(self) -> None: ...
    def __len__(self) -> int: ...
    def from_sympy(self, obj: Any) -> _Expr: ...
    def to_sympy(self, e: _Expr) -> Any: ...
    def integer(self, v: int) -> _Expr: ...
    def rational(self, p: int, q: int) -> _Expr: ...
    def add(self, args: list[_Expr]) -> _Expr: ...
    def mul(self, args: list[_Expr]) -> _Expr: ...
    def pow(self, b: _Expr, e: _Expr) -> _Expr: ...
    def neg(self, a: _Expr) -> _Expr: ...
    def sub(self, a: _Expr, b: _Expr) -> _Expr: ...
    def args(self, e: _Expr) -> list[_Expr]: ...
    def ask(self, e: _Expr, fact: str) -> bool | None: ...
    def diff(self, e: _Expr, x: _Expr) -> _Expr: ...
    def as_numer_denom(self, e: _Expr) -> tuple[_Expr, _Expr]: ...
    def is_polynomial(self, e: _Expr) -> bool: ...
    def monotonic_sign(self, e: _Expr) -> _Expr | None: ...
    def boolean(self, v: bool) -> _Expr: ...
    def rel(self, op: str, lhs: _Expr, rhs: _Expr, evaluate: bool = True) -> _Expr: ...
    def function(self, name: str, args: list[_Expr]) -> _Expr: ...
    def ceildiv(self, base: _Expr, divisor: _Expr) -> _Expr: ...
    def lshift(self, base: _Expr, shift: _Expr) -> _Expr: ...
    def rshift(self, base: _Expr, shift: _Expr) -> _Expr: ...
    def logical_not(self, a: _Expr) -> _Expr: ...
    def logical_and(self, args: list[_Expr]) -> _Expr: ...
    def logical_or(self, args: list[_Expr]) -> _Expr: ...
    def is_eq(self, a: _Expr, b: _Expr) -> bool | None: ...
    def is_ge(self, a: _Expr, b: _Expr) -> bool | None: ...
    def reversed(self, r: _Expr) -> _Expr: ...
    def reversedsign(self, r: _Expr) -> _Expr: ...
    def negated(self, r: _Expr) -> _Expr: ...
    def weak(self, r: _Expr) -> _Expr: ...
    def strict(self, r: _Expr) -> _Expr: ...
    def compare(self, a: _Expr, b: _Expr) -> int: ...
    def value_range(
        self, e: _Expr, ranges: list[tuple[_Expr, _Expr, _Expr]]
    ) -> tuple[_Expr, _Expr]: ...
    def bound_sympy(
        self,
        e: _Expr,
        ranges: list[tuple[_Expr, _Expr, _Expr]],
        context_ranges: list[tuple[_Expr, _Expr, _Expr]] = ...,
    ) -> tuple[_Expr, _Expr]: ...
    def sort_key(self, e: _Expr) -> tuple[Any, ...]: ...
    def ordered(self, seq: list[_Expr]) -> list[_Expr]: ...
    def as_ordered_terms(self, e: _Expr) -> list[_Expr]: ...
    def as_ordered_factors(self, e: _Expr) -> list[_Expr]: ...
    def could_extract_minus_sign(self, e: _Expr) -> bool: ...
    def canonical(self, r: _Expr) -> _Expr: ...
    def safe_expand(self, e: _Expr) -> _Expr: ...
    def canonicalize_bool_expr(self, e: _Expr) -> _Expr: ...
    def xreplace(self, e: _Expr, rule: list[tuple[_Expr, _Expr]]) -> _Expr: ...
    def sstr(self, e: _Expr) -> str: ...

class NativeShapeEnv:
    def __init__(self, arena: _Arena, shape_env: object = None) -> None: ...
    @property
    def arena(self) -> _Arena: ...
    @property
    def pristine(self) -> bool: ...
    def add_symbol(
        self,
        sym: _Expr,
        hint: int | None,
        lower: _Expr,
        upper: _Expr,
        size_like: bool,
    ) -> None: ...
    def mirror_symbol(self, sym: Any, hint: int, lower: Any, upper: Any) -> None: ...
    def mirrored(self, sym: Any) -> tuple[int | None, Any, Any, bool] | None: ...
    @property
    def replacements_empty(self) -> bool: ...
    def __deepcopy__(self, memo: dict[int, object]) -> None: ...
    def __reduce__(self) -> tuple[type[None], tuple[()]]: ...
    def update_range(self, sym: _Expr, lower: _Expr, upper: _Expr) -> None: ...
    def mark_not_pristine(self) -> None: ...
    def mark_replacements(self) -> None: ...
    def simplify(self, e: _Expr) -> _Expr: ...
    def maybe_evaluate_static(self, e: _Expr) -> _Expr | None: ...
    def static_eval(self, e: _Expr) -> tuple[bool, _Expr | None]: ...
    def evaluate_expr(
        self, e: _Expr, hint: object = None, fallback_value: bool | None = None
    ) -> _Expr | None: ...
    def take_queries(
        self,
    ) -> list[tuple[int, Any, bool, int | bool | None, bool | None, bool, Any]]: ...
    def make_node(
        self, expr: Any, pytype: type, hint: int | bool | None
    ) -> _NativeSymNode: ...

class _NativeSymNode:
    @property
    def _expr(self) -> Any: ...
    @property
    def expr(self) -> Any: ...
    @property
    def hint(self) -> int | bool | None: ...
    @property
    def constant(self) -> int | bool | None: ...
    @property
    def pytype(self) -> type: ...
    @property
    def _optimized_summation(self) -> bool: ...
    def __getattr__(self, name: str) -> Any: ...
    def maybe_as_int(self) -> int | None: ...
    def statically_known_true(self, file: str, line: int) -> bool: ...
    def str(self) -> str: ...
