from typing import Any

class no_grad:
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> bool: ...

class enable_grad:
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> bool: ...

class set_grad_enabled:
    def __init__(self, mode: bool) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, *args: Any) -> bool: ...
