# mypy: allow-untyped-defs
"""Shrinking compatibility shim.

Historically held all of ``torch.utils.cpp_extension``; content has been
split into focused submodules (:mod:`._discovery`, :mod:`._jit`, and
:mod:`.setuptools`). This module re-exports the public surface so that
``from torch.utils.cpp_extension._impl import *`` in :mod:`__init__` keeps
working while the ``__init__`` rewiring lands in a later step.
"""

from ._discovery import (  # noqa: F401
    _accepted_compilers_for_platform,
    _append_sycl_std_if_no_std_present,
    _append_sycl_targets_if_missing,
    _check_cuda_version,
    _COMMON_SYCL_FLAGS,
    _find_cuda_home,
    _find_rocm_home,
    _find_sycl_home,
    _get_icpx_version,
    _get_pybind11_abi_build_flags,
    _get_sycl_arch_list,
    _get_sycl_device_flags,
    _is_binary_build,
    _is_cuda_file,
    _is_sycl_file,
    _join_cuda_home,
    _join_rocm_home,
    _join_sycl_home,
    _maybe_write,
    _nt_quote_args,
    _set_hipcc_runtime_lib,
    _SYCL_DLINK_FLAGS,
    _TORCH_PATH,
    _wrap_sycl_host_flags,
    ABI_INCOMPATIBILITY_WARNING,
    BUILT_FROM_SOURCE_VERSION_PATTERN,
    check_compiler_is_gcc,
    check_compiler_ok_for_platform,
    CLIB_EXT,
    CLIB_PREFIX,
    COMMON_HIP_FLAGS,
    COMMON_HIPCC_FLAGS,
    COMMON_MSVC_FLAGS,
    COMMON_NVCC_FLAGS,
    CUDA_CLANG_VERSIONS,
    CUDA_GCC_VERSIONS,
    CUDA_HOME,
    CUDA_MISMATCH_MESSAGE,
    CUDA_MISMATCH_WARN,
    CUDA_NOT_FOUND_MESSAGE,
    CUDNN_HOME,
    EXEC_EXT,
    get_compiler_abi_compatibility_and_version,
    get_cxx_compiler,
    get_default_build_root,
    HIP_HOME,
    include_paths,
    IS_HIP_EXTENSION,
    IS_LINUX,
    IS_MACOS,
    is_ninja_available,
    IS_WINDOWS,
    JIT_EXTENSION_VERSIONER,
    LIB_EXT,
    library_paths,
    min_supported_cpython,
    MINIMUM_CLANG_VERSION,
    MINIMUM_GCC_VERSION,
    MINIMUM_MSVC_VERSION,
    MSVC_IGNORE_CUDAFE_WARNINGS,
    PLAT_TO_VCVARS,
    ROCM_HOME,
    ROCM_VERSION,
    SHARED_FLAG,
    SUBPROCESS_DECODE_ARGS,
    SYCL_HOME,
    TORCH_LIB_PATH,
    verify_ninja_availability,
    VersionMap,
    VersionRange,
    WINDOWS_CUDA_HOME,
    WRONG_COMPILER_WARNING,
)
from ._jit import (  # noqa: F401
    _get_cuda_arch_flags,
    _get_hipcc_path,
    _get_rocm_arch_flags,
    _write_ninja_file_and_compile_objects,
    load,
    load_inline,
    remove_extension_h_precompiler_headers,
)
from .setuptools import (  # noqa: F401
    BuildExtension,
    CppExtension,
    CUDAExtension,
    SyclExtension,
)


__all__ = [
    "get_default_build_root",
    "check_compiler_ok_for_platform",
    "get_compiler_abi_compatibility_and_version",
    "BuildExtension",
    "CppExtension",
    "CUDAExtension",
    "SyclExtension",
    "include_paths",
    "library_paths",
    "load",
    "load_inline",
    "is_ninja_available",
    "verify_ninja_availability",
    "remove_extension_h_precompiler_headers",
    "get_cxx_compiler",
    "check_compiler_is_gcc",
]
