# DO NOT EDIT! This file was generated by jschema_to_python version 0.0.1.dev29,
# with extension for dataclasses and type annotation.

from __future__ import annotations

import dataclasses
from typing import Any


@dataclasses.dataclass
class ArtifactLocation(object):
    """Specifies the location of an artifact."""

    description: Any
    index: Any
    properties: Any
    uri: Any
    uri_base_id: Any


# flake8: noqa
