# DO NOT EDIT! This file was generated by jschema_to_python version 0.0.1.dev29,
# with extension for dataclasses and type annotation.

from __future__ import annotations

import dataclasses
from typing import Any


@dataclasses.dataclass
class SarifLog(object):
    """Static Analysis Results Format (SARIF) Version 2.1.0 JSON Schema: a standard format for the output of static analysis tools."""

    runs: Any = dataclasses.field(metadata={"schema_property_name": "runs"})
    version: Any = dataclasses.field(metadata={"schema_property_name": "version"})
    schema_uri: Any = dataclasses.field(
        default=None, metadata={"schema_property_name": "$schema"}
    )
    inline_external_properties: Any = dataclasses.field(
        default=None, metadata={"schema_property_name": "inlineExternalProperties"}
    )
    properties: Any = dataclasses.field(
        default=None, metadata={"schema_property_name": "properties"}
    )


# flake8: noqa
