# DO NOT EDIT! This file was generated by jschema_to_python version 0.0.1.dev29,
# with extension for dataclasses and type annotation.

from __future__ import annotations

import dataclasses
from typing import Any


@dataclasses.dataclass
class Suppression(object):
    """A suppression that is relevant to a result."""

    kind: Any
    guid: Any
    justification: Any
    location: Any
    properties: Any
    state: Any


# flake8: noqa
