from torch.testing._internal.distributed._tensor.xfails import xfail, skip

# Flattened xfails for TestCompiledDTensorOps
xfails = {
    xfail('__getitem__'),
    xfail('_batch_norm_with_update'),
    xfail('_chunk_cat'),
    xfail('_native_batch_norm_legit'),
    xfail('_unsafe_masked_index'),
    xfail('_unsafe_masked_index_put_accumulate'),
    xfail('_upsample_bilinear2d_aa'),
    xfail('addbmm'),
    xfail('addr'),
    xfail('allclose'),
    xfail('as_strided'),
    xfail('as_strided', 'partial_views'),
    xfail('as_strided_copy'),
    xfail('as_strided_scatter'),
    xfail('atleast_1d'),
    xfail('atleast_2d'),
    xfail('atleast_3d'),
    xfail('bernoulli'),
    xfail('block_diag'),
    xfail('broadcast_tensors'),
    xfail('broadcast_to'),
    xfail('cartesian_prod'),
    xfail('cauchy'),
    xfail('cdist'),
    xfail('cholesky'),
    xfail('cholesky_inverse'),
    xfail('cholesky_solve'),
    xfail('combinations'),
    xfail('complex'),
    xfail('corrcoef'),
    xfail('cov'),
    xfail('cross'),
    xfail('cummax'),
    xfail('cummin'),
    xfail('diagonal'),
    xfail('diagonal_scatter'),
    xfail('dsplit'),
    xfail('equal'),
    xfail('expand'),
    xfail('expand_as'),
    xfail('exponential'),
    xfail('fft.fft'),
    xfail('fft.fft2'),
    xfail('fft.fftn'),
    xfail('fft.fftshift'),
    xfail('fft.ifft'),
    xfail('fft.ifft2'),
    xfail('fft.ifftshift'),
    xfail('fft.ihfft'),
    xfail('fft.ihfft2'),
    xfail('fft.ihfftn'),
    xfail('fft.irfft2'),
    xfail('fft.irfftn'),
    xfail('fft.rfft'),
    xfail('fft.rfft2'),
    xfail('fft.rfftn'),
    xfail('flatten'),
    xfail('flip'),
    xfail('fliplr'),
    xfail('flipud'),
    xfail('gather'),
    xfail('geometric'),
    xfail('geqrf'),
    xfail('grid_sampler_2d'),
    xfail('hash_tensor'),
    xfail('histogram'),
    xfail('histogramdd'),
    xfail('hsplit'),
    xfail('index_add'),
    xfail('index_copy'),
    xfail('index_fill'),
    xfail('index_put'),
    xfail('index_reduce', 'amax'),
    xfail('index_reduce', 'amin'),
    xfail('index_reduce', 'mean'),
    xfail('index_reduce', 'prod'),
    xfail('index_select'),
    xfail('isin'),
    xfail('item'),
    xfail('kron'),
    xfail('kthvalue'),
    xfail('linalg.cholesky'),
    xfail('linalg.cholesky_ex'),
    xfail('linalg.cross'),
    xfail('linalg.det'),
    xfail('linalg.diagonal'),
    xfail('linalg.eig'),
    xfail('linalg.eigvals'),
    xfail('linalg.householder_product'),
    xfail('linalg.inv'),
    xfail('linalg.inv_ex'),
    xfail('linalg.ldl_factor'),
    xfail('linalg.ldl_factor_ex'),
    xfail('linalg.ldl_solve'),
    xfail('linalg.lstsq'),
    xfail('linalg.lstsq', 'grad_oriented'),
    xfail('linalg.lu'),
    xfail('linalg.lu_factor'),
    xfail('linalg.lu_factor_ex'),
    xfail('linalg.lu_solve'),
    xfail('linalg.matrix_power'),
    xfail('linalg.pinv'),
    xfail('linalg.pinv', 'hermitian'),
    xfail('linalg.slogdet'),
    xfail('linalg.solve'),
    xfail('linalg.solve_ex'),
    xfail('linalg.solve_triangular'),
    xfail('linalg.tensorinv'),
    xfail('linalg.tensorsolve'),
    xfail('linalg.vander'),
    xfail('linspace', 'tensor_overload'),
    xfail('log_normal'),
    xfail('logcumsumexp'),
    xfail('logdet'),
    xfail('logspace', 'tensor_overload'),
    xfail('logsumexp'),
    xfail('lu'),
    xfail('lu_solve'),
    xfail('lu_unpack'),
    xfail('masked.cumprod'),
    xfail('masked.logsumexp'),
    xfail('masked.median'),
    xfail('masked_scatter'),
    xfail('masked_select'),
    xfail('matrix_exp'),
    xfail('max', 'reduction_with_dim'),
    xfail('max_pool2d_with_indices_backward'),
    xfail('median'),
    xfail('min', 'reduction_with_dim'),
    xfail('mode'),
    xfail('movedim'),
    xfail('multinomial'),
    xfail('nanmean'),
    xfail('nanmedian'),
    xfail('nanquantile'),
    xfail('nansum'),
    xfail('narrow'),
    xfail('narrow_copy'),
    xfail('native_batch_norm'),
    xfail('nn.functional.adaptive_avg_pool1d'),
    xfail('nn.functional.adaptive_avg_pool2d'),
    xfail('nn.functional.adaptive_avg_pool3d'),
    xfail('nn.functional.adaptive_max_pool1d'),
    xfail('nn.functional.adaptive_max_pool2d'),
    xfail('nn.functional.adaptive_max_pool3d'),
    xfail('nn.functional.alpha_dropout'),
    xfail('nn.functional.avg_pool1d'),
    xfail('nn.functional.avg_pool2d'),
    xfail('nn.functional.avg_pool3d'),
    xfail('nn.functional.batch_norm'),
    xfail('nn.functional.bilinear'),
    xfail('nn.functional.binary_cross_entropy'),
    xfail('nn.functional.binary_cross_entropy_with_logits'),
    xfail('nn.functional.conv1d'),
    xfail('nn.functional.conv2d'),
    xfail('nn.functional.conv3d'),
    xfail('nn.functional.conv_transpose1d'),
    xfail('nn.functional.conv_transpose2d'),
    xfail('nn.functional.conv_transpose3d'),
    xfail('nn.functional.cosine_similarity'),
    xfail('nn.functional.ctc_loss'),
    xfail('nn.functional.dropout'),
    xfail('nn.functional.dropout2d'),
    xfail('nn.functional.dropout3d'),
    xfail('nn.functional.fractional_max_pool2d'),
    xfail('nn.functional.fractional_max_pool3d'),
    xfail('nn.functional.gaussian_nll_loss'),
    xfail('nn.functional.glu'),
    xfail('nn.functional.grid_sample'),
    xfail('nn.functional.group_norm'),
    xfail('nn.functional.instance_norm'),
    xfail('nn.functional.interpolate', 'area'),
    xfail('nn.functional.interpolate', 'bicubic'),
    xfail('nn.functional.interpolate', 'bilinear'),
    xfail('nn.functional.interpolate', 'linear'),
    xfail('nn.functional.interpolate', 'nearest'),
    xfail('nn.functional.interpolate', 'nearest-exact'),
    xfail('nn.functional.interpolate', 'trilinear'),
    xfail('nn.functional.local_response_norm'),
    xfail('nn.functional.logsigmoid'),
    xfail('nn.functional.margin_ranking_loss'),
    xfail('nn.functional.max_pool1d'),
    xfail('nn.functional.max_pool2d'),
    xfail('nn.functional.max_pool3d'),
    xfail('nn.functional.max_unpool1d'),
    xfail('nn.functional.max_unpool1d', 'grad'),
    xfail('nn.functional.max_unpool2d'),
    xfail('nn.functional.max_unpool2d', 'grad'),
    xfail('nn.functional.max_unpool3d'),
    xfail('nn.functional.max_unpool3d', 'grad'),
    xfail('nn.functional.multi_margin_loss'),
    xfail('nn.functional.multilabel_margin_loss'),
    xfail('nn.functional.multilabel_soft_margin_loss'),
    xfail('nn.functional.pad', 'reflect'),
    xfail('nn.functional.pad', 'replicate'),
    xfail('nn.functional.pad', 'replicate_negative'),
    xfail('nn.functional.pdist'),
    xfail('nn.functional.rrelu'),
    xfail('nn.functional.threshold'),
    xfail('nn.functional.unfold'),
    xfail('nn.functional.upsample_bilinear'),
    xfail('nn.functional.upsample_nearest'),
    xfail('nonzero'),
    xfail('nonzero_static'),
    xfail('normal'),
    xfail('normal', 'in_place'),
    xfail('normal', 'number_mean'),
    xfail('ormqr'),
    xfail('pca_lowrank'),
    xfail('permute'),
    xfail('pinverse'),
    xfail('polar'),
    xfail('put'),
    xfail('quantile'),
    xfail('rand_like'),
    xfail('randint_like'),
    xfail('randn_like'),
    xfail('ravel'),
    xfail('renorm'),
    xfail('repeat_interleave'),
    xfail('reshape'),
    xfail('reshape_as'),
    xfail('resize_'),
    xfail('resize_as_'),
    xfail('roll'),
    xfail('rot90'),
    xfail('scatter'),
    xfail('scatter_add'),
    xfail('scatter_reduce', 'amax'),
    xfail('scatter_reduce', 'amin'),
    xfail('scatter_reduce', 'mean'),
    xfail('scatter_reduce', 'prod'),
    xfail('scatter_reduce', 'sum'),
    xfail('searchsorted'),
    xfail('select'),
    xfail('select_scatter'),
    xfail('slice'),
    xfail('special.airy_ai'),
    xfail('special.bessel_y0'),
    xfail('special.bessel_y1'),
    xfail('special.chebyshev_polynomial_t'),
    xfail('special.chebyshev_polynomial_u'),
    xfail('special.chebyshev_polynomial_v'),
    xfail('special.chebyshev_polynomial_w'),
    xfail('special.entr'),
    xfail('special.hermite_polynomial_h'),
    xfail('special.hermite_polynomial_he'),
    xfail('special.laguerre_polynomial_l'),
    xfail('special.legendre_polynomial_p'),
    xfail('special.modified_bessel_i0'),
    xfail('special.modified_bessel_i1'),
    xfail('special.modified_bessel_k0'),
    xfail('special.modified_bessel_k1'),
    xfail('special.scaled_modified_bessel_k0'),
    xfail('special.scaled_modified_bessel_k1'),
    xfail('special.shifted_chebyshev_polynomial_t'),
    xfail('special.shifted_chebyshev_polynomial_u'),
    xfail('special.shifted_chebyshev_polynomial_v'),
    xfail('special.shifted_chebyshev_polynomial_w'),
    xfail('special.xlog1py'),
    xfail('squeeze', 'multiple'),
    xfail('stft'),
    xfail('svd_lowrank'),
    xfail('t'),
    xfail('take'),
    xfail('take_along_dim'),
    xfail('tensor_split'),
    xfail('to_sparse'),
    xfail('transpose'),
    xfail('transpose_copy'),
    xfail('triangular_solve'),
    xfail('unbind'),
    xfail('unflatten'),
    xfail('unfold'),
    xfail('unfold_copy'),
    xfail('uniform'),
    xfail('unique'),
    xfail('unique_consecutive'),
    xfail('unsafe_split'),
    xfail('unsqueeze'),
    xfail('view'),
    xfail('view_as'),
    xfail('vsplit'),
    skip('__rmatmul__'),
    skip('_segment_reduce', 'lengths'),
    skip('_segment_reduce', 'offsets'),
    skip('argwhere'),
    skip('cumprod'),
    skip('empty'),
    skip('empty_like'),
    skip('empty_permuted'),
    skip('empty_strided'),
    skip('fft.hfft'),
    skip('fft.hfft2'),
    skip('fft.hfftn'),
    skip('fft.ifftn'),
    skip('fft.irfft'),
    skip('isclose'),
    skip('isreal'),
    skip('istft'),
    skip('masked.mean'),
    skip('masked.normalize'),
    skip('masked.std'),
    skip('masked.var'),
    skip('matmul'),
    skip('meshgrid', 'list_of_tensors'),
    skip('meshgrid', 'variadic_tensors'),
    skip('new_empty'),
    skip('new_empty_strided'),
    skip('nn.functional.cosine_embedding_loss'),
    skip('nn.functional.embedding'),
    skip('nn.functional.embedding_bag'),
    skip('nn.functional.feature_alpha_dropout', 'with_train'),
    skip('nn.functional.feature_alpha_dropout', 'without_train'),
    skip('nn.functional.hinge_embedding_loss'),
    skip('nn.functional.multi_head_attention_forward'),
    skip('nn.functional.scaled_dot_product_attention'),
    skip('nn.functional.softmin'),
    skip('prod'),
    skip('squeeze'),
}
