# Owner(s): ["module: inductor"]
import contextlib
import dataclasses
import re
import unittest
from unittest import mock

import torch
from torch._inductor import config
from torch._inductor.async_compile import AsyncCompile
from torch._inductor.autows_utils import has_two_ctas, meta_ws_enabled
from torch._inductor.codegen import simd
from torch._inductor.heuristics.registry import _HEURISTIC_CACHE, get_template_heuristic
from torch._inductor.heuristics.template.triton import (
    _use_template_autows,
    BaseHeuristicSingleton,
    BlackwellGPUGemmConfig,
    CUDABlackwellAddmmPersistentTMATemplateConfigHeuristic,
    CUDABlackwellPersistentTMATemplateConfigHeuristic,
    CUDAScaledBlackwellTMATemplateConfigHeuristic,
    GemmConfig,
    TMATemplateConfigMixin,
)
from torch._inductor.ir import MultiTemplateBuffer
from torch._inductor.kernel.mm import (
    blackwell_ws_persistent_tma_mm_template,
    persistent_tma_mm_template,
    scaled_mm_device_tma_epilogue_scaling_template,
    scaled_mm_device_tma_main_loop_scaling_template,
)
from torch._inductor.kernel.mm_common import blackwell_persistent_mm_grid
from torch._inductor.kernel_inputs import MMKernelInputs
from torch._inductor.scheduler import Scheduler
from torch._inductor.test_case import run_tests, TestCase
from torch._inductor.utils import get_num_sms, run_and_get_code
from torch.nn.functional import scaled_mm, ScalingType  # type: ignore[attr-defined]
from torch.testing import FileCheck
from torch.testing._internal.common_utils import (
    instantiate_parametrized_tests,
    parametrize,
)
from torch.testing._internal.inductor_utils import GPU_TYPE, HAS_CPU, HAS_GPU
from torch.utils._triton import (
    has_datacenter_blackwell_tma_device,
    has_triton_tma_device,
)


def has_tlx() -> bool:
    """Check if TLX (Triton Language eXtensions) is available."""
    try:
        import triton.language.extra.tlx  # noqa: F401

        return True
    except ImportError:
        return False


_PRIOR_FP32_MATMUL_PRECISION: str | None = None


def setUpModule():
    global _PRIOR_FP32_MATMUL_PRECISION
    _PRIOR_FP32_MATMUL_PRECISION = torch.get_float32_matmul_precision()
    torch.set_float32_matmul_precision("high")


def tearDownModule():
    global _PRIOR_FP32_MATMUL_PRECISION
    if _PRIOR_FP32_MATMUL_PRECISION is not None:
        torch.set_float32_matmul_precision(_PRIOR_FP32_MATMUL_PRECISION)
        _PRIOR_FP32_MATMUL_PRECISION = None


@instantiate_parametrized_tests
class TestMaxAutotuneBlackwell(TestCase):
    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("a_transposed", (False, True))
    @parametrize("b_transposed", (False, True))
    @parametrize("dynamic", (False, True))
    @parametrize("tma_store", (False, True))
    @parametrize("epilogue_subtile", (1, 2, 4))
    @parametrize("host_side_tma", (False, True))
    def test_blackwell_max_autotune_regular_mm_persistent_tma(
        self,
        a_transposed: bool,
        b_transposed: bool,
        dynamic: bool,
        tma_store: bool,
        epilogue_subtile: int,
        host_side_tma: bool,
    ):
        def mm(a, b):
            # TMA requires 16-byte alignment: here we repeat the dims
            # by the factor of 8, as float16 is 2-byte. All dims are
            # repeated due to the possible transpositions below.
            a = a.repeat(8, 8)
            b = b.repeat(8, 8)
            if a_transposed:
                a = a.T
            if b_transposed:
                b = b.T

            return torch.mm(a, b)

        M, N, K = 32, 16, 48
        a = (
            torch.randn(*((K, M) if a_transposed else (M, K)))
            .to(torch.float16)
            .to(GPU_TYPE)
        )
        b = (
            torch.randn(*((N, K) if b_transposed else (K, N)))
            .to(torch.float16)
            .to(GPU_TYPE)
        )

        epilogue_subtile_regex = f"EPILOGUE_SUBTILE={epilogue_subtile}"
        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_template_tma_store": tma_store,
                "triton.enable_host_side_tma": host_side_tma,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                "test_configs.autotune_choice_desc_regex": epilogue_subtile_regex,
            }
        ):
            c_actual, code = run_and_get_code(torch.compile(mm, dynamic=dynamic), a, b)
            c_expected = mm(a, b)

        torch.testing.assert_close(c_actual, c_expected, atol=1e-2, rtol=1e-2)
        if tma_store:
            # Verify that we are using a TMA implementation
            # Note: The tma_descriptor0 is generated by the kernel. If the
            # code generation process changes this could change.
            write_api = "tma_descriptor0.store"
        else:
            write_api = "tl.store"
        fc = FileCheck().check("triton_tem_fused_mm")
        if host_side_tma:
            fc.check("host_tma_descriptor_args")
            if not tma_store:
                fc.check_not("tl.make_tensor_descriptor")
        else:
            fc.check("tl.make_tensor_descriptor")
        fc.check(write_api).run(code[0])
        if host_side_tma and tma_store:
            # Loads are host-side, so the TMA store is the only descriptor
            # still built in-kernel.
            FileCheck().check_count("tl.make_tensor_descriptor", 1, exactly=True).run(
                code[0]
            )
            FileCheck().check("tl.make_tensor_descriptor(out_ptr0").run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("a_transposed", (False, True))
    @parametrize("b_transposed", (False, True))
    @parametrize("host_side_tma", (False, True))
    def test_blackwell_square_operand_dim_order(
        self, a_transposed: bool, b_transposed: bool, host_side_tma: bool
    ):
        # A square operand has the same descriptor shape under either dim_order,
        # so only the strides distinguish row-major from transposed. Picking the
        # wrong order is invisible in the shape and shows up as a wrong result.
        S = 512
        a = torch.randn(S, S).to(torch.float16).to(GPU_TYPE)
        b = torch.randn(S, S).to(torch.float16).to(GPU_TYPE)

        def mm(a, b):
            return torch.mm(a.T if a_transposed else a, b.T if b_transposed else b)

        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_host_side_tma": host_side_tma,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
            }
        ):
            actual, code = run_and_get_code(torch.compile(mm), a, b)
        torch.testing.assert_close(actual, mm(a, b), atol=1e-2, rtol=1e-2)
        fc = FileCheck().check("triton_tem_fused")
        if host_side_tma:
            fc.check("host_tma_descriptor_args").check_not("tl.make_tensor_descriptor")
        else:
            fc.check("tl.make_tensor_descriptor")
        fc.run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("op", ("mm", "addmm"))
    def test_blackwell_host_side_tma_transposed_b(self, op: str):
        # Regression test for host-side TMA with a column-major / transposed B
        # operand (B_ROW_MAJOR=False, the nn.Linear `x @ W.t()` case).
        # Previously the host launcher re-permuted the runtime tensor's own
        # dims -- which are in base layout for a transposed operand -- producing
        # an incorrect result. Also covers addmm host-side TMA, previously
        # untested.
        M, N, K = 512, 256, 512
        a = torch.randn(M, K).to(torch.float16).to(GPU_TYPE)
        # b is [N, K]; b.t() is the [K, N] column-major operand.
        b = torch.randn(N, K).to(torch.float16).to(GPU_TYPE)
        bias = torch.randn(N).to(torch.float16).to(GPU_TYPE)

        def fn(a, b, bias):
            if op == "addmm":
                return torch.addmm(bias, a, b.t())
            return torch.mm(a, b.t())

        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_host_side_tma": True,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
            }
        ):
            c_actual, code = run_and_get_code(torch.compile(fn), a, b, bias)
        c_expected = fn(a, b, bias)
        torch.testing.assert_close(c_actual, c_expected, atol=1e-2, rtol=1e-2)
        # host-side TMA: descriptors come from the launcher, none built in-kernel
        FileCheck().check("triton_tem_fused").check_not(
            "tl.make_tensor_descriptor"
        ).run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("host_side_tma", (False, True))
    def test_blackwell_size_one_dim_persistent_tma(self, host_side_tma: bool):
        # A contiguous [1, K] operand is reported transposed by
        # Layout.is_transposed(), which skips size-1 dims, so the descriptor was
        # built with a non-unit trailing stride.
        M, N, K = 1, 512, 1024
        a = torch.randn(M, K).to(torch.float16).to(GPU_TYPE)
        b = torch.randn(K, N).to(torch.float16).to(GPU_TYPE)

        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_host_side_tma": host_side_tma,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
            }
        ):
            c_actual, code = run_and_get_code(torch.compile(torch.mm), a, b)
        torch.testing.assert_close(c_actual, torch.mm(a, b), atol=1e-2, rtol=1e-2)
        fc = FileCheck().check("triton_tem_fused_mm")
        if host_side_tma:
            fc.check("host_tma_descriptor_args")
            fc.check_not("tl.make_tensor_descriptor(base=")
        else:
            fc.check("tl.make_tensor_descriptor(base=")
        fc.run(code[0])

    # NOTE: the current Inductor template verifies that the scaling mode is either per-tensor or per-row
    # TODO: support additional scaling modes for Blackwell
    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("dynamic", (False, True))
    @parametrize("tma_store", (False, True))
    @parametrize("host_side_tma", (False, True))
    def test_blackwell_max_autotune_scaled_mm_per_tensor_persistent_tma(
        self,
        dynamic: bool,
        tma_store: bool,
        host_side_tma: bool,
    ):
        def scaled_mm(a, b, scale_a, scale_b):
            # NOTE: Inductor constrains a to be row_major and b to be col_major
            return torch._scaled_mm(
                a, b.t(), scale_a, scale_b, use_fast_accum=True, out_dtype=torch.float16
            )

        def get_scale_per_tensor(t):
            scale = torch.finfo(torch.float8_e4m3fn).max / t.abs().max()
            return scale.to(torch.float32)

        # TMA requires 16-byte alignment: here we repeat the dims
        # by the factor of 8, as float16 is 2-byte.
        M, N, K = 32, 16, 48
        a = (torch.randn((M, K)).to(torch.float16).to(GPU_TYPE)).repeat(8, 8)
        b = (torch.randn((N, K)).to(torch.float16).to(GPU_TYPE)).repeat(8, 8)

        scale_a = get_scale_per_tensor(a)
        scale_b = get_scale_per_tensor(b)

        a = a.to(torch.float8_e4m3fn)
        b = b.to(torch.float8_e4m3fn)

        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_template_tma_store": tma_store,
                "triton.enable_host_side_tma": host_side_tma,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
            }
        ):
            c_actual, code = run_and_get_code(
                torch.compile(scaled_mm, dynamic=dynamic), a, b, scale_a, scale_b
            )
            c_expected = scaled_mm(a, b, scale_a, scale_b)

        torch.testing.assert_close(c_actual, c_expected, atol=1e-2, rtol=0.5)
        if tma_store:
            # Verify that we are using a TMA implementation
            # Note: The tma_descriptor0 is generated by the kernel. If the
            # code generation process changes this could change.
            write_api = "tma_descriptor0.store"
        else:
            write_api = "tl.store"
        fc = FileCheck().check("triton_tem_fused__scaled_mm")
        if host_side_tma:
            fc.check("host_tma_descriptor_args")
        else:
            fc.check("tl.make_tensor_descriptor(base=")
        fc.check("_desc.load(").check(write_api).run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("dynamic", (False, True))
    @parametrize("tma_store", (False, True))
    @parametrize("host_side_tma", (False, True))
    def test_blackwell_max_autotune_scaled_mm_per_row_persistent_tma(
        self,
        dynamic: bool,
        tma_store: bool,
        host_side_tma: bool,
    ):
        def scaled_mm(a, b, scale_a, scale_b):
            # NOTE: Inductor constrains a to be row_major and b to be col_majo
            return torch._scaled_mm(
                a,
                b.t(),
                scale_a,
                scale_b.t(),
                use_fast_accum=True,
                out_dtype=torch.bfloat16,
            )

        def get_scale_per_row(t):
            scale = (
                torch.finfo(torch.float8_e4m3fn).max
                / t.abs().max(dim=1, keepdim=True).values
            )
            return scale.to(torch.float32)

        # TMA requires 16-byte alignment: here we repeat the dims
        # by the factor of 8, as float16 is 2-byte.
        M, N, K = 32, 16, 48
        a = (torch.randn((M, K)).to(torch.bfloat16).to(GPU_TYPE)).repeat(8, 8)
        b = (torch.randn((N, K)).to(torch.bfloat16).to(GPU_TYPE)).repeat(8, 8)

        scale_a = get_scale_per_row(a)
        scale_b = get_scale_per_row(b)

        a = a.to(torch.float8_e4m3fn)
        b = b.to(torch.float8_e4m3fn)

        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_template_tma_store": tma_store,
                "triton.enable_host_side_tma": host_side_tma,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
            }
        ):
            c_actual, code = run_and_get_code(
                torch.compile(scaled_mm, dynamic=dynamic), a, b, scale_a, scale_b
            )
            c_expected = scaled_mm(a, b, scale_a, scale_b)

        torch.testing.assert_close(c_actual, c_expected, atol=1e-2, rtol=0.5)
        if tma_store:
            # Verify that we are using a TMA implementation
            # Note: The tma_descriptor0 is generated by the kernel. If the
            # code generation process changes this could change.
            write_api = "tma_descriptor0.store"
        else:
            write_api = "tl.store"
        fc = FileCheck().check("triton_tem_fused__scaled_mm")
        if host_side_tma:
            fc.check("host_tma_descriptor_args")
        else:
            fc.check("tl.make_tensor_descriptor(base=")
        fc.check("_desc.load(").check(write_api).run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("a_transposed", (False, True))
    @parametrize("b_transposed", (False, True))
    @parametrize("dynamic", (False, True))
    @parametrize("tma_store", (False, True))
    @parametrize("epilogue_subtile", (1, 2, 4))
    @parametrize("host_side_tma", (False, True))
    def test_blackwell_max_autotune_addmm_persistent_tma(
        self,
        a_transposed: bool,
        b_transposed: bool,
        dynamic: bool,
        tma_store: bool,
        epilogue_subtile: int,
        host_side_tma: bool,
    ):
        def addmm(x, a, b):
            # TMA requires 16-byte alignment: here we repeat the dims
            # by the factor of 8, as float16 is 2-byte. All dims are
            # repeated due to the possible transpositions below.
            x = x.repeat(8)
            a = a.repeat(8, 8)
            b = b.repeat(8, 8)

            if a_transposed:
                a = a.T
            if b_transposed:
                b = b.T

            return torch.addmm(x, a, b)

        M, N, K = 21, 31, 11
        a = (
            torch.randn(*((K, M) if a_transposed else (M, K)))
            .to(torch.float16)
            .to(GPU_TYPE)
        )
        b = (
            torch.randn(*((N, K) if b_transposed else (K, N)))
            .to(torch.float16)
            .to(GPU_TYPE)
        )
        x = torch.randn(N).to(torch.float16).to(GPU_TYPE)

        epilogue_subtile_regex = f"EPILOGUE_SUBTILE={epilogue_subtile}"
        with config.patch(
            {
                "max_autotune": True,
                "triton.enable_persistent_tma_matmul": True,
                "triton.enable_template_tma_store": tma_store,
                "triton.enable_host_side_tma": host_side_tma,
                "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                "test_configs.autotune_choice_desc_regex": epilogue_subtile_regex,
                # If we dynamically disable pipelining,
                # triton_blackwell_ws_persistent_tma template will
                # be picked and then cause mis-aligned memory access.
                # If we don't dynamically disable pipelining,
                # this template is skipped and triton_tem_fused_addmm_repeat_3
                # is used.
                #
                # Fundamentally we should fix the triton_blackwell_ws_persistent_tma template
                # The flag below work around the problem.
                #
                # This only happens in fbcode https://www.internalfb.com/diff/D101855575.
                # Can not repro it in OSS build.
                "triton.dynamic_disable_pipelining": not config.is_fbcode(),
            }
        ):
            c_actual, code = run_and_get_code(
                torch.compile(addmm, dynamic=dynamic), x, a, b
            )
            c_expected = addmm(x, a, b)

        make_desc_api = "tl.make_tensor_descriptor"
        read_api = "_desc.load("
        if tma_store:
            # Verify that we are using a TMA implementation
            # Note: The tma_descriptor0 is generated by the kernel. If the
            # code generation process changes this could change.
            write_api = "tma_descriptor0.store"
        else:
            write_api = "tl.store"

        # Verify that we are using a TMA implementation
        fc = FileCheck().check("triton_tem_fused_addmm")
        if host_side_tma:
            fc.check("host_tma_descriptor_args")
            if not tma_store:
                fc.check_not(make_desc_api)
        else:
            fc.check(make_desc_api)
        fc.check(read_api).check(write_api).run(code[0])
        if host_side_tma and tma_store:
            # Loads are host-side, so the TMA store is the only descriptor
            # still built in-kernel.
            FileCheck().check_count(make_desc_api, 1, exactly=True).run(code[0])

        torch.testing.assert_close(c_actual, c_expected, atol=1e-2, rtol=1e-2)

    def test_resolved_host_tma_descriptor_args_symbolic_block_shape(self):
        from types import SimpleNamespace

        from torch._inductor.codegen.triton import TritonKernel

        # A block shape naming an autotuned kernel arg stays a name for the
        # launcher to look up per config; anything else resolves to a value.
        signature = [SimpleNamespace(name="XBLOCK")]
        kernel = SimpleNamespace(
            args=SimpleNamespace(python_argdefs=lambda: ([], [], signature, [])),
            persistent_reduction=False,
            host_tma_descriptor_args={
                "in_ptr0": SimpleNamespace(
                    block_shape=["XBLOCK", 128, "YBLOCK"],
                    shape=[1024, "s0"],
                    strides=["s0", 1],
                )
            },
        )

        resolved = TritonKernel.resolved_host_tma_descriptor_args(kernel)

        self.assertEqual(
            resolved["in_ptr0"],
            {
                "block_shape": ["XBLOCK", 128, "YBLOCK"],
                "shape": [1024, "s0"],
                "strides": ["s0", 1],
            },
        )
        # An already-resolved dict passes through untouched.
        kernel.host_tma_descriptor_args = {"in_ptr1": {"block_shape": [64]}}
        self.assertEqual(
            TritonKernel.resolved_host_tma_descriptor_args(kernel),
            {"in_ptr1": {"block_shape": [64]}},
        )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_host_side_tma_signature_upgraded_at_precompile(self):
        from torch._inductor.runtime import triton_heuristics

        def mm(a, b):
            return torch.mm(a, b)

        a = torch.randn(1024, 1024).to(torch.float16).to(GPU_TYPE)
        b = torch.randn(1024, 1024).to(torch.float16).to(GPU_TYPE)

        captured: list[dict] = []
        orig = triton_heuristics.CachingAutotuner._create_compile_meta

        def _spy(self, cfg):
            meta = orig(self, cfg)
            if self.inductor_meta.get("host_tma_descriptor_args"):
                captured.append(dict(meta["signature"]))
            return meta

        with (
            config.patch(
                {
                    "max_autotune": True,
                    "triton.enable_persistent_tma_matmul": True,
                    "triton.enable_host_side_tma": True,
                    "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                }
            ),
            mock.patch.object(
                triton_heuristics.CachingAutotuner, "_create_compile_meta", _spy
            ),
        ):
            actual, code = run_and_get_code(torch.compile(mm), a, b)

        torch.testing.assert_close(actual, mm(a, b), atol=1e-2, rtol=1e-2)
        self.assertTrue(captured, "no host-side TMA kernel was precompiled")
        upgraded = [
            ty
            for sig in captured
            for ty in sig.values()
            if isinstance(ty, str) and ty.startswith("tensordesc<")
        ]
        self.assertTrue(upgraded, f"no arg upgraded to tensordesc<>: {captured}")
        # Block dims must be concrete by this point: the launcher resolves the
        # autotuned symbol per config.
        FileCheck().check_regex(r"tensordesc<\w+\[\d+, \d+\]>").run("\n".join(upgraded))
        # The upgrade is the launcher's job now, so codegen must not have
        # already baked it into the generated module.
        FileCheck().check_not("tensordesc<").run(code[0])


@instantiate_parametrized_tests
@unittest.skipIf(
    config.triton.enable_host_side_tma,
    "epilogue fusion registers a descriptor the host path cannot resolve",
)
class TestBlackwellTMAStoreFusion(TestCase):
    """Tests for TMA store with fused pointwise epilogues on Blackwell."""

    @staticmethod
    def _make_tma_store_test_config(epilogue_subtile: int) -> BlackwellGPUGemmConfig:
        """FLATTEN=False test config for TMA store pointwise epilogue fusion.

        The WS pipeline doesn't yet support FLATTEN=True + TMA descriptor store.
        """
        return BlackwellGPUGemmConfig(
            128,
            128,
            64,
            3,
            4,
            epilogue_subtile=epilogue_subtile,
            warp_specialize=False,
            flatten=False,
        )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("shape", ((512, 256, 256), (4096, 256, 256)))
    @parametrize("epilogue_subtile", (1, 2))
    def test_blackwell_mm_sigmoid_epilogue_fusion_tma_store(
        self,
        shape: tuple[int, int, int],
        epilogue_subtile: int,
    ):
        """Verify fused mm + sigmoid epilogue with TMA store (FLATTEN=False)."""

        def fn(x, W):
            mm = torch.mm(x, W.T)
            return x * (2.0 * torch.sigmoid(mm))

        M, N, K = shape
        x = torch.randn(M, K, dtype=torch.bfloat16, device=GPU_TYPE)
        W = torch.randn(N, K, dtype=torch.bfloat16, device=GPU_TYPE)

        test_config = self._make_tma_store_test_config(epilogue_subtile)
        # Ensure the heuristic cache is populated, then patch mm_configs.
        from torch._inductor.heuristics.template.registry import get_template_heuristic

        _cache_keys = [
            ("triton::blackwell_ws_persistent_tma", "cuda", "mm"),
            ("triton::blackwell_ws_persistent_tma", "cuda", "addmm"),
        ]
        orig_configs_by_key = {}
        for key in _cache_keys:
            h = get_template_heuristic(*key)
            orig_configs_by_key[key] = h.mm_configs
            h.mm_configs = [test_config]
        try:
            with config.patch(
                {
                    "max_autotune": True,
                    "triton.enable_persistent_tma_matmul": True,
                    "triton.enable_template_tma_store": True,
                    "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                }
            ):
                actual, code = run_and_get_code(torch.compile(fn), x, W)
                expected = fn(x, W)
        finally:
            for key, orig in orig_configs_by_key.items():
                if key in _HEURISTIC_CACHE:
                    _HEURISTIC_CACHE[key].mm_configs = orig

        torch.testing.assert_close(actual, expected, atol=1e-1, rtol=1e-1)

        FileCheck().check("triton_tem_fused_mm").check("tma_descriptor").check(
            ".store"
        ).run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("shape", ((512, 256, 256), (4096, 256, 256)))
    @parametrize("epilogue_subtile", (1, 2))
    def test_blackwell_addmm_relu_epilogue_fusion_tma_store(
        self,
        shape: tuple[int, int, int],
        epilogue_subtile: int,
    ):
        """Verify fused addmm + relu epilogue with TMA store (FLATTEN=False)."""

        def fn(x, W, bias):
            mm = torch.mm(x, W.T)
            return torch.relu(mm + bias)

        M, N, K = shape
        x = torch.randn(M, K, dtype=torch.bfloat16, device=GPU_TYPE)
        W = torch.randn(N, K, dtype=torch.bfloat16, device=GPU_TYPE)
        bias = torch.randn(N, dtype=torch.bfloat16, device=GPU_TYPE)

        test_config = self._make_tma_store_test_config(epilogue_subtile)
        # Ensure the heuristic cache is populated, then patch mm_configs.
        from torch._inductor.heuristics.template.registry import get_template_heuristic

        _cache_keys = [
            ("triton::blackwell_ws_persistent_tma", "cuda", "mm"),
            ("triton::blackwell_ws_persistent_tma", "cuda", "addmm"),
        ]
        orig_configs_by_key = {}
        for key in _cache_keys:
            h = get_template_heuristic(*key)
            orig_configs_by_key[key] = h.mm_configs
            h.mm_configs = [test_config]
        try:
            with config.patch(
                {
                    "max_autotune": True,
                    "triton.enable_persistent_tma_matmul": True,
                    "triton.enable_template_tma_store": True,
                    "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                }
            ):
                actual, code = run_and_get_code(torch.compile(fn), x, W, bias)
                expected = fn(x, W, bias)
        finally:
            for key, orig in orig_configs_by_key.items():
                if key in _HEURISTIC_CACHE:
                    _HEURISTIC_CACHE[key].mm_configs = orig

        torch.testing.assert_close(actual, expected, atol=1e-1, rtol=1e-1)

        FileCheck().check("triton_tem_fused").check("tma_descriptor").check(
            ".store"
        ).run(code[0])


@instantiate_parametrized_tests
@unittest.skipIf(
    config.triton.enable_host_side_tma,
    "epilogue fusion registers a descriptor the host path cannot resolve",
)
class TestBlackwellTMALoadFusion(TestCase):
    """Tests for TMA load with fused pointwise epilogues on Blackwell."""

    @staticmethod
    def _make_tma_load_test_config(epilogue_subtile: int) -> BlackwellGPUGemmConfig:
        return BlackwellGPUGemmConfig(
            128,
            128,
            64,
            3,
            4,
            epilogue_subtile=epilogue_subtile,
            warp_specialize=False,
            flatten=False,
        )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("shape", ((512, 256, 256), (4096, 256, 256)))
    @parametrize("epilogue_subtile", (1, 2))
    def test_blackwell_mm_sigmoid_epilogue_tma_load(
        self,
        shape: tuple[int, int, int],
        epilogue_subtile: int,
    ):
        """Verify fused mm + sigmoid epilogue with TMA load (1 epilogue load)."""

        def fn(x, W):
            mm = torch.mm(x, W.T)
            return x * (2.0 * torch.sigmoid(mm))

        M, N, K = shape
        x = torch.randn(M, K, dtype=torch.bfloat16, device=GPU_TYPE)
        W = torch.randn(N, K, dtype=torch.bfloat16, device=GPU_TYPE)

        test_config = self._make_tma_load_test_config(epilogue_subtile=epilogue_subtile)
        from torch._inductor.heuristics.template.registry import get_template_heuristic

        _cache_keys = [
            ("triton::blackwell_ws_persistent_tma", "cuda", "mm"),
            ("triton::blackwell_ws_persistent_tma", "cuda", "addmm"),
        ]
        orig_configs_by_key = {}
        for key in _cache_keys:
            h = get_template_heuristic(*key)
            orig_configs_by_key[key] = h.mm_configs
            h.mm_configs = [test_config]
        try:
            with config.patch(
                {
                    "max_autotune": True,
                    "triton.enable_persistent_tma_matmul": True,
                    "triton.enable_tma_load_for_template_epilogue": True,
                    "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                }
            ):
                actual, code = run_and_get_code(torch.compile(fn), x, W)
                expected = fn(x, W)
        finally:
            for key, orig in orig_configs_by_key.items():
                if key in _HEURISTIC_CACHE:
                    _HEURISTIC_CACHE[key].mm_configs = orig

        torch.testing.assert_close(actual, expected, atol=1e-1, rtol=1e-1)

        FileCheck().check("triton_tem_fused_mm").check("tma_descriptor").check(
            ".load(["
        ).run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("shape", ((512, 256, 256), (4096, 256, 256)))
    @parametrize("epilogue_subtile", (1, 2))
    def test_blackwell_mm_scale_bias_epilogue_tma_load(
        self,
        shape: tuple[int, int, int],
        epilogue_subtile: int,
    ):
        """Verify fused mm * scale + bias epilogue with TMA load (2 epilogue loads)."""

        def fn(x, W, scale, bias):
            return torch.mm(x, W.T) * scale + bias

        M, N, K = shape
        x = torch.randn(M, K, dtype=torch.bfloat16, device=GPU_TYPE)
        W = torch.randn(N, K, dtype=torch.bfloat16, device=GPU_TYPE)
        scale = torch.randn(M, N, dtype=torch.bfloat16, device=GPU_TYPE)
        bias = torch.randn(M, N, dtype=torch.bfloat16, device=GPU_TYPE)

        test_config = self._make_tma_load_test_config(epilogue_subtile=epilogue_subtile)
        from torch._inductor.heuristics.template.registry import get_template_heuristic

        _cache_keys = [
            ("triton::blackwell_ws_persistent_tma", "cuda", "mm"),
            ("triton::blackwell_ws_persistent_tma", "cuda", "addmm"),
        ]
        orig_configs_by_key = {}
        for key in _cache_keys:
            h = get_template_heuristic(*key)
            orig_configs_by_key[key] = h.mm_configs
            h.mm_configs = [test_config]
        try:
            with config.patch(
                {
                    "max_autotune": True,
                    "triton.enable_persistent_tma_matmul": True,
                    "triton.enable_tma_load_for_template_epilogue": True,
                    "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                }
            ):
                actual, code = run_and_get_code(torch.compile(fn), x, W, scale, bias)
                expected = fn(x, W, scale, bias)
        finally:
            for key, orig in orig_configs_by_key.items():
                if key in _HEURISTIC_CACHE:
                    _HEURISTIC_CACHE[key].mm_configs = orig

        torch.testing.assert_close(actual, expected, atol=1e-1, rtol=1e-1)

        FileCheck().check("triton_tem_fused").check("tma_descriptor").check(
            ".load(["
        ).run(code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("shape", ((512, 256, 256), (4096, 256, 256)))
    @parametrize("epilogue_subtile", (1, 2))
    def test_blackwell_addmm_1d_bias_epilogue_tma_load(
        self,
        shape: tuple[int, int, int],
        epilogue_subtile: int,
    ):
        """Verify fused addmm with 1D bias epilogue with TMA load."""

        def fn(bias, x, W):
            return torch.addmm(bias, x, W.T)

        M, N, K = shape
        x = torch.randn(M, K, dtype=torch.bfloat16, device=GPU_TYPE)
        W = torch.randn(N, K, dtype=torch.bfloat16, device=GPU_TYPE)
        bias = torch.randn(N, dtype=torch.bfloat16, device=GPU_TYPE)

        test_config = self._make_tma_load_test_config(epilogue_subtile=epilogue_subtile)
        from torch._inductor.heuristics.template.registry import get_template_heuristic

        _cache_keys = [
            ("triton::blackwell_ws_persistent_tma", "cuda", "mm"),
            ("triton::blackwell_ws_persistent_tma", "cuda", "addmm"),
        ]
        orig_configs_by_key = {}
        for key in _cache_keys:
            h = get_template_heuristic(*key)
            orig_configs_by_key[key] = h.mm_configs
            h.mm_configs = [test_config]
        try:
            with config.patch(
                {
                    "max_autotune": True,
                    "triton.enable_persistent_tma_matmul": True,
                    "triton.enable_tma_load_for_template_epilogue": True,
                    "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                }
            ):
                actual, code = run_and_get_code(torch.compile(fn), bias, x, W)
                expected = fn(bias, x, W)
        finally:
            for key, orig in orig_configs_by_key.items():
                if key in _HEURISTIC_CACHE:
                    _HEURISTIC_CACHE[key].mm_configs = orig

        torch.testing.assert_close(actual, expected, atol=1e-1, rtol=1e-1)

        FileCheck().check("triton_tem_fused").check("tma_descriptor").check(
            ".load(["
        ).run(code[0])

    @staticmethod
    def _run_with_mm_config(
        fn,
        args,
        test_config,
        *extra_configs,
        autows=(1, False),
        dynamic=None,
        fused_ms=0.0,
        **patches,
    ):
        """Compile fn with only the given configs as Triton choices. Under
        template autoWS, only the (DATA_PARTITION_FACTOR, TWO_CTAS) = autows
        variants of them. Fused epilogue benchmarks report fused_ms, so by
        default every fusion the gates allow is kept."""
        keys = [
            ("triton::blackwell_ws_persistent_tma", "cuda", op)
            for op in ("mm", "addmm")
        ]
        heuristics = [get_template_heuristic(*key) for key in keys]
        # Template autoWS builds its configs from blackwell_persistent_mm_configs.
        orig = [(h.mm_configs, h.blackwell_persistent_mm_configs) for h in heuristics]
        configs = [
            test_config,
            # Epilogues are only benchmarked, and so reductions only fused,
            # when autotuning has more than one choice. This twin hosts the
            # same reductions.
            dataclasses.replace(test_config, num_stages=test_config.num_stages - 1),
            *extra_configs,
        ]
        for heuristic in heuristics:
            heuristic.mm_configs = heuristic.blackwell_persistent_mm_configs = configs
        # The addmm heuristic inherits _generate_autows_configs from mm's.
        heuristic = heuristics[0]
        generate_autows_configs = type(heuristic)._generate_autows_configs

        def autows_configs(self):
            return [
                cfg
                for cfg in generate_autows_configs(self)
                if (cfg.data_partition_factor, cfg.two_ctas) == autows
            ]

        try:
            with (
                config.patch(
                    {
                        "max_autotune": True,
                        "max_autotune_gemm_backends": "TRITON",
                        "triton.enable_persistent_tma_matmul": True,
                        "test_configs.autotune_choice_name_regex": "blackwell_ws_persistent_tma",
                        "benchmark_template_fusion": True,
                        **patches,
                    }
                ),
                mock.patch.object(
                    type(heuristic), "_generate_autows_configs", autows_configs
                ),
                mock.patch.object(
                    Scheduler, "benchmark_codegened_module", return_value=(fused_ms, "")
                ),
            ):
                return run_and_get_code(torch.compile(fn, dynamic=dynamic), *args)
        finally:
            for key, configs in zip(keys, orig):
                if (cached := _HEURISTIC_CACHE.get(key)) is not None:
                    cached.mm_configs, cached.blackwell_persistent_mm_configs = configs

    @staticmethod
    def _poison_outputs():
        """Poison allocations so unwritten outputs show up as NaN."""

        def empty_strided(size, stride, dtype):
            out = torch.empty_strided(size, stride, dtype=dtype, device=GPU_TYPE)
            out.untyped_storage().fill_(255)
            return out

        return mock.patch("torch._C._dynamo.guards._empty_strided_cuda", empty_strided)

    def _run_reduction(
        self,
        fn,
        M,
        K,
        N,
        test_config,
        *extra_configs,
        tol=0,
        dtype=torch.bfloat16,
        **patches,
    ):
        """Run fn on a (M, K) @ (K, N) GEMM and compare against eager. Returns the
        generated kernel names and the output code."""
        # Small integers make the GEMM and the sums exact, so results don't
        # depend on summation order and must match eager bitwise.
        a = torch.randint(-1, 2, (M, K), device=GPU_TYPE).to(dtype)
        b = torch.randint(-1, 2, (K, N), device=GPU_TYPE).to(dtype)
        with self._poison_outputs():
            actual, code = self._run_with_mm_config(
                fn, (a, b), test_config, *extra_configs, **patches
            )
        self.assertEqual(actual, fn(a, b), atol=tol, rtol=tol)
        return re.findall(r"def (triton_\w+)\(", code[0]), code[0]

    def _assert_row_fused(self, kernels, code, op="sum"):
        self.assertEqual(len(kernels), 1, kernels)
        self.assertTrue(kernels[0].startswith("triton_tem_fused"), kernels)
        FileCheck().check("tl.sum" if op != "amax" else "max2").run(code)

    ROW_OPS = {
        "sum": lambda a, b: (a @ b).float().sum(-1),
        # Every row is negative, so unmasked out-of-range columns would win.
        "amax": lambda a, b: ((a @ b) - 100).amax(-1),
        "mean": lambda a, b: (a @ b).float().mean(-1),
        "mean_and_sqmean": lambda a, b: (
            (c := (a @ b).float()).mean(-1),
            c.pow(2).mean(-1),
        ),
        "var_mean": lambda a, b: torch.var_mean((a @ b).float(), -1),
        "sum_and_out": lambda a, b: ((c := a @ b), c.float().sum(-1)),
        "extra_input": lambda a, b: ((a @ b).float() * b[0].float()).sum(-1),
    }

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("op", tuple(ROW_OPS))
    @parametrize("shape", ((1024, 128, 512), (1000, 120, 512)))
    @parametrize("variant", ("ws", "ws_tma_store", "ws_flatten"))
    def test_blackwell_mm_row_reduction_epilogue_fusion(
        self, op: str, shape: tuple[int, int, int], variant: str
    ):
        if variant == "ws_flatten" and meta_ws_enabled():
            self.skipTest("meta WS doesn't support FLATTEN")
        M, N, K = shape
        test_config = BlackwellGPUGemmConfig(
            128, 128, 64, 3, 8, warp_specialize=True, flatten=variant == "ws_flatten"
        )
        kernels, code = self._run_reduction(
            self.ROW_OPS[op],
            M,
            K,
            N,
            test_config,
            # Divisions (mean, var) may be reassociated.
            tol=1e-5 if "mean" in op else 0,
            **{
                "triton.template_reduction_epilogue": True,
                "triton.enable_template_tma_store": variant == "ws_tma_store",
            },
        )
        self._assert_row_fused(kernels, code, op)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_row_reduction_epilogue_fusion_fp16(self):
        kernels, code = self._run_reduction(
            self.ROW_OPS["sum_and_out"],
            1024,
            512,
            128,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            dtype=torch.float16,
            **{"triton.template_reduction_epilogue": True},
        )
        self._assert_row_fused(kernels, code)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_row_reduction_epilogue_fusion_randn(self):
        fn = self.ROW_OPS["sum"]
        a = torch.randn(1024, 512, device=GPU_TYPE, dtype=torch.bfloat16)
        b = torch.randn(512, 128, device=GPU_TYPE, dtype=torch.bfloat16)
        with self._poison_outputs():
            actual, code = self._run_with_mm_config(
                fn,
                (a, b),
                BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
                **{"triton.template_reduction_epilogue": True},
            )
        torch.testing.assert_close(actual, fn(a, b), atol=1e-3, rtol=1e-5)
        self._assert_row_fused(re.findall(r"def (triton_\w+)\(", code[0]), code[0])

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_addmm_row_reduction_epilogue_fusion(self):
        M, K, N = 1024, 512, 128
        bias = torch.randint(-1, 2, (N,), device=GPU_TYPE).to(torch.bfloat16)

        def fn(a, b):
            return torch.addmm(bias, a, b).float().sum(-1)

        kernels, code = self._run_reduction(
            fn,
            M,
            K,
            N,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True},
        )
        self._assert_row_fused(kernels, code)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize(
        "case",
        (
            "disabled",
            "unprofitable",
            "no_benchmark",
            "max_values",
            "argmax",
            "subtile",
            "data_partition",
            "two_ctas",
            "dynamic",
            "cpp_wrapper",
            "fp32",
            "wide_n",
        ),
    )
    def test_blackwell_mm_row_reduction_epilogue_not_fused(self, case: str):
        """The reduction stays unfused when the flag is off, when the fused
        kernel benchmarks slower or isn't benchmarked, for arg reductions,
        configs that can't host it (EPILOGUE_SUBTILE > 1, data partitioning,
        2CTA), dynamic shapes, cpp_wrapper, fp32 outputs,
        and tiles narrower than N."""
        fn = {
            "max_values": lambda a, b: (a @ b).float().max(-1).values,
            "argmax": lambda a, b: (a @ b).argmax(-1),
        }.get(case, self.ROW_OPS["sum"])
        # With N == 8, BLOCK_N is clamped to 16, so one of two subtiles spans N.
        M, K, N = 1024, 512, {"wide_n": 256, "subtile": 8}.get(case, 128)
        test_config = BlackwellGPUGemmConfig(
            128,
            128,
            64,
            3,
            8,
            epilogue_subtile=2 if case == "subtile" else 1,
        )
        patches = {
            "benchmark_template_fusion": case != "no_benchmark",
            "triton.template_reduction_epilogue": case != "disabled",
            "triton.enable_template_tma_store": case == "two_ctas",
            "cpp_wrapper": case == "cpp_wrapper",
        }
        autows = {"data_partition": (2, False), "two_ctas": (1, True)}.get(
            case, (1, False)
        )
        if case in ("data_partition", "two_ctas") and not _use_template_autows():
            self.skipTest("needs template autoWS")
        if case == "two_ctas" and not has_two_ctas():
            self.skipTest("needs 2CTA support in Triton")
        if case == "subtile" and meta_ws_enabled():
            self.skipTest("meta WS has no valid choice for this GEMM")
        if case == "fp32" and meta_ws_enabled():
            self.skipTest("fp32 GEMMs fail to compile under meta WS")
        if case == "cpp_wrapper":
            # The cpp wrapper can't embed the template's source.
            patches["triton.autotune_at_compile_time"] = True
        dtype = torch.float32 if case == "fp32" else torch.bfloat16
        a = torch.randint(-1, 2, (M, K), device=GPU_TYPE).to(dtype)
        b = torch.randint(-1, 2, (K, N), device=GPU_TYPE).to(dtype)
        actual, code = self._run_with_mm_config(
            fn,
            (a, b),
            test_config,
            autows=autows,
            dynamic=case == "dynamic" or None,
            # Otherwise fused kernels benchmark as free, so a perf rejection
            # can't hide a missing gate.
            fused_ms=1e6 if case == "unprofitable" else 0.0,
            **patches,
        )
        self.assertEqual(actual, fn(a, b), atol=0, rtol=0)
        kernels = re.findall(r"def (triton_\w+)\(", code[0])
        self.assertTrue(any(k.startswith("triton_tem") for k in kernels), kernels)
        self.assertTrue(
            any(k.startswith(("triton_per", "triton_red")) for k in kernels), kernels
        )

    COL_OPS = {
        "sum": lambda a, b: (a @ b).float().sum(0),
        # Unmasked out-of-range rows would each add 1.
        "plus1": lambda a, b: ((a @ b).float() + 1).sum(0),
        "amax": lambda a, b: ((a @ b) - 100).amax(0),
        "amin": lambda a, b: ((a @ b) + 100).amin(0),
        "mean": lambda a, b: (a @ b).float().mean(0),
        "center": lambda a, b: (c := (a @ b).float()) - c.sum(0),
        "sum_bf16": lambda a, b: (a @ b).sum(0),
        "sum_and_out": lambda a, b: ((c := a @ b), c.float().sum(0)),
        "relu_sum": lambda a, b: (a @ b).float().relu().sum(0, keepdim=True),
    }

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("op", tuple(COL_OPS))
    @parametrize("M", (1000, 1001, 4096))
    @parametrize("split", (False, True))
    def test_blackwell_mm_col_reduction_epilogue_fusion(
        self, op: str, M: int, split: bool
    ):
        kernels, _ = self._run_reduction(
            self.COL_OPS[op],
            M,
            128,
            200,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True, "split_reductions": split},
        )
        self.assertTrue(kernels[0].startswith("triton_tem_fused"), kernels)
        # Nodes reading the finished column results stay unfused.
        self.assertEqual(len(kernels), 2 if op in ("mean", "center") else 1, kernels)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_col_reduction_epilogue_with_pointwise(self):
        """A pointwise node reading the output in place fuses next to a column
        reduction."""

        def fn(a, b):
            c = a @ b
            return c.relu(), c.float().sum(0)

        kernels, _ = self._run_reduction(
            fn,
            1024,
            128,
            256,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True},
        )
        self.assertEqual(len(kernels), 1, kernels)
        self.assertTrue(kernels[0].startswith("triton_tem_fused"), kernels)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_col_reduction_epilogue_transposed_pointwise(self):
        """A pointwise node reading the output transposed doesn't fuse next to
        a column reduction, whose pass transposes the stored tile."""

        def fn(a, b):
            c = a @ b
            return c.t().contiguous(), c.float().sum(0)

        kernels, _ = self._run_reduction(
            fn,
            256,
            128,
            256,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True},
        )
        self.assertGreater(len(kernels), 1, kernels)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize(
        "case", ("disabled", "argmax", "fp64", "dynamic", "subtile", "data_partition")
    )
    def test_blackwell_mm_col_reduction_epilogue_not_fused(self, case: str):
        """The column reduction stays unfused when the flag is off, it is an
        arg reduction, its fp32 partials would lose precision, the shape is
        dynamic, or the config can't host it (EPILOGUE_SUBTILE > 1, data
        partitioning)."""
        fn = {
            "argmax": lambda a, b: (a @ b).float().argmax(0),
            "fp64": lambda a, b: (a @ b).double().sum(0),
        }.get(case, self.COL_OPS["sum"])
        if case == "data_partition" and not _use_template_autows():
            self.skipTest("needs template autoWS")
        test_config = BlackwellGPUGemmConfig(
            128, 128, 64, 3, 8, epilogue_subtile=2 if case == "subtile" else 1
        )
        with torch._dynamo.config.patch(assume_static_by_default=case != "dynamic"):
            kernels, _ = self._run_reduction(
                fn,
                1024,
                128,
                256,
                test_config,
                autows=(2, False) if case == "data_partition" else (1, False),
                **{"triton.template_reduction_epilogue": case != "disabled"},
            )
        self.assertTrue(
            any(k.startswith(("triton_red", "triton_per")) for k in kernels), kernels
        )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_row_and_col_reduction_epilogue(self):
        """Only the column reduction fuses; mixing row and column reductions
        in one epilogue is not supported."""

        def fn(a, b):
            c = (a @ b).float()
            return c.sum(0), c.sum(1)

        kernels, _ = self._run_reduction(
            fn,
            1024,
            128,
            256,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True},
        )
        self.assertEqual(len(kernels), 2, kernels)
        self.assertTrue(kernels[0].startswith("triton_tem_fused"), kernels)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_reduction_epilogue_benchmark_times_finish(self):
        """The benchmark harness of a kernel with column reduction partials also
        runs the wrapper's finish, so epilogue benchmarking pays for it."""
        _, code = self._run_reduction(
            self.COL_OPS["sum"],
            1024,
            128,
            128,
            BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True, "benchmark_kernel": True},
        )
        finish = re.findall(
            r"\.run\(\*args, stream=\w+\)\n\s+args\[\d+\]\[\d+:\d+\]"
            r"\.view\(torch\.float32\)\.view\(\d+, 128\)\.sum\(dim=0\)",
            code,
        )
        self.assertEqual(len(finish), 1, code)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("op", ("row", "col"))
    def test_blackwell_mm_reduction_epilogue_transposed_read(self, op: str):
        """A square output read transposed by a pointwise node must not fuse,
        since epilogue loads take the tile element at the store position."""
        fn = {
            "row": lambda a, b: ((p := (a @ b).t().contiguous()), p.float().sum(1)),
            "col": lambda a, b: ((c := a @ b).t().contiguous(), c.float().sum(0)),
        }[op]
        kernels, _ = self._run_reduction(
            fn,
            256,
            128,
            256,
            BlackwellGPUGemmConfig(128, 256, 64, 3, 8),
            **{"triton.template_reduction_epilogue": True},
        )
        self.assertFalse(
            any(k.startswith("triton_tem") and "clone" in k for k in kernels), kernels
        )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_blackwell_mm_row_reduction_epilogue_skips_misfit_tile(self):
        """The fusion benchmark skips choices whose tile can't host the
        reduction epilogue, even when they rank first, and fuses into one that
        can. Reading a row reduction back doesn't fit subtiled outputs."""
        orig_choice_timings = MultiTemplateBuffer.choice_timings
        orig_tile_fits = simd.tile_fits_reduction_epilogue
        rejected_tiles = []

        def choice_timings(self, hint_override=None):
            # Rank the subtiled choices first.
            timings = orig_choice_timings(self, hint_override)
            subtiled = [c for c in timings if (c.output_tile or (0, 0, 1))[2] > 1]
            return dict.fromkeys([*subtiled, *timings], 1.0)

        def tile_fits(tile, template, epilogue_nodes):
            fits = orig_tile_fits(tile, template, epilogue_nodes)
            if not fits:
                rejected_tiles.append(tile)
            return fits

        with (
            mock.patch.object(MultiTemplateBuffer, "choice_timings", choice_timings),
            mock.patch.object(simd, "tile_fits_reduction_epilogue", tile_fits),
        ):
            kernels, code = self._run_reduction(
                lambda a, b: (c := (a @ b).float()) - c.mean(-1, keepdim=True),
                1024,
                512,
                128,
                BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
                BlackwellGPUGemmConfig(128, 128, 64, 3, 8, epilogue_subtile=2),
                tol=1e-5,
                **{"triton.template_reduction_epilogue": True},
            )
        self._assert_row_fused(kernels, code)
        self.assertTrue(rejected_tiles)
        self.assertTrue(
            all(tile is not None and tile[2] > 1 for tile in rejected_tiles),
            rejected_tiles,
        )

    def _run_stale_pending_fusion(self, compile_mode: str, **patches):
        """Compile a GEMM whose epilogue fusion with a pointwise node is
        benchmarked before that node fuses with a row reduction. The benchmark
        picks a subtiled choice, whose tile can't hold var_mean."""
        if compile_mode == "async" and not AsyncCompile.wait_process_pool_ready():
            self.skipTest("compile worker pool unavailable")
        orig_choice_timings = MultiTemplateBuffer.choice_timings

        def choice_timings(self, hint_override=None):
            timings = orig_choice_timings(self, hint_override)
            subtiled = [c for c in timings if (c.output_tile or (0, 0, 1))[2] > 1]
            return dict.fromkeys([*subtiled, *timings], 1.0)

        with (
            mock.patch.object(MultiTemplateBuffer, "choice_timings", choice_timings),
            mock.patch.object(AsyncCompile, "use_process_pool", return_value=False)
            if compile_mode == "sync"
            else contextlib.nullcontext(),
        ):
            return self._run_reduction(
                lambda a, b: ((c := a @ b) * 2, torch.var_mean(c.float(), -1)),
                1024,
                512,
                128,
                BlackwellGPUGemmConfig(128, 128, 64, 3, 8),
                BlackwellGPUGemmConfig(128, 128, 64, 3, 8, epilogue_subtile=2),
                tol=1e-5,
                **{
                    "triton.template_reduction_epilogue": True,
                    "epilogue_fusion_first": True,
                    **patches,
                },
            )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("compile_mode", ("sync", "async"))
    def test_blackwell_mm_reduction_epilogue_stale_pending_fusion(
        self, compile_mode: str
    ):
        """A pending epilogue fusion whose pointwise node has since fused with a
        row reduction isn't applied, and the next fusion round benchmarks the
        template with both."""
        kernels, code = self._run_stale_pending_fusion(compile_mode)
        self._assert_row_fused(kernels, code)

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    @parametrize("compile_mode", ("sync", "async"))
    def test_blackwell_mm_reduction_epilogue_stale_pending_fusion_memory_guard(
        self, compile_mode: str
    ):
        """The peak-memory fusion guard still rejects the template fusion that
        the next round proposes after a stale pending fusion is skipped."""
        orig_check = Scheduler._can_fuse_peak_memory_check
        orig_is_stale = Scheduler._is_stale_pending_fusion
        stale, rejected = [], []

        def check(self, state, node1, node2):
            # Treat template fusions with the fused pointwise and reduction
            # nodes as exceeding the allowed peak increase.
            nodes = node2.get_nodes()
            if node1.is_template() and len(nodes) > 1:
                if any(n.is_reduction() for n in nodes):
                    rejected.append(node2)
                    return False, None
            return orig_check(self, state, node1, node2)

        def is_stale(self, pending_fusion):
            stale.append(orig_is_stale(self, pending_fusion))
            return stale[-1]

        with (
            mock.patch.object(Scheduler, "_can_fuse_peak_memory_check", check),
            mock.patch.object(Scheduler, "_is_stale_pending_fusion", is_stale),
        ):
            kernels, _ = self._run_stale_pending_fusion(
                compile_mode, fusion_memory_timeline_peak_memory_increase_gb=1000.0
            )
        self.assertIn(True, stale)
        self.assertTrue(rejected)
        self.assertTrue(any(k.startswith("triton_tem") for k in kernels), kernels)
        self.assertTrue(
            any(k.startswith(("triton_per", "triton_red")) for k in kernels), kernels
        )

    def _assert_template_row_sum_fused(
        self, fn, args, template, op_name, test_config, expected
    ):
        """Compile fn with test_config, and a twin so epilogues are benchmarked,
        as the only choices of template. Fused epilogue benchmarks report 0 ms."""
        heuristic = get_template_heuristic(template.uid, GPU_TYPE, op_name)
        twin = dataclasses.replace(test_config, num_stages=test_config.num_stages - 1)
        with (
            config.patch(
                {
                    "max_autotune": True,
                    "max_autotune_gemm_backends": "TRITON",
                    "triton.enable_persistent_tma_matmul": True,
                    "test_configs.autotune_choice_name_regex": template.name,
                    "benchmark_template_fusion": True,
                    "triton.template_reduction_epilogue": True,
                }
            ),
            mock.patch.object(heuristic, "mm_configs", [test_config, twin]),
            mock.patch.object(
                Scheduler, "benchmark_codegened_module", return_value=(0.0, "")
            ),
            self._poison_outputs(),
        ):
            actual, code = run_and_get_code(torch.compile(fn), *args)
        self.assertEqual(actual, expected, atol=0, rtol=0)
        kernels = re.findall(r"def (triton_\w+)\(", code[0])
        # A scale layout fixup may run as a separate pointwise kernel.
        self.assertFalse(
            any(k.startswith(("triton_per", "triton_red")) for k in kernels), kernels
        )
        self.assertTrue(
            any(k.startswith("triton_tem_fused") and "sum" in k for k in kernels),
            kernels,
        )

    @unittest.skipIf(not has_triton_tma_device(), "Need device-side TMA support")
    def test_persistent_tma_mm_row_reduction_epilogue_fusion(self):
        a = torch.randint(-1, 2, (1024, 512), device=GPU_TYPE).to(torch.bfloat16)
        b = torch.randint(-1, 2, (512, 128), device=GPU_TYPE).to(torch.bfloat16)
        fn = self.ROW_OPS["sum"]
        # On datacenter Blackwell the Blackwell template replaces this one.
        with mock.patch.object(
            torch._inductor.kernel.mm,
            "use_triton_blackwell_tma_template",
            return_value=False,
        ):
            self._assert_template_row_sum_fused(
                fn,
                (a, b),
                persistent_tma_mm_template,
                "mm",
                GemmConfig(128, 128, 64, 3, 8),
                fn(a, b),
            )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_scaled_mm_epilogue_scaling_row_reduction_epilogue_fusion(self):
        M, K, N = 1024, 512, 128
        a = torch.randint(-1, 2, (M, K), device=GPU_TYPE).to(torch.float8_e4m3fn)
        b = torch.randint(-1, 2, (N, K), device=GPU_TYPE).to(torch.float8_e4m3fn).t()
        # Power-of-two scales keep the GEMM exact, so it matches eager bitwise.
        scale_a = 2.0 ** torch.randint(0, 2, (M, 1), device=GPU_TYPE)
        scale_b = 2.0 ** torch.randint(0, 2, (1, N), device=GPU_TYPE)

        def fn(a, b, scale_a, scale_b):
            c = torch._scaled_mm(a, b, scale_a, scale_b, out_dtype=torch.bfloat16)
            return c.float().sum(-1)

        args = (a, b, scale_a, scale_b)
        self._assert_template_row_sum_fused(
            fn,
            args,
            scaled_mm_device_tma_epilogue_scaling_template,
            "scaled_mm",
            GemmConfig(128, 128, 128, 3, 8),
            fn(*args),
        )

    @unittest.skipIf(
        not has_datacenter_blackwell_tma_device(),
        "Need Blackwell with device-side TMA support in Triton",
    )
    def test_scaled_mm_main_loop_scaling_row_reduction_epilogue_fusion(self):
        M, K, N = 1024, 256, 128
        a = torch.randint(-1, 2, (M, K), device=GPU_TYPE).to(torch.float8_e4m3fn)
        b = torch.randint(-1, 2, (N, K), device=GPU_TYPE).to(torch.float8_e4m3fn)
        # 1x128 scales for a (stored outer-dim-major) and 128x128 scales for b.
        scale_a = 2.0 ** torch.randint(0, 2, (K // 128, M), device=GPU_TYPE).t()
        scale_b = 2.0 ** torch.randint(0, 2, (N // 128, K // 128), device=GPU_TYPE)

        def fn(a, b, scale_a, scale_b):
            c = scaled_mm(
                a,
                b,
                scale_a,
                ScalingType.BlockWise1x128,
                scale_b,
                ScalingType.BlockWise128x128,
                output_dtype=torch.bfloat16,
            )
            return c.float().sum(-1)

        # Eager blockwise scaling needs SM90 cuBLAS, so compare against an exact
        # reference: integer inputs and power-of-two scales make the GEMM exact
        # in fp64 and fp32, and its bf16 rounding and row sums then match.
        scale_a_full = scale_a.double().repeat_interleave(128, 1)
        scale_b_full = scale_b.double().repeat_interleave(128, 0)
        scale_b_full = scale_b_full.repeat_interleave(128, 1)
        c = (a.double() * scale_a_full) @ (b.double() * scale_b_full).t()
        self._assert_template_row_sum_fused(
            fn,
            (a, b.t(), scale_a, scale_b),
            scaled_mm_device_tma_main_loop_scaling_template,
            "scaled_mm",
            GemmConfig(128, 128, 128, 3, 8),
            c.bfloat16().float().sum(-1),
        )


@instantiate_parametrized_tests
class TestBlackwellExhaustiveConfigs(TestCase):
    """Tests for exhaustive config generation for Blackwell templates."""

    # Expected valid values for each parameter based on _generate_exhaustive_configs
    VALID_BLOCK_SIZES = {32, 64, 128, 256}
    VALID_GROUP_M = {8}
    VALID_NUM_STAGES = {2, 3, 4, 5, 6}
    VALID_NUM_WARPS = {4, 8}
    VALID_EPILOGUE_SUBTILE = {1, 2, 4}

    @parametrize(
        "heuristic_cls",
        (
            CUDABlackwellPersistentTMATemplateConfigHeuristic,
            CUDABlackwellAddmmPersistentTMATemplateConfigHeuristic,
        ),
    )
    def test_exhaustive_configs_parameter_variety(self, heuristic_cls):
        """Test that exhaustive configs have variety in all expected parameters."""
        heuristic = heuristic_cls()
        configs = heuristic.exhaustive_configs

        # Ensure we have at least 128 configs
        self.assertGreaterEqual(len(configs), 128)

        # Collect all unique values for each parameter
        block_m_values = set()
        block_n_values = set()
        block_k_values = set()
        group_m_values = set()
        num_stages_values = set()
        num_warps_values = set()
        epilogue_subtile_values = set()

        for cfg in configs:
            self.assertIsInstance(cfg, BlackwellGPUGemmConfig)
            block_m_values.add(cfg.block_m)
            block_n_values.add(cfg.block_n)
            block_k_values.add(cfg.block_k)
            group_m_values.add(cfg.group_m)
            num_stages_values.add(cfg.num_stages)
            num_warps_values.add(cfg.num_warps)
            epilogue_subtile_values.add(cfg.epilogue_subtile)

        # Verify multiple values exist for each parameter via set membership
        self.assertEqual(block_m_values, self.VALID_BLOCK_SIZES)
        self.assertEqual(block_n_values, self.VALID_BLOCK_SIZES)
        self.assertEqual(block_k_values, self.VALID_BLOCK_SIZES)
        self.assertEqual(group_m_values, self.VALID_GROUP_M)
        self.assertEqual(num_stages_values, self.VALID_NUM_STAGES)
        self.assertEqual(num_warps_values, self.VALID_NUM_WARPS)
        self.assertEqual(epilogue_subtile_values, self.VALID_EPILOGUE_SUBTILE)

    def test_scaled_blackwell_tma_uses_scaled_persistent_configs(self):
        """Verify scaled Blackwell TMA heuristic uses blackwell_scaled_persistent_mm_configs."""
        heuristic = CUDAScaledBlackwellTMATemplateConfigHeuristic()

        for cfg in heuristic.mm_configs:
            self.assertIsInstance(cfg, BlackwellGPUGemmConfig)

        expected_configs = heuristic.blackwell_scaled_persistent_mm_configs
        self.assertEqual(len(heuristic.mm_configs), len(expected_configs))
        for actual, expected in zip(heuristic.mm_configs, expected_configs):
            self.assertEqual(actual.block_m, expected.block_m)
            self.assertEqual(actual.block_n, expected.block_n)
            self.assertEqual(actual.block_k, expected.block_k)
            self.assertEqual(actual.num_stages, expected.num_stages)
            self.assertEqual(actual.num_warps, expected.num_warps)

        addmm_configs = heuristic.blackwell_persistent_addmm_configs
        self.assertGreater(
            len(heuristic.mm_configs),
            len(addmm_configs),
            "Scaled TMA should use the larger scaled_persistent list, not the small addmm list",
        )


class TestBlackwellAutoWSConstraints(TestCase):
    def test_two_ctas_allows_all_pipeline_depths(self):
        kwargs = {
            "BLOCK_M": 128,
            "BLOCK_N": 128,
            "EPILOGUE_SUBTILE": 2,
            "DATA_PARTITION_FACTOR": 1,
            "TWO_CTAS": True,
            "USE_META_WS": True,
        }
        with (
            config.patch({"triton.enable_template_tma_store": True}),
            unittest.mock.patch(
                "torch._inductor.heuristics.template.triton.has_two_ctas",
                return_value=True,
            ),
        ):
            for num_stages in range(2, 7):
                kwargs["num_stages"] = num_stages
                self.assertTrue(
                    CUDABlackwellPersistentTMATemplateConfigHeuristic._autows_constraints_ok(
                        kwargs, element_size=2
                    )
                )

    def test_two_ctas_swizzle_is_dtype_aware(self):
        kwargs = {
            "BLOCK_M": 128,
            "BLOCK_N": 64,
            "EPILOGUE_SUBTILE": 1,
            "DATA_PARTITION_FACTOR": 1,
            "TWO_CTAS": True,
            "USE_META_WS": True,
        }
        with (
            config.patch({"triton.enable_template_tma_store": True}),
            unittest.mock.patch(
                "torch._inductor.heuristics.template.triton.has_two_ctas",
                return_value=True,
            ),
        ):
            self.assertFalse(
                CUDABlackwellPersistentTMATemplateConfigHeuristic._autows_constraints_ok(
                    kwargs, element_size=2
                )
            )
            self.assertTrue(
                CUDABlackwellPersistentTMATemplateConfigHeuristic._autows_constraints_ok(
                    kwargs, element_size=4
                )
            )

            kwargs["BLOCK_N"] = 32
            self.assertFalse(
                CUDABlackwellPersistentTMATemplateConfigHeuristic._autows_constraints_ok(
                    kwargs, element_size=4
                )
            )

    def test_two_ctas_requires_tma_store_for_metaws_template(self):
        kwargs = {
            "BLOCK_M": 128,
            "BLOCK_N": 128,
            "EPILOGUE_SUBTILE": 1,
            "DATA_PARTITION_FACTOR": 1,
            "TWO_CTAS": True,
            "USE_META_WS": True,
        }
        with (
            config.patch({"triton.enable_template_tma_store": False}),
            unittest.mock.patch(
                "torch._inductor.heuristics.template.triton.has_two_ctas",
                return_value=True,
            ),
        ):
            self.assertFalse(
                CUDABlackwellPersistentTMATemplateConfigHeuristic._autows_constraints_ok(
                    kwargs, element_size=2
                )
            )

    def test_two_ctas_odd_num_sms_covers_every_tile(self):
        with (
            unittest.mock.patch("torch.xpu.is_available", return_value=False),
            unittest.mock.patch(
                "torch._inductor.utils.get_max_num_sms", return_value=149
            ),
            unittest.mock.patch.object(
                torch._C, "_get_sm_carveout_experimental", return_value=None
            ),
        ):
            self.assertEqual(get_num_sms(), 149)
            num_sms = get_num_sms(two_ctas=True)
        self.assertEqual(num_sms, 148)

        block_m, block_n = 128, 128
        m, n = 17 * block_m, 20 * block_n
        meta = {
            "BLOCK_M": block_m,
            "BLOCK_N": block_n,
            "NUM_SMS": num_sms,
            "TWO_CTAS": True,
        }
        grid_size = blackwell_persistent_mm_grid(m, n, meta)[0]
        grid_m = ((m + block_m - 1) // block_m + 1) // 2 * 2
        num_tiles = grid_m * ((n + block_n - 1) // block_n)
        visited = {
            tile for pid in range(grid_size) for tile in range(pid, num_tiles, num_sms)
        }
        self.assertEqual(visited, set(range(num_tiles)))


@unittest.skipIf(torch.version.hip is not None, "CUDA-specific template heuristics")
@instantiate_parametrized_tests
class TestBlackwellAutoWSConfigs(TestCase):
    """autoWS config selection for the Blackwell persistent-TMA template."""

    @parametrize(
        "op_name,heuristic_cls",
        (
            ("mm", CUDABlackwellPersistentTMATemplateConfigHeuristic),
            ("addmm", CUDABlackwellAddmmPersistentTMATemplateConfigHeuristic),
            ("scaled_mm", CUDAScaledBlackwellTMATemplateConfigHeuristic),
        ),
    )
    @parametrize("search_space", ("DEFAULT", "EXHAUSTIVE"))
    @parametrize("initial_autows", (False, True))
    def test_autows_configs_follow_current_mode(
        self, op_name, heuristic_cls, search_space, initial_autows
    ):
        with (
            mock.patch.dict(_HEURISTIC_CACHE, clear=True),
            mock.patch.dict(BaseHeuristicSingleton._instances, clear=True),
            mock.patch("torch._inductor.heuristics.template.triton.USE_META_WS", True),
        ):
            first_heuristic = None
            for enabled in (initial_autows, not initial_autows, initial_autows):
                with config.patch(
                    {
                        "triton.enable_template_autows": enabled,
                        "max_autotune_gemm_search_space": search_space,
                    }
                ):
                    heuristic = heuristic_cls()
                    if first_heuristic is None:
                        first_heuristic = heuristic
                    self.assertIs(heuristic, first_heuristic)
                    self.assertIs(
                        get_template_heuristic(
                            blackwell_ws_persistent_tma_mm_template.uid,
                            "cuda",
                            op_name,
                        ),
                        heuristic,
                    )
                    configs = heuristic._get_config_generator().keywords["configs"]
                    self.assertEqual(
                        {getattr(cfg, "use_meta_ws", False) for cfg in configs},
                        {enabled},
                    )
                    if enabled:
                        expected = (
                            heuristic._generate_autows_exhaustive_configs()
                            if search_space == "EXHAUSTIVE"
                            else heuristic._generate_autows_configs()
                        )
                        self.assertEqual(configs, expected)
                    else:
                        self.assertIs(
                            configs,
                            heuristic.exhaustive_configs
                            if search_space == "EXHAUSTIVE"
                            else heuristic.mm_configs,
                        )
                        if op_name == "addmm":
                            self.assertEqual(
                                heuristic.mm_configs,
                                heuristic.blackwell_persistent_mm_configs
                                + heuristic.blackwell_persistent_addmm_configs,
                            )

    @parametrize("global_meta_ws", (False, True))
    def test_global_meta_ws_disables_flatten(self, global_meta_ws):
        # Triton's Meta WS knob rewrites every WS kernel, so configs with
        # use_meta_ws=False must not be flattened either.
        mat1, mat2 = mock.Mock(), mock.Mock()
        mat2.get_dtype.return_value = torch.bfloat16
        kernel_inputs = MMKernelInputs([mat1, mat2], mat1_idx=0, mat2_idx=1)
        base = {
            "BLOCK_M": 128,
            "BLOCK_N": 128,
            "BLOCK_K": 64,
            "num_stages": 3,
            "num_warps": 4,
            "WARP_SPECIALIZE": True,
            "FLATTEN": True,
            "USE_META_WS": False,
        }
        with (
            mock.patch.dict(BaseHeuristicSingleton._instances, clear=True),
            mock.patch(
                "torch._inductor.heuristics.template.triton.USE_META_WS",
                global_meta_ws,
            ),
            mock.patch.object(
                TMATemplateConfigMixin,
                "_get_template_configs_impl",
                return_value=iter([base]),
            ),
        ):
            heuristic = CUDABlackwellPersistentTMATemplateConfigHeuristic()
            configs = list(heuristic._get_template_configs_impl(kernel_inputs, "mm"))
        self.assertEqual(len(configs), 1)
        self.assertTrue(configs[0]["WARP_SPECIALIZE"])
        self.assertEqual(configs[0]["FLATTEN"], not global_meta_ws)

    def test_autows_default_configs_are_subset_of_exhaustive(self):
        with mock.patch.dict(BaseHeuristicSingleton._instances, clear=True):
            heuristic = CUDABlackwellPersistentTMATemplateConfigHeuristic()
            configs = heuristic._generate_autows_configs()
            exhaustive_configs = heuristic._generate_autows_exhaustive_configs()
            for cfg in configs:
                self.assertIsInstance(cfg, BlackwellGPUGemmConfig)
                self.assertTrue(cfg.use_meta_ws)
                self.assertIn(cfg, exhaustive_configs)
            expected_stages = [
                cfg.num_stages for cfg in heuristic.blackwell_persistent_mm_configs
            ]
            two_cta_stages = [
                cfg.num_stages
                for cfg in configs
                if cfg.two_ctas and cfg.data_partition_factor == 1
            ]
            self.assertEqual(two_cta_stages, expected_stages)


if __name__ == "__main__":
    from torch._inductor.utils import is_big_gpu

    # Set env to make it work in CI.
    if HAS_GPU and HAS_CPU and is_big_gpu():
        run_tests()
