/* Auto-generated by generate-wrappers.py script. Do not modify */

#if defined(__i386__) || defined(__i686__) || defined(__x86_64__)
#include <q8dwconv/up8x9-sse2-per-channel.c>
#endif /* defined(__i386__) || defined(__i686__) || defined(__x86_64__) */
