"""Generate the native-AOT kernel library source from declarations + sidecars.

Each op's aot.py (contract: tools/native_aot/decl.py) states the C++
side as string-returning functions: cpp_dispatch_prelude() (optional
shared checks + setup), cpp_dispatch(spec) (one boolean per precompile
point), cpp_launch(spec, launch_fn) (the invocation), cpp_helpers()
(optional family-shared C++). The Python-side coverage check
(covered_axes, consumed by torch._native.aot_manifest) lives in the
same module -- the two sides are kept in sync by hand.

Kernels are exported to ``<artifacts-dir>/<arch>/<op>/`` -- one tree per
arch, whatever the arch count. For each op found there this emits
``<artifacts-dir>/<op>/aot_<op>_<key>.cpp``, one file covering every arch
the op shipped for, containing:

  * a launch_<prefix>() marshalling helper per exported kernel,
    emitted by the sidecar kind's Toolchain (see toolchains.py); every
    toolchain produces the same launcher signature, so cpp_launch and
    the guard chain are toolchain-blind
  * the stub kernel: an early-out over the shipped compute capabilities,
    then helpers | prelude, then one cond chain PER CAPABILITY -- inside
    each, an `if (cpp_dispatch(spec)) { cpp_launch; return true; }`
    branch per exported precompile point, and `return false` at the end
    (the fallback). A device runs only kernels built for exactly its
    capability; anything else declines to op.impl.
  * registration on the generated at::native DispatchStub
    (<op>_aot_stub) via set_<device>_dispatch_ptr at static-init time

The kernel signature is the op's structured impl signature: outputs are
allocated by the wrapper's meta() before the stub runs, so bodies write
into them and return true, or return false to fall through to op.impl.

Requires torchgen (impl signature) but not a built torch.

Usage:
    python tools/native_aot/gen_aot_lib.py [--artifacts-dir build/native_aot]
"""

from __future__ import annotations

import argparse
import os
import re
import sys


REPO = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
)
# append, never insert(0): the repo root holds a torch/ SOURCE tree with no
# compiled extension, and ahead of site-packages it shadows the real torch so
# any `import torch` dies with "loaded the torch/_C folder of the PyTorch
# repository". Invisible in a `pip install -e .` checkout, where that tree IS
# the installed torch -- which is how it reached CI (see export.py's copy of
# this note, and the b200 build it broke).
sys.path.append(REPO)

from torchgen import native_aot_decl as decl


OPS_DIR = os.path.join(REPO, "torch", "_native", "ops")

FILE_TMPL = """\
// @generated by tools/native_aot/gen_aot_lib.py from
// {decl_path} -- do not edit
//
// {precompute_note}
// core/Tensor.h, not ATen/ATen.h: the latter pulls Functions.h +
// NativeFunctions.h, i.e. ~1300 ATen/ops/*.h each, so every generated file
// depended on unrelated ops (conv2d, lstm, fft) and any schema edit rebuilt
// all of them -- exactly what AT_PER_OPERATOR_HEADERS exists to avoid.
// TensorIterator.h and ops/empty.h are unconditional: declaration preludes
// commonly need one or both (shape analysis, the reduction family's
// accumulator), and there is no per-declaration include hook yet. A body that
// calls some other at:: FACTORY needs its op header added here.
//
// torch/library.h is the exception, emitted only for ops with cpp_covers,
// because it is in a different weight class: the covers registration at the end
// of this file is its only consumer and it pulls the whole dispatcher in with
// it (~110 transitive headers, measured).
#include <ATen/core/Tensor.h>
#include <ATen/NativeAotStubs.h>
#include <ATen/TensorIterator.h>
#include <ATen/cuda/CUDAContext.h>
#include <ATen/ops/empty.h>
#include <c10/cuda/CUDAStream.h>
{covers_include}#include <algorithm>
#include <limits>

{kernel_includes}

namespace {{
{size_gate_helper}
{launchers}
bool {op}_{key_lc}_aot_kernel({params}) {{
{cond}
{guards}
  return false;
}}
{covers_fn}
}} // namespace

// Register on the generated DispatchStub (same mechanism as aten's own
// runtime-registered CUDA kernels; see ATen/native/DispatchStub.h).
namespace at::native {{
REGISTER_{key_uc}_DISPATCH({op}_aot_stub, &::{op}_{key_lc}_aot_kernel)
}} // namespace at::native
{covers_reg}"""

# Emitted only into files whose kind narrows shapes (see
# Toolchain.NARROWS_SHAPES_TO_INT32); an unused inline function would
# otherwise sit in every generated file's anonymous namespace.
SIZE_GATE_HELPER = """
// This kind's exported ABI carries int32_t shape slots while aten sizes are
// int64_t; the generated gates decline rather than truncate. See
// _int32_size_gate in tools/native_aot/gen_aot_lib.py.
inline bool _naot_dim_too_big(int64_t d) {
  return d > std::numeric_limits<int32_t>::max();
}
"""


# Fast coverage predicate: the declaration's cpp_covers() body over the
# op's FUNCTIONAL schema arguments (plus a trailing optional `out` so
# the .out variant's kwarg binds). Registered as a catch-all custom op;
# torch._native.aot_manifest prefers it over the Python covered_axes
# matching when the library is loaded.
COVERS_FN_TMPL = """
bool {op}_{key_lc}_covers({params}) {{
{body}
}}
"""

COVERS_REG_TMPL = """
TORCH_LIBRARY_FRAGMENT(_native_aot, m) {{
  m.def("{schema}", &::{op}_{key_lc}_covers);
}}
"""


from tools.native_aot import toolchains


def indent(code: str, pad: str) -> str:
    return "\n".join(pad + l if l.strip() else l for l in code.rstrip().splitlines())


def gen_launcher(sidecar: dict) -> str:
    return toolchains.get_toolchain(sidecar["kind"]).gen_launcher(sidecar)


_CURRENT_PROPS = "at::cuda::getCurrentDeviceProperties()"

# Name of the local the generated gates read device properties through. Its
# own prefix, because declaration-supplied bodies share the scope.
_PROPS_LOCAL = "_naot_props"


def _split_params(params: str) -> list[str]:
    """A C++ parameter list split at its TOP-LEVEL commas.

    `params.split(",")` cuts inside template argument lists too, and a
    signature can carry one that holds a comma (`std::array<bool, 3>` for an
    output mask, `std::pair<at::Tensor, at::Tensor>`). It hands the callers
    below fragments -- "std::pair<at::Tensor" and "at::Tensor> pr" -- and
    _int32_size_gate's refusal of unknown tensor-shaped types then judges a
    fragment, naming a type that appears nowhere in the signature it was
    given. Splitting at depth 0 is what lets those callers see whole types."""
    out: list[str] = []
    depth = 0
    cur = ""
    for ch in params:
        if ch in "<([{":
            depth += 1
        elif ch in ">)]}":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    out.append(cur)
    return [p.strip() for p in out if p.strip()]


def _param_type_and_name(param: str) -> tuple[str, str]:
    """One declaration -> (type without const/ref, parameter name)."""
    name = param.split()[-1].lstrip("&*")
    ctype = param[: -len(name)].strip().removeprefix("const ").rstrip("& ")
    return ctype, name


def _first_tensor_name(params: str) -> str | None:
    """Name of the first plain at::Tensor parameter, or None."""
    for p in _split_params(params):
        ctype, name = _param_type_and_name(p)
        if ctype == "at::Tensor":
            return name
    return None


def _device_match(major: int, minor: int, props: str = _CURRENT_PROPS) -> str:
    """The device predicate for one compute capability.

    ``props`` is the properties expression to read. The stub runs inside the
    wrapper's device guard, so the CURRENT device is the right one there; a
    covers predicate does not -- it is called by the router before any guard --
    so it must ask about the tensor's device instead, which is also what the
    declarations' own covers bodies do."""
    return f"{props}->major == {major} && {props}->minor == {minor}"


# One implementation, shared with the exporter: see decl.cc_of, which also holds
# the bound on plausible capabilities so a malformed arch cannot produce a gate
# that is silently false on every device.
_cc_of = decl.cc_of


def _spec_from_json(spec):
    """A recorded spec as the DECLARATION stated it: sequences back to tuples.

    The grid distinguishes the two -- expand_specs treats a list as an axis and a
    tuple as one compound value -- but JSON has only arrays, so a tuple-valued
    grid field reached cpp_dispatch as a list. `spec["dtypes"] == ("f32", "bf16")`
    was then silently False (emitting a cond that never fires, so the kernel
    shipped and every call declined) and `_CTYPE[spec["dtypes"]]` raised
    "unhashable type: 'list'" inside generation. The restore is exact rather than
    a guess: expand_specs consumed every list as an axis, so a sequence still in a
    recorded point can only have come from a tuple."""
    if isinstance(spec, list):
        return tuple(_spec_from_json(v) for v in spec)
    if isinstance(spec, dict):
        return {k: _spec_from_json(v) for k, v in spec.items()}
    return spec


def _by_arch(sidecars: list[dict]) -> dict[tuple[int, int], list[dict]]:
    """Group sidecars by the compute capability they were compiled for, in
    ascending cc order, dropping candidates that lose the arch-conditional
    tie-break.

    Several arches can ship in one library (a multi-arch export nests one
    tree per arch), and each device must run kernels built for exactly its
    cc -- hence the grouping rather than one gate over the union, which
    would accept a device nothing was compiled for.

    Within one cc, an arch-conditional build ("sm_100a") and a plain one
    ("sm_100") are both valid on the hardware. Prefer the conditional: it is
    the one the kernels were written against (TMA, clusters), and shipping
    both otherwise leaves the choice to directory order.

    A sidecar with no recorded arch is rejected: export names the arch of
    everything it writes, so this is a tree from before it did, and there is
    no hardware such an artifact can be matched to. Erroring beats emitting a
    branch that never matches and declines every call in silence."""
    groups: dict[tuple[int, int], list[dict]] = {}
    conditional: dict[tuple[int, int], bool] = {}
    for sc in sidecars:
        arch = sc.get("arch")
        if not isinstance(arch, str):
            raise RuntimeError(
                f"{sc.get('prefix', '<unnamed>')} in {sc.get('_dir', '?')} "
                f"records no arch. Re-export: the runtime gate is built from "
                f"the arch each artifact was compiled for."
            )
        cc = _cc_of(arch)
        is_cond = arch.endswith("a")
        if cc in groups and conditional.get(cc, False) != is_cond:
            # A conditional build for this cc wins outright; a plain one loses.
            if not is_cond:
                continue
            groups[cc] = []
        groups.setdefault(cc, []).append(sc)
        conditional[cc] = conditional.get(cc, False) or is_cond
    return {cc: groups[cc] for cc in sorted(groups)}


# Tensor-shaped C++ types the gate must recognize or refuse. torchgen renders
# Tensor? as at::OptionalTensorRef and Tensor[] as at::ITensorListRef in
# structured impl signatures (api/structured.py), and index.Tensor's covers
# signature carries c10::List<::std::optional<at::Tensor>> -- none of which
# the two accessors below fit.
_TENSOR_ISH = re.compile(r"\bat::\w*Tensor\w*|\bc10::List<")

# A sidecar prefix must be usable as a C identifier: it is pasted into
# extern "C" declarations, launcher names and version-script patterns.
# Spelled out rather than \w, which is Unicode by default: "héllo" would satisfy
# a check whose entire contract is "usable as a C identifier".
_C_IDENT = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")


def _int32_size_gate(params: str) -> str:
    """Runtime gate: decline any call whose tensor has a dimension that
    does not fit in int32.

    aten stores sizes as int64_t (TensorBase.h: `int64_t size(int64_t)`),
    but our fake tensors declare shape symbols with cute.sym_int(), which
    is 32-bit, so export_to_c emits `int32_t dynamic_shapes[]` and the
    kernel's C ABI takes i32 extents. Without this gate the launcher's
    `static_cast<int32_t>(t.size(dim))` would silently truncate a >=2^31
    dim and hand the kernel a wrong (possibly negative) extent: wrong
    results or corrupted memory, with no error. Declining instead routes
    the call to the JIT layer or to stock aten.

    Emitted ahead of the declaration's prelude AND into cpp_covers (like
    _arch_gate) so no declaration has to hand-write it, and so coverage
    never claims a shape the stub will refuse.

    Widening is NOT just switching to cute.sym_int64(), and that switch is
    actively unsafe on its own: as of cutlass-dsl 4.5.2 the ABI honors the
    symbol width (the ciface takes `struct<(i64, i64)>`) but the emitted
    header still declares `int32_t dynamic_shapes[]` -- hardcoded in
    c_header_generator.py, while the stride width beside it is derived
    from the arg. Header and ABI then disagree on slot width, so every
    field after the first shape is read at the wrong offset. Two more
    ceilings sit behind that one: `t.shape[i]` is Int32 whatever the
    symbol ("CuTe IR only supports Int32 for now", cute/core.py) so
    kernels must read extents via cute.size(), and on the JIT path
    build_memref_desc raises OverflowError outright for a dynamic-marked
    dim >=2^31.

    TODO(native-aot): to serve >=2^31 dims, fix the header width upstream
    (NVIDIA's own 4.6+ docs direct users to sym_int64 for shape dims, so
    the int32 default is a bug), port kernels off .shape[] to cute.size(),
    and keep this gate for the JIT route, which has its own hard limit.
    """
    # Parameter list -> the at::Tensor names in scope. The prelude sees
    # plain `const at::Tensor & x`; cpp_covers sees the functional schema
    # plus out-variant outputs as `const std::optional<at::Tensor>& x`.
    plain: list[str] = []
    optional: list[str] = []
    for p in _split_params(params):
        ctype, name = _param_type_and_name(p)
        if ctype in ("std::optional<at::Tensor>", "::std::optional<at::Tensor>"):
            optional.append(name)
        elif ctype == "at::Tensor":
            plain.append(name)
        elif _TENSOR_ISH.search(ctype):
            # Anything else tensor-shaped would need its own accessor
            # (at::OptionalTensorRef has no has_value(); at::ITensorListRef
            # and c10::List<optional<Tensor>> are sequences), so a substring
            # guess emits either an ungated dim or uncompilable C++. Refuse
            # instead: the next op to use one gets this message, not a
            # silent truncation.
            raise RuntimeError(
                f"_int32_size_gate: unhandled tensor-like parameter type "
                f"{ctype!r} (arg {name!r}). Teach the gate this type -- gating "
                f"it wrongly would let a >=2^31 dim through the launcher's "
                f"static_cast<int32_t>, or emit C++ that does not compile."
            )
    if not plain and not optional:
        return ""
    checks = [
        f"{n}.sizes().end() != std::find_if({n}.sizes().begin(), {n}.sizes().end(), _naot_dim_too_big)"
        for n in plain
    ]
    checks += [
        f"({n}.has_value() && {n}->sizes().end() != "
        f"std::find_if({n}->sizes().begin(), {n}->sizes().end(), _naot_dim_too_big))"
        for n in optional
    ]
    return (
        "  // Size gate: the DSL's exported ABI carries int32_t shape slots\n"
        "  // (see _int32_size_gate); a bigger dim would truncate silently.\n"
        f"  if (C10_UNLIKELY({' || '.join(checks)})) return false;\n"
    )


def gen_op(
    op: str,
    key: str,
    d,
    sidecars: list[dict],
    impl_params: str,
    covers: tuple[str, str, str] | None = None,
    precomputed: list[str] | None = None,
    decl_path: str = "",
) -> str:
    def _branch(s: dict, pad: str) -> str:
        spec = _spec_from_json(s["spec"])
        dispatch = d.cpp_dispatch(spec).strip()
        launch = d.cpp_launch(spec, f"launch_{s['prefix']}")
        return (
            f"{pad}if ({dispatch}) {{\n{indent(launch, pad + '  ')}\n"
            f"{pad}  return true;\n{pad}}}"
        )

    # One cond chain per compute capability. A multi-arch export ships a tree
    # per arch, and a kernel built for one cc must never be launched on
    # another -- the module load would fail (unchecked, so it surfaces as the
    # wrapper's rc) instead of declining. Selecting first, then running that
    # cc's chain, is what keeps each artifact on its own hardware.
    groups = _by_arch(sidecars)
    # Everything below emits from the sidecars that SURVIVED the tie-break, not
    # from the full list: a launcher for a dropped candidate would be defined
    # and never called, which is -Wunused-function in an anonymous namespace and
    # fatal under CI's WERROR. Reachable from a plain arch list, since both
    # spellings of a capability are exportable ("10.0;10.0a").
    sidecars = [sc for scs in groups.values() for sc in scs]
    # Shipping an arch the declaration disowns is a packaging bug: error rather
    # than gate on kernels the op does not claim to support.
    shipped = {sc["arch"] for sc in sidecars}
    if unclaimed := shipped - set(decl.archs_of(d)):
        # Name the directories and say DELETE. "Re-export" cannot fix this:
        # _collect_jobs skips (declaration x arch) pairs outside ARCHS, so export
        # never visits these trees, never prunes them, and every later
        # generation -- hence every build -- fails identically. The usual cause is
        # an author narrowing ARCHS after having exported.
        # .get: gen_op is also called directly (tests, and any future caller) with
        # sidecars that carry no generation-time _dir.
        trees = sorted(
            {sc.get("_dir", "?") for sc in sidecars if sc["arch"] in unclaimed}
        )
        raise RuntimeError(
            f"{op}: artifacts exported for {sorted(unclaimed)} but the "
            f"declaration supports only {decl.archs_of(d)}. Delete "
            f"{', '.join(trees) or 'those arch trees'} -- export.py skips "
            f"unsupported arches, so it will not remove them -- then re-export. "
            f"A bare re-export alone will NOT clear this: only deleting the tree "
            f"does. (This is a backstop. Export resolves an on-device arch to the "
            f"spelling the declaration claims for that capability, so reaching it "
            f"means the tree predates that resolution or was narrowed since.)"
        )

    def _gate_for(props: str) -> str:
        accept = " || ".join(
            f"({_device_match(*cc, props=_PROPS_LOCAL)})" for cc in groups
        )
        return (
            f"  // Device gate: one branch per shipped capability "
            f"({', '.join(f'{maj}.{min_}' for maj, min_ in groups)})\n"
            f"  // Read once into a local: this gate and every per-capability\n"
            f"  // branch below ask the same question, and the accessor is a\n"
            f"  // call per read.\n"
            f"  const auto* {_PROPS_LOCAL} = {props};\n"
            f"  if (!({accept})) return false;\n"
        )

    arch_gate = _gate_for(_CURRENT_PROPS)
    branches = [
        f"  if ({_device_match(*cc, props=_PROPS_LOCAL)}) {{\n"
        + "\n".join(_branch(s, "    ") for s in scs)
        + "\n  }"
        for cc, scs in groups.items()
    ]
    prelude_fn = getattr(d, "cpp_dispatch_prelude", None)
    helpers_fn = getattr(d, "cpp_helpers", None)
    prelude = (prelude_fn() or "") if prelude_fn else ""
    helpers = (helpers_fn() or "") if helpers_fn else ""
    # Only kinds whose exported ABI takes i32 extents need the size gate;
    # Triton takes its scalar widths from the kernel's own signature. Any
    # narrowing kind among this op's points is enough, since any point may
    # be the one selected at runtime.
    narrows = any(
        toolchains.get_toolchain(sc["kind"]).NARROWS_SHAPES_TO_INT32 for sc in sidecars
    )
    covers_fn = covers_reg = ""
    if covers is not None:
        covers_params, covers_schema, covers_body = covers
        # Coverage must be no wider than the stub's acceptance: the
        # arch gate declines in the stub, so covers must decline on the
        # same devices or gated calls lose their JIT route.
        #
        # Read the TENSOR's device, not the current one: covers is called by the
        # router before any device guard, so on a mixed-capability host the
        # current device need not be the one the op will run on -- and the
        # declarations' own covers bodies already use
        # getDeviceProperties(self.device().index()).
        _cov_t = _first_tensor_name(covers_params)
        if _cov_t is None:
            # Refused rather than falling back to the current device. Without a
            # tensor there is nothing to ask is_cuda() of, so the predicate would
            # read current-device properties on every call of a catch-all custom
            # op -- initializing a CUDA context from a predicate, and ABORTING on
            # a GPU-less host (num_gpus=0) where the answer is simply false.
            raise RuntimeError(
                f"{op}: cpp_covers needs a plain at::Tensor parameter to read the "
                f"device from, and this signature has none ({covers_params}). "
                f"Drop cpp_covers for this op -- the Python covered_axes path "
                f"still applies -- or route it through an op whose schema takes a "
                f"Tensor."
            )
        covers_props = f"at::cuda::getDeviceProperties({_cov_t}.device().index())"
        # is_cuda BEFORE reading properties. covers is registered as a catch-all
        # custom op, so it is callable with a CPU tensor, and
        # getDeviceProperties(-1) falls back to the current device: that
        # initializes a CUDA context as a side effect of a predicate the router
        # runs on every call, and on a GPU-less host it aborts
        # (num_gpus=0) where the answer should simply be false. The declarations'
        # own bodies end in `return self.is_cuda();` -- this restores their
        # ability to decline.
        cuda_first = f"  if (!{_cov_t}.is_cuda()) return false;\n"
        covers_fn = COVERS_FN_TMPL.format(
            op=op,
            key_lc=key.lower(),
            params=covers_params,
            body=cuda_first
            + _gate_for(covers_props)
            + (_int32_size_gate(covers_params) if narrows else "")
            + indent(covers_body, "  "),
        )
        # Escaped: the schema goes into a C++ string literal, and a default
        # spelled with double quotes in native_functions.yaml (str mode="constant"
        # on pad, str padding="valid" on conv1d.padding, str UPLO="L" on
        # _linalg_eigh) closed the literal early -- a compile error inside a
        # @generated file, far from the declaration that caused it.
        covers_reg = COVERS_REG_TMPL.format(
            op=op,
            key_lc=key.lower(),
            schema=covers_schema.replace("\\", "\\\\").replace('"', '\\"'),
        )
    # State the group's precompute behavior where authors debug: a raw
    # dim compared unwrapped against self.dim()-1 silently declines
    # every negative-dim call (PAIN_POINTS P14).
    if precomputed:
        note = (
            f"Structured META precomputes (impl receives them wrapped/"
            f"replaced): {', '.join(precomputed)}"
        )
    else:
        note = (
            "Structured META precomputes NOTHING for this op: schema "
            "args (incl. any dim) arrive RAW -- wrap dims before comparing."
        )
    return FILE_TMPL.format(
        op=op,
        key_lc=key.lower(),
        key_uc=key.upper(),
        decl_path=decl_path or f"the declaration for aten::{op}",
        precompute_note=note,
        covers_fn=covers_fn,
        covers_reg=covers_reg,
        covers_include=(
            "#include <torch/library.h>\n\n" if covers is not None else "\n"
        ),
        kernel_includes="\n".join(
            dict.fromkeys(  # ordered dedup across sidecars
                line
                for sc in sidecars
                for tc in [toolchains.get_toolchain(sc["kind"])]
                for line in (*tc.kernel_includes(sc), *tc.launcher_includes)
            )
        ),
        launchers="\n".join(
            ([helpers] if helpers else []) + [gen_launcher(s) for s in sidecars]
        ),
        params=impl_params,
        size_gate_helper=SIZE_GATE_HELPER if narrows else "",
        cond=arch_gate
        + (_int32_size_gate(impl_params) if narrows else "")
        + indent(prelude, "  "),
        guards="\n".join(branches),
    )


def _structured_group(op: str):
    from torchgen.gen import get_grouped_native_functions, parse_native_yaml
    from torchgen.model import NativeFunctionsGroup

    aten = os.path.join(REPO, "aten", "src", "ATen")
    parsed = parse_native_yaml(
        os.path.join(aten, "native", "native_functions.yaml"),
        os.path.join(aten, "native", "tags.yaml"),
    )
    for g in get_grouped_native_functions(parsed.native_functions):
        # Base names repeat across groups (e.g. bmm vs bmm.dtype); the
        # kernel signature must come from the STRUCTURED group. Qualified
        # ops ("gt.Tensor") match the exact functional overload name.
        if isinstance(g, NativeFunctionsGroup) and g.structured:
            name = (
                str(g.functional.func.name)
                if "." in op
                else g.functional.func.name.name.base
            )
            if name == op:
                return g
    raise RuntimeError(f"no structured group for {op}")


def impl_signature_params(op: str) -> str:
    from torchgen.api import structured
    from torchgen.context import native_function_manager

    g = _structured_group(op)
    with native_function_manager(g):
        return ", ".join(b.decl() for b in structured.impl_arguments(g))


def precomputed_args(op: str) -> list[str]:
    """Schema argument names the structured META precomputes (replaces)
    before the impl runs -- e.g. index_add's dim arrives already
    maybe_wrap_dim'ed, while sum.dim_IntList's dim arrives RAW.
    Declarations must know which they get (PAIN_POINTS P14): a prelude
    comparing a raw negative dim against self.dim()-1 silently declines
    every dim=-1 call to stock aten. The generated .cpp states this per
    op; this helper answers it programmatically."""
    g = _structured_group(op)
    pre = g.out.precomputed
    return sorted(pre.replace.keys()) if pre is not None else []


def covers_signature(op: str) -> tuple[str, str]:
    """(C++ params, torch.library schema) for the fast coverage
    predicate: the FUNCTIONAL schema arguments (SymInt degraded to int
    -- symbolic sizes can't be covered anyway; a failed bind falls back
    to the Python path) plus the out variant's outputs as trailing
    optionals so calls arriving through the .out overload bind too.
    """
    from torchgen.api.types import DispatcherSignature
    from torchgen.context import native_function_manager

    g = _structured_group(op)
    with native_function_manager(g):
        sig = DispatcherSignature.from_schema(g.functional.func, symint=False)
        params = [a.decl() for a in sig.arguments()]
    # Render per-argument from the model (not string surgery on the
    # whole schema): SymInt -> int argument-by-argument, and the
    # kwarg-only marker reconstructed from the model's split.
    args = g.functional.func.arguments
    pos = [str(a).replace("SymInt", "int") for a in args.flat_positional]
    kw = [str(a).replace("SymInt", "int") for a in args.flat_kwarg_only]
    pieces = pos + (["*", *kw] if kw else [])
    # Trailing out-variant outputs bind the .out overload's kwargs;
    # appended last, so kwarg-only exactly when the schema already has
    # a kwarg section (matching the C++ params' positional binding).
    for a in g.out.func.arguments.out:
        params.append(f"const std::optional<at::Tensor>& {a.name}")
        pieces.append(f"Tensor? {a.name}=None")
    schema_args = ", ".join(pieces)
    # Op name in the registered schema is the decl_id (dots are illegal
    # in custom-op names); the runtime resolves covers_<decl_id> too.
    return (
        ", ".join(params),
        f"covers_{decl.decl_id_for_op(op)}({schema_args}) -> bool",
    )


VERSION_SCRIPT = "native_aot_local.ver"

VER_TMPL = """\
/* @generated by tools/native_aot/gen_aot_lib.py -- do not edit
 *
 * Localize the exported kernel objects' entry points. CuTeDSL's
 * export_to_c gives them default visibility and they link straight into
 * torch_cuda (caffe2/CMakeLists.txt), so without this they would join
 * torch_cuda's public ABI: hundreds of names with no stability guarantee,
 * tied to the DSL's codegen. The generated launchers are the only callers
 * and share the link, so localizing costs nothing.
 *
 * Generated rather than hand-written so every pattern is anchored on a
 * kernel prefix: a bare `*_cuda_init` would also localize any unrelated
 * extern "C" symbol in torch_cuda ending that way, and a symbol silently
 * leaving the ABI is painful to debug.
 *
 * `local:` alone restricts nothing else -- with no `global:` pattern the
 * linker keeps its default of exporting everything not named here.
 */
{{
  local:
{patterns}
}};
"""


def surviving_sidecars(op: str, sidecars: list[dict]) -> list[dict]:
    """The sidecars generation will actually wire a launcher up to.

    The arch tie-break in _by_arch drops candidates, and EVERY consumer has to
    agree on that set: the launchers, the object list CMake links, the version
    script, and the reported kernel count. gen_op used to compute it privately,
    so main() built the list and the script from the UNFILTERED sidecars and the
    dropped objects shipped inside libtorch_cuda unreferenced -- the exact dead
    weight the object list exists to prevent (measured: 3 of 6 listed objects
    with no launcher). Called by main() ahead of gen_op, which re-groups the
    already-filtered list idempotently."""
    kept = [sc for scs in _by_arch(sidecars).values() for sc in scs]
    if dropped := {sc["arch"] for sc in sidecars} - {sc["arch"] for sc in kept}:
        print(
            f"{op}: ignoring artifacts for {sorted(dropped)} -- an "
            f"arch-conditional build for the same capability wins. They are not "
            f"linked; delete those trees to reclaim the disk."
        )
    return kept


# The one file CMake reads. It is not data for CMake to interpret: it IS the
# CMake calls, emitted here, so caffe2/CMakeLists.txt is a single
# include(... OPTIONAL) with no logic of its own. Named .cmake rather than .txt
# for exactly that reason.
CMAKE_INCLUDE = "native_aot.cmake"


def _cmake_str(value: str) -> str:
    """A python string as a quoted CMake argument.

    Escaped in this order, because each character means something to CMake's
    parser: backslash (a path on any platform can hold one), double quote (ends
    the argument), dollar (starts a variable reference, and a build directory can
    contain one), and semicolon (CMake's list separator -- unescaped, one path
    with a semicolon becomes two)."""
    for char in ("\\", '"', "$", ";"):
        value = value.replace(char, "\\" + char)
    return f'"{value}"'


def _write_atomic(path: str, text: str) -> str:
    """Write via a temp file + rename, so a crash cannot leave a partial file
    that CMake would read as authoritative."""
    tmp = path + ".tmp"
    try:
        with open(tmp, "w") as f:
            f.write(text)
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.remove(tmp)
    return path


def _delete_generated(artifacts_dir: str, decl_id: str, why: str) -> None:
    """Drop a declaration's generated source. Regenerating one is free; the
    artifacts it describes are never touched.

    Called from both places a declaration can stop contributing: its arch trees
    are gone (or excluded by --archs), and its trees are present but hold no
    sidecar. The second case used to `continue` silently, leaving a source that
    compiles and then references module entry points whose object is not in the
    link set -- green link, symbol lookup error at first use."""
    src_dir = os.path.join(artifacts_dir, decl_id)
    if not os.path.isdir(src_dir):
        return
    for fn in sorted(os.listdir(src_dir)):
        if fn.startswith("aot_") and fn.endswith(".cpp"):
            os.remove(os.path.join(src_dir, fn))
            print(f"{decl_id}: {why}, deleted stale {fn}")


def write_cmake_include(
    artifacts_dir: str,
    sources: list[str],
    objects: list[str],
    version_script: str,
    dsl_runtime: str | None,
    arch_list: str | None,
) -> str:
    """Emit the CMake calls that embed this generation into torch_cuda.

    Written atomically and LAST, so its presence is the only evidence that a
    generation finished. CMake does nothing but include it, which is why every
    decision -- and every diagnostic -- has to be resolved here:

      * the OPT-OUT is a generated `return()`, because only CMake is running at
        configure time and a previous run's file may be on disk; checking it here
        keeps the branch out of caffe2/CMakeLists.txt;
      * paths are ABSOLUTE and escaped, since CMake resolves relative ones
        against a different directory than this process;
      * the version script and --exclude-libs go through `SHELL:-Xlinker`, and
        the quoting is not optional: -Wl, (what LINKER: expands to) is split on
        commas by the compiler driver, bare -Xlinker tokens are collapsed by
        target_link_options' de-duplication, and SHELL: splits its own value on
        spaces;
      * BUILD_WITH_INSTALL_RPATH, because stage 2 copies build/lib/libtorch_cuda.so
        over the installed one and the two must agree; it is set here rather than
        for every CUDA build because building with the install RPATH drops link
        directories inside the source or binary tree.

    Nothing is emitted when there is nothing to embed: an absent or empty file is
    the "no kernels" state, so a tree that never exported and a generation that
    refused look the same to the build, which is what keeps the main build
    independent of stage 2 having run."""
    if not sources:
        return _write_atomic(
            os.path.join(artifacts_dir, CMAKE_INCLUDE),
            "# @generated by tools/native_aot/gen_aot_lib.py -- do not edit.\n"
            "# Nothing to embed for this build.\n",
        )

    srcs = [os.path.abspath(p) for p in sorted(sources)]
    objs = [os.path.abspath(p) for p in sorted(objects)]
    # A SEMICOLON cannot be carried through. Escaping it as \; does produce a
    # literal semicolon in the value, but CMake re-splits a source list on it
    # downstream, so the build asks for the prefix before the semicolon
    # ("ninja: error: '/tmp/x/semi', needed by libtorch_cuda.so, missing") --
    # verified. Refused here, naming the path, rather than emitted as a file that
    # configures cleanly and then cannot build. Quotes, backslashes and dollars DO
    # survive _cmake_str, so only this one is fatal.
    for path in srcs + objs + [version_script] + ([dsl_runtime] if dsl_runtime else []):
        if ";" in path or "\n" in path:
            raise RuntimeError(
                f"native-AOT: cannot embed {path!r} -- CMake splits source lists on "
                f"';' (and a newline cannot appear in a CMake argument), so this "
                f"path cannot reach the build intact. Move the build directory (or "
                f"the DSL wheel) somewhere without those characters, or set "
                f"TORCH_NATIVE_AOT=0 to build without embedded kernels."
            )
    out = [
        "# @generated by tools/native_aot/gen_aot_lib.py -- do not edit.",
        "#",
        "# Included by caffe2/CMakeLists.txt. Every decision behind these calls was",
        "# made by the generator; edit tools/native_aot/gen_aot_lib.py instead.",
        f"# Generated for TORCH_CUDA_ARCH_LIST={arch_list!r}."
        if arch_list is not None
        else "# Generated without an arch list (a hand run, or an on-device export).",
        "",
        "# The opt-out, checked here because only CMake runs at configure time and a",
        "# previous run's file can still be on disk. A blank value reads as absent, and",
        "# CMake truthiness means OFF/false/no work as well as 0 -- matching",
        "# build_stage2._OPT_OUT_VALUES, so the two sides cannot disagree.",
        'if(DEFINED ENV{TORCH_NATIVE_AOT} AND NOT "$ENV{TORCH_NATIVE_AOT}" STREQUAL ""',
        '   AND NOT "$ENV{TORCH_NATIVE_AOT}")',
        '  message(STATUS "native-AOT: TORCH_NATIVE_AOT=$ENV{TORCH_NATIVE_AOT}, not embedding kernels")',
        "  return()",
        "endif()",
        "if(DEFINED TORCH_NATIVE_AOT AND NOT TORCH_NATIVE_AOT)",
        '  message(STATUS "native-AOT: TORCH_NATIVE_AOT=${TORCH_NATIVE_AOT}, not embedding kernels")',
        "  return()",
        "endif()",
        "",
        "# Re-run configure when this file changes, so a later export + relink picks the",
        "# new kernels up even without stage 2 asking for a reconfigure.",
        # No DIRECTORY argument: inside an included file CMAKE_CURRENT_LIST_DIR is
        # the ARTIFACTS dir, which CMake has not processed as a directory, so
        # naming it is an error ("requested directory was not found"). Omitted, the
        # property lands on the directory doing the include, which is the one whose
        # configure has to re-run.
        "set_property(DIRECTORY APPEND PROPERTY",
        f"    CMAKE_CONFIGURE_DEPENDS {_cmake_str(os.path.join(os.path.abspath(artifacts_dir), CMAKE_INCLUDE))})",
        "",
        f'message(STATUS "native-AOT: embedding {len(objs)} object(s) from '
        f'{len(srcs)} generated source(s)")',
        "",
    ]
    if objs:
        # EXTERNAL_OBJECT but NOT GENERATED: nothing in this build produces these
        # objects, and GENERATED tells CMake to stop checking they exist -- which
        # defers a missing one to "ninja: error: ... missing and no known rule to
        # make it", naming neither native-AOT nor a remedy.
        out += [
            "set_source_files_properties(",
            *[f"    {_cmake_str(o)}" for o in objs],
            "    PROPERTIES EXTERNAL_OBJECT TRUE)",
            "",
        ]
    out += [
        "target_sources(torch_cuda PRIVATE",
        *[f"    {_cmake_str(p)}" for p in srcs + objs],
        ")",
        "",
        "if(UNIX AND NOT APPLE)",
        "  set_target_properties(torch_cuda PROPERTIES BUILD_WITH_INSTALL_RPATH TRUE)",
        "  target_link_options(torch_cuda PRIVATE",
        f'      "SHELL:-Xlinker --version-script -Xlinker \\"{os.path.abspath(version_script)}\\"")',
        "  # LINK_DEPENDS as well as the option: without it ninja does not relink when",
        "  # only the script changes, so new entry points would stay public.",
        "  set_property(TARGET torch_cuda APPEND PROPERTY",
        f"      LINK_DEPENDS {_cmake_str(os.path.abspath(version_script))})",
        "endif()",
    ]
    if dsl_runtime:
        name = os.path.basename(dsl_runtime)
        out += [
            "",
            "# whole-archive is NOT needed (the kernels reference it directly); exclude-libs",
            "# keeps its symbols out of torch_cuda's export table.",
            f"target_link_libraries(torch_cuda PRIVATE {_cmake_str(os.path.abspath(dsl_runtime))})",
            "if(UNIX AND NOT APPLE)",
            "  target_link_options(torch_cuda PRIVATE",
            f'      "SHELL:-Xlinker --exclude-libs -Xlinker \\"{name}\\"")',
            "endif()",
        ]
    return _write_atomic(
        os.path.join(artifacts_dir, CMAKE_INCLUDE), "\n".join(out) + "\n"
    )


def write_version_script(artifacts_dir: str, prefixes: list[str]) -> str:
    """Emit the linker version script localizing every exported kernel's
    symbols. Two spellings per prefix: the DSL emits a bare _mlir_<...>
    form and a prefix-first <prefix>__mlir_ciface_* form; the module
    loader adds the four _cuda_* entry points."""
    lines = []
    for prefix in sorted(prefixes):
        # Two patterns cover every global symbol the DSL emits for a kernel
        # (verified with nm over the exported objects): everything is either
        # named <prefix>_... or is an MLIR entry point carrying the prefix.
        # Enumerating known suffixes instead missed _args_spec, _kernel_info,
        # _function_name, _version and the mangled cutlass call symbol -- 270
        # of 864 symbols, which stayed in torch_cuda's ABI.
        lines.append(f"    /* {prefix} */")
        lines.append(f"    {prefix}_*;")
        lines.append(f"    _mlir_*{prefix}*;")
    # Atomically, like the manifest: a truncated version script passes CMake's
    # EXISTS check and reaches the linker as a syntax error that names nothing.
    return _write_atomic(
        os.path.join(artifacts_dir, VERSION_SCRIPT),
        VER_TMPL.format(patterns="\n".join(lines)),
    )


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--artifacts-dir", default=os.path.join(REPO, "build", "native_aot")
    )
    parser.add_argument(
        "--archs",
        nargs="*",
        help="restrict generation to these arch trees (sm strings). Stage 2 "
        "passes the arches this build targets, so a tree left by a build with "
        "a different TORCH_CUDA_ARCH_LIST is ignored rather than shipped",
    )
    parser.add_argument(
        "--dsl-runtime",
        default=None,
        help="the DSL runtime static archive to link (build_stage2 finds it; "
        "CMake used to glob for it per CUDA major)",
    )
    parser.add_argument(
        "--arch-list",
        default=None,
        help="the raw TORCH_CUDA_ARCH_LIST this generation is for, recorded in "
        "the manifest so caffe2/CMakeLists.txt can refuse artifacts generated "
        "for another one. Passed by stage 2; omit it for a hand run and the "
        "manifest records no claim rather than an empty one (reading the "
        "environment here instead let a hand run overwrite -- or fabricate -- a "
        "claim about a list it never consulted)",
    )
    parser.add_argument(
        "--allow-stale",
        action="store_true",
        help="generate even when artifact source hashes mismatch the tree "
        "(a sidecar SCHEMA mismatch stays fatal: its fields may not be "
        "readable)",
    )
    args = parser.parse_args(argv)

    from tools.native_aot import export as export_mod

    # Artifact dirs are named by decl_id (one per declaration; family
    # modules under one ops/<dir> produce several). Map them back to
    # their declarations by scanning every aot.py.
    by_id = {}
    for entry in sorted(os.listdir(OPS_DIR)):
        path = os.path.join(OPS_DIR, entry, "aot.py")
        if os.path.exists(path):
            for d in decl.load_declarations(path):
                # Keep the real source path: a family module's decl_ids do
                # not name their own directory (pointwise/aot.py declares
                # acos, add.Tensor, ...), so it cannot be reconstructed.
                by_id[decl.decl_id(d)] = (d, os.path.relpath(path, REPO))

    if not os.path.isdir(args.artifacts_dir):
        # Zero declarations => export wrote nothing and never created
        # the dir. A normal artifacts-free build, not an error (the
        # embedded glob in caffe2/CMakeLists.txt degrades the same way).
        print(f"{args.artifacts_dir}: no artifacts, nothing to generate")
        return

    # decl_id -> its arch dirs, so one declaration's artifacts are generated
    # together however many arches it shipped for: a per-arch dir generated on
    # its own would emit one .cpp per arch, each registering the same
    # DispatchStub.
    dirs_by_id: dict[str, list[str]] = {}
    for entry in sorted(os.listdir(args.artifacts_dir)):
        art_dir = os.path.join(args.artifacts_dir, entry)
        if not os.path.isdir(art_dir):
            continue
        # ONE layout: <root>/<arch>/<decl_id>/ holds the artifacts, and
        # <root>/<decl_id>/ holds only the generated .cpp that covers every
        # arch. So every top-level directory is an arch, and its subdirectories
        # are declarations; a top-level directory with no subdirectories is a
        # generated-source dir and has nothing to discover.
        children = [
            c
            for c in sorted(os.listdir(art_dir))
            if os.path.isdir(os.path.join(art_dir, c))
        ]
        # An arch tree this build did not ask for is left ALONE, not generated
        # from and not linked: nothing prunes trees, so an incremental build
        # whose TORCH_CUDA_ARCH_LIST changed still has the old one. Generating
        # from it would ship a capability nobody requested, and its staleness
        # would fail the build telling you to re-export an arch you dropped.
        if children and args.archs and entry not in args.archs:
            print(f"{entry}: not in this build's arch list, ignoring its artifacts")
            continue
        for child in children:
            dirs_by_id.setdefault(child, []).append(os.path.join(art_dir, child))

    # A generated source whose artifacts are all gone -- an arch tree deleted by
    # hand, or every tree it had skipped by --archs -- is deleted here. It is not
    # reached by the loop below (that walks decl_ids that still HAVE artifacts),
    # and leaving it means the link glob compiles a file whose
    # #include "../<arch>/<id>/..." no longer resolves: a compile error naming a
    # generated file, with nothing pointing at the tree the user removed.
    # Regenerating a source is free, so deleting is safe; artifacts never are.
    for entry in sorted(os.listdir(args.artifacts_dir)):
        src_dir = os.path.join(args.artifacts_dir, entry)
        if not os.path.isdir(src_dir) or entry in dirs_by_id:
            continue
        _delete_generated(args.artifacts_dir, entry, "no artifacts remain")

    all_prefixes: list[str] = []
    link_objects: list[str] = []
    # (out_dir, path, source, kernel count) -- written only once every
    # declaration has passed its refusals; see the commit step after the loop.
    pending: list[tuple[str, str, str, int]] = []
    for entry, art_dirs in sorted(dirs_by_id.items()):
        d, decl_path = by_id.get(entry, (None, ""))
        if d is None:
            # Orphaned artifact dir (declaration renamed/removed): its
            # previously generated .cpp would still be globbed by the build
            # and reference a stub that no longer exists -- a link error far
            # from the cause. Delete that (regenerating is free) but NEVER
            # the kernel artifacts, which cost a full export to rebuild.
            # They must not silently link either, so leaving them behind is
            # an error the user resolves by removing the directory.
            #
            # An empty by_id means this tree declares nothing at all (an
            # earlier commit of a stack, or a bisect) -- NOT that every
            # artifact is orphaned. Deleting there would destroy a whole
            # export for a checkout that simply predates the declarations.
            entries = [
                os.path.join(one, fn) for one in art_dirs for fn in os.listdir(one)
            ]
            if not by_id or not any(os.path.isfile(p) for p in entries):
                continue
            # The stale .cpp sits with the generated sources at
            # <root>/<decl_id>/, not in the arch tree the artifacts live in, so
            # look for it there -- that is the copy the CMake glob would still
            # compile against a stub that no longer exists.
            src_dir = os.path.join(args.artifacts_dir, entry)
            removed = []
            for fn in sorted(os.listdir(src_dir) if os.path.isdir(src_dir) else []):
                if fn.startswith("aot_") and fn.endswith(".cpp"):
                    os.remove(os.path.join(src_dir, fn))
                    removed.append(fn)
            print(
                f"{entry}: no declaration (renamed or removed?); "
                + (f"deleted stale {', '.join(removed)}" if removed else "skipped")
            )
            # Reported, not fatal. Under the manifest design nothing links an
            # artifact the manifest does not name, and the stale .cpp that COULD
            # have referenced one was just deleted above -- so what is left on
            # disk is inert, exactly like the two states already reported rather
            # than refused (an arch tie-break loser, and a tree outside --archs).
            # As a fatal it also failed every later build until the user deleted a
            # full export by hand, and it fired for a directory holding only the
            # ABI header, which is never a link input at all.
            #
            # Per arch dir, because `entries` spans all of them: naming
            # art_dirs[0] while listing basenames gathered from every tree told
            # the user to look for files that were not in the directory named.
            leftover_exts = toolchains.all_artifact_exts()
            for one in art_dirs:
                leftover = sorted(
                    fn
                    for fn in os.listdir(one)
                    if os.path.splitext(fn)[1] in leftover_exts
                )
                if leftover:
                    print(
                        f"{one}: {len(leftover)} artifact(s) with no declaration "
                        f"({', '.join(leftover[:4])}"
                        f"{', ...' if len(leftover) > 4 else ''}); not linked -- "
                        f"delete this directory to reclaim the disk."
                    )
            continue
        sidecars = []
        # Across every arch dir this declaration exported into.
        for one_dir in art_dirs:
            for fn in sorted(os.listdir(one_dir)):
                if fn.endswith(".json"):
                    path = os.path.join(one_dir, fn)
                    sc = export_mod._read_sidecar(path)
                    # SCHEMA FIRST: every check below reads fields by name, and a
                    # different version may not mean by them what this generator
                    # thinks. A bump is not waivable by --allow-stale, which
                    # exists for artifacts whose SOURCES drifted while still
                    # describing themselves in a shape this generator reads.
                    if sc.get("version") != export_mod.SIDECAR_VERSION:
                        raise RuntimeError(
                            f"{path}: sidecar schema version {sc.get('version')!r}, "
                            f"but this generator reads version "
                            f"{export_mod.SIDECAR_VERSION}. Re-export this arch "
                            f"({sc.get('arch') or 'unknown arch'}) or delete the "
                            f"tree; generation cannot be forced past a schema "
                            f"change."
                        )
                    # The prefix names this kernel's extern "C" entry points and
                    # its launcher, so a value that is not a C identifier reaches
                    # the compiler as a syntax error inside a @generated file --
                    # far from the export that chose it.
                    prefix = sc.get("prefix", "")
                    if not _C_IDENT.fullmatch(prefix):
                        raise RuntimeError(
                            f"{path}: prefix {prefix!r} is not a C identifier. It "
                            f'names the kernel\'s extern "C" symbols and its '
                            f"launcher, so generation would emit C++ that does "
                            f"not compile."
                        )
                    # Generation-time context: a toolchain whose launcher embeds
                    # the artifact's bytes reads them from the sidecar's dir.
                    sc["_dir"] = one_dir
                    # Include path from where the generated .cpp lands (always
                    # <root>/<decl_id>/, see out_dir below): "../<arch>/<id>"
                    # the artifacts sit one level below it.
                    rel = os.path.relpath(
                        one_dir, os.path.join(args.artifacts_dir, entry)
                    )
                    if rel != ".":
                        # Forward slashes: this goes into an #include, where a
                        # Windows separator would not resolve.
                        sc["_include_dir"] = rel.replace(os.sep, "/")
                    sidecars.append(sc)
        # One prefix must come from one artifact, or the generated file defines
        # launch_<prefix> twice and the same object is globbed twice. Prefixes
        # carry their arch, so the export cannot produce this; a copied or
        # renamed arch tree can. Never deleted automatically: artifacts cost a
        # full export to rebuild.
        seen: dict[str, str] = {}
        for sc in sidecars:
            p = sc.get("prefix", "")
            if p in seen:
                raise RuntimeError(
                    f"{entry}: {p} is present in both {seen[p]} and "
                    f"{sc['_dir']}. Each arch directory must hold its own "
                    f"artifacts once; a copied or renamed tree duplicates them. "
                    f"Delete whichever is stale and re-run generation."
                )
            seen[p] = sc["_dir"]
        # Filter BEFORE judging staleness: a candidate the tie-break drops can
        # never reach the library, so a stale leftover `sm_100` beside a fresh
        # `sm_100a` used to fail the whole run -- and the advice it printed
        # re-exported a full set of kernels that generation drops again.
        sidecars = surviving_sidecars(entry, sidecars)
        # The sidecar records the builder's source closure AND the DSL versions
        # that compiled it. A mismatch in either means the artifact no longer
        # corresponds to what this tree would produce: edited kernel source, or
        # an upgraded compiler, which changes nothing on disk and so cannot be
        # caught by the closure.
        stale = [
            sc
            for sc in sidecars
            if not (export_mod.sources_current(sc) and export_mod.runtimes_current(sc))
        ]
        if stale and not args.allow_stale:
            # Name the arches, and re-export THEM: a bare export.py run only
            # maintains the one arch it resolves for (--arch, a toolchain's arch
            # variable, or the local device), so it silently leaves every other
            # arch tree stale -- and a tree that carries several is the normal
            # case here. "Just re-run export" is the advice that does not work.
            archs = sorted({sc.get("arch") or "?" for sc in stale})
            raise RuntimeError(
                f"{entry}: {len(stale)} artifact(s) were exported from "
                f"different kernel sources than the current tree (e.g. "
                f"{stale[0].get('prefix')} in {stale[0]['_dir']}). Re-export "
                f"those arches -- `python tools/native_aot/export.py --arch "
                f"{' '.join(archs)}` -- or delete their trees. Pass "
                f"--allow-stale to generate anyway."
            )
        if not sidecars:
            # A declaration whose artifacts are gone but whose directory remains
            # (a partial `rm`, or the "delete their trees" advice above taken
            # literally). Its generated source must go with them: it would still
            # compile -- the ABI header is a separate file -- and then reference
            # module entry points whose object this run did not list, which links
            # green (nothing passes --no-undefined) and fails at symbol lookup.
            _delete_generated(args.artifacts_dir, entry, "no sidecars remain")
            continue
        did, key = decl.decl_id(d), d.DISPATCH_KEY
        covers = None
        covers_fn = getattr(d, "cpp_covers", None)
        covers_body = (covers_fn() or "") if covers_fn else ""
        if covers_body:
            params, schema = covers_signature(d.ATEN_OP)
            covers = (params, schema, covers_body)
        # Everything that can REFUSE this declaration runs before anything is
        # written, and the sources are BUFFERED to the end of the loop: a refusal
        # in declaration N used to leave declaration 1..N-1's fresh sources
        # paired with the previous run's manifest, which the next main build
        # linked into an undefined-symbol failure that only stage 2 -- running
        # after it -- could have repaired.
        entry_objects = []
        for sc in sidecars:
            tc = toolchains.get_toolchain(sc["kind"])
            tc.validate_abi(sc)
            # EVERY artifact the sidecar claims must be on disk, not just the
            # link inputs: a missing ABI header otherwise became a `fatal error:
            # no such file` inside a @generated file, and silently turned
            # validate_abi (which reads that header) into a no-op.
            for ext in tc.artifact_exts:
                art = os.path.join(sc["_dir"], sc["prefix"] + ext)
                if not os.path.exists(art):
                    raise RuntimeError(
                        f"{art}: sidecar describes an artifact that is not on "
                        f"disk. The launcher would be emitted and the artifact "
                        f"missing at compile or link time; re-export this arch "
                        f"({sc.get('arch')}) or delete {sc['_dir']}."
                    )
                if ext in tc.link_exts:
                    entry_objects.append(art)
        src = gen_op(
            did,
            key,
            d,
            sidecars,
            impl_signature_params(d.ATEN_OP),
            covers,
            precomputed_args(d.ATEN_OP),
            decl_path,
        )
        # The source covers every arch this declaration shipped, so it belongs
        # to no single arch tree: always <root>/<decl_id>/, one arch or many.
        out_dir = os.path.join(args.artifacts_dir, entry)
        out = os.path.join(out_dir, f"aot_{did}_{key.lower()}.cpp")
        pending.append((out_dir, out, src, len(sidecars)))
        all_prefixes.extend(sc["prefix"] for sc in sidecars)
        link_objects.extend(entry_objects)

    # Past every refusal: INVALIDATE the old manifest, then commit the sources,
    # then the version script, then the new manifest LAST -- its presence is what
    # tells CMake a generation finished.
    #
    # Removing it first is what makes the window between sources harmless. Each
    # source is written atomically, but the paths are deterministic, so the
    # previous manifest already names them: a run that died after source 1 left
    # THAT source fresh beside the previous run's OBJECT list, and the main build
    # then failed on undefined symbols -- with stage 2, the only writer that could
    # repair it, running after that build. With no manifest present, the same state
    # reads as "not generated yet" and the build proceeds without embedding.
    stale = os.path.join(args.artifacts_dir, CMAKE_INCLUDE)
    if os.path.exists(stale):
        os.remove(stale)
    for out_dir, out, src, n in pending:
        os.makedirs(out_dir, exist_ok=True)
        # Atomically, like the manifest and the version script: the path is
        # deterministic, so the PREVIOUS run's manifest already names it, and
        # CMake validates only that it exists. A run killed here (hard kill,
        # ENOSPC) left a truncated @generated .cpp that the old manifest still
        # pointed at, so the MAIN build failed compiling it -- and stage 2, the
        # only writer that could repair it, runs after that build.
        _write_atomic(out, src)
        print(f"wrote {out} ({n} kernels)")
    ver = write_version_script(args.artifacts_dir, all_prefixes)
    print(f"wrote {ver}")
    print(
        f"wrote {write_cmake_include(args.artifacts_dir, [p[1] for p in pending], link_objects, ver, args.dsl_runtime, args.arch_list)}"
    )


if __name__ == "__main__":
    main()
