#!/bin/bash
set -e

echo "Running pre-commit flake8"
python3 tools/linter/flake8_hook.py

if [ $(which clang-tidy) ]
then
  echo "Running pre-commit clang-tidy"
  git diff HEAD > pr.diff
  python3 -m tools.linter.clang_tidy --diff-file "pr.diff"
  rm pr.diff
else
  echo "WARNING: Couldn't find clang-tidy executable."
  echo "  Please install it if you want local clang-tidy checks."
fi

echo "Running pre-commit clang-format"
tools/linter/git-clang-format HEAD~ --force
