if (WIN32)
  set(TORCH_PYTHON_IMPORTED_LOCATION "${PYTORCH_INSTALL_DIR}/lib/torch_python.lib")
  set(TORCH_PYTHON_LINK_LIBS
    "${PYTORCH_INSTALL_DIR}/lib/c10.lib"
    "${PYTORCH_INSTALL_DIR}/lib/torch_cpu.lib"
  )
  set(TORCH_PYTHON_LIBRARY_LINK
    "\$<TARGET_FILE:torch_python>;\$<TARGET_PROPERTY:torch_python,INTERFACE_LINK_LIBRARIES>"
  )
else()
  set(TORCH_PYTHON_IMPORTED_LOCATION "${PYTORCH_INSTALL_DIR}/lib/libtorch_python.so")
  set(TORCH_PYTHON_LINK_LIBS "c10;torch_cpu")
  set(TORCH_PYTHON_LIBRARY_LINK
    "-Wl,--no-as-needed,\"\$<TARGET_FILE:torch_python>\" -Wl,--as-needed;"
    "\$<TARGET_PROPERTY:torch_python,INTERFACE_LINK_LIBRARIES>"
  )
endif()

add_library(torch_python SHARED IMPORTED)

set_target_properties(torch_python PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "USE_DISTRIBUTED;USE_C10D_GLOO;USE_C10D_MPI;USE_RPC;USE_TENSORPIPE"
  INTERFACE_INCLUDE_DIRECTORIES "${PYTORCH_INSTALL_DIR}/include"
  INTERFACE_LINK_LIBRARIES "${TORCH_PYTHON_LINK_LIBS}"
  IMPORTED_LOCATION "${TORCH_PYTHON_IMPORTED_LOCATION}"
)

add_library(torch_python_library INTERFACE IMPORTED)

set_target_properties(torch_python_library PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<TARGET_PROPERTY:torch_python,INTERFACE_COMPILE_DEFINITIONS>"
  INTERFACE_COMPILE_OPTIONS "\$<TARGET_PROPERTY:torch_python,INTERFACE_COMPILE_OPTIONS>"
  INTERFACE_INCLUDE_DIRECTORIES "\$<TARGET_PROPERTY:torch_python,INTERFACE_INCLUDE_DIRECTORIES>"
  INTERFACE_LINK_LIBRARIES "${TORCH_PYTHON_LIBRARY_LINK}"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "\$<TARGET_PROPERTY:torch_python,INTERFACE_SYSTEM_INCLUDE_DIRECTORIES>"
)