def define_targets(rules):
    rules.cc_library(
        name = "TypeCast",
        srcs = ["TypeCast.cpp"],
        hdrs = ["TypeCast.h"],
        linkstatic = True,
        local_defines = ["C10_BUILD_MAIN_LIB"],
        visibility = ["//visibility:public"],
        deps = [
            ":base",
            "//c10/core:ScalarType",
            "//c10/macros",
        ],
    )

    rules.cc_library(
        name = "base",
        srcs = [
            "Array.cpp",
            "Backtrace.cpp",
            "C++17.cpp",
            "DeadlockDetection.cpp",
            "Exception.cpp",
            "Half.cpp",
            "LeftRight.cpp",
            "Logging.cpp",
            "MathConstants.cpp",
            "Metaprogramming.cpp",
            "Optional.cpp",
            "SmallVector.cpp",
            "StringUtil.cpp",
            "ThreadLocalDebugInfo.cpp",
            "TypeList.cpp",
            "TypeTraits.cpp",
            "Type_demangle.cpp",
            "Type_no_demangle.cpp",
            "Unicode.cpp",
            "UniqueVoidPtr.cpp",
            "complex_math.cpp",
            "flags_use_gflags.cpp",
            "flags_use_no_gflags.cpp",
            "int128.cpp",
            "intrusive_ptr.cpp",
            "numa.cpp",
            "signal_handler.cpp",
            "thread_name.cpp",
        ],
        hdrs = [
            "AlignOf.h",
            "Array.h",
            "ArrayRef.h",
            "BFloat16-inl.h",
            "BFloat16-math.h",
            "BFloat16.h",
            "Backtrace.h",
            "Bitset.h",
            "C++17.h",
            "ConstexprCrc.h",
            "DeadlockDetection.h",
            "Deprecated.h",
            "Exception.h",
            "ExclusivelyOwned.h",
            "Flags.h",
            "FunctionRef.h",
            "Half-inl.h",
            "Half.h",
            "IdWrapper.h",
            "LeftRight.h",
            "Logging.h",
            "MathConstants.h",
            "MaybeOwned.h",
            "Metaprogramming.h",
            "Optional.h",
            "Registry.h",
            "ScopeExit.h",
            "SmallBuffer.h",
            "SmallVector.h",
            "StringUtil.h",
            "ThreadLocal.h",
            "ThreadLocalDebugInfo.h",
            "Type.h",
            "TypeIndex.h",
            "TypeList.h",
            "TypeSafeSignMath.h",
            "TypeTraits.h",
            "Unicode.h",
            "UniqueVoidPtr.h",
            "Unroll.h",
            "accumulate.h",
            "complex.h",
            "complex_math.h",
            "complex_utils.h",
            "copysign.h",
            "either.h",
            "env.h",
            "flat_hash_map.h",
            "hash.h",
            "in_place.h",
            "int128.h",
            "intrusive_ptr.h",
            "irange.h",
            "llvmMathExtras.h",
            "logging_is_google_glog.h",
            "logging_is_not_google_glog.h",
            "math_compat.h",
            "numa.h",
            "order_preserving_flat_hash_map.h",
            "overloaded.h",
            "python_stub.h",
            "qint32.h",
            "qint8.h",
            "quint2x4.h",
            "quint4x2.h",
            "quint8.h",
            "reverse_iterator.h",
            "signal_handler.h",
            "sparse_bitset.h",
            "string_utils.h",
            "string_view.h",
            "tempfile.h",
            "thread_name.h",
            "variant.h",
            "win32-headers.h",
        ],
        # This library uses flags and registration. Do not let the
        # linker remove them.
        alwayslink = True,
        linkstatic = True,
        local_defines = ["C10_BUILD_MAIN_LIB"],
        visibility = ["//visibility:public"],
        deps = [
            "@fmt",
            "//c10/macros",
        ] + rules.select({
            "//c10:using_gflags": ["@com_github_gflags_gflags//:gflags"],
            "//conditions:default": [],
        }) + rules.select({
            "//c10:using_glog": ["@com_github_glog//:glog"],
            "//conditions:default": [],
        }),
    )

    rules.cc_library(
        name = "typeid",
        srcs = ["typeid.cpp"],
        hdrs = ["typeid.h"],
        linkstatic = True,
        local_defines = ["C10_BUILD_MAIN_LIB"],
        visibility = ["//visibility:public"],
        deps = [
            ":base",
            "//c10/core:ScalarType",
            "//c10/macros",
        ],
    )

    rules.filegroup(
        name = "headers",
        srcs = rules.glob(
            ["*.h"],
            exclude = [
            ],
        ),
        visibility = ["//c10:__pkg__"],
    )
