#pragma once

#include "TensorLib/Scalar.h"
#include "TensorLib/Type.h"
#include "TensorLib/Generator.h"
#include "TensorLib/CPUGenerator.h"
#include "TensorLib/CUDAGenerator.h"
#include "TensorLib/Context.h"
#include "TensorLib/Storage.h"

#include "TensorLib/CPUByteStorage.h"
#include "TensorLib/CPUCharStorage.h"
#include "TensorLib/CPUDoubleStorage.h"
#include "TensorLib/CPUFloatStorage.h"
#include "TensorLib/CPUIntStorage.h"
#include "TensorLib/CPULongStorage.h"
#include "TensorLib/CPUShortStorage.h"
#include "TensorLib/CPUHalfStorage.h"
#include "TensorLib/CUDAByteStorage.h"
#include "TensorLib/CUDACharStorage.h"
#include "TensorLib/CUDADoubleStorage.h"
#include "TensorLib/CUDAFloatStorage.h"
#include "TensorLib/CUDAIntStorage.h"
#include "TensorLib/CUDALongStorage.h"
#include "TensorLib/CUDAShortStorage.h"
#include "TensorLib/CUDAHalfStorage.h"
