#pragma once

#include <cstdint>

namespace thd {

enum Functions: std::uint16_t {
  // generator functions
  generatorConstruct,
  generatorCopy,
  generatorFree,
  generatorSeed,
  generatorManualSeed,

  tensorConstruct,
  tensorConstructWithSize,
  tensorFree,
  tensorResize,
  tensorResizeAs,
  tensorResize1d,
  tensorResize2d,
  tensorResize3d,
  tensorResize4d,
  tensorResize5d,
  tensorSet,
  tensorSetStorage,
  tensorSetStorage1d,
  tensorSetStorage2d,
  tensorSetStorage3d,
  tensorSetStorage4d,
  tensorNarrow,
  tensorSelect,
  tensorTranspose,
  tensorUnfold,

  tensorFill,
  tensorGather,
  tensorScatter,
  tensorScatterFill,
  tensorDot,
  tensorMinall,
  tensorMaxall,
  tensorSumall,
  tensorProdall,
  tensorNeg,
  tensorCinv,
  tensorAdd,
  tensorSub,
  tensorMul,
  tensorDiv,
  tensorFmod,
  tensorRemainder,
  tensorClamp,
  tensorCadd,
  tensorCsub,
  tensorCmul,
  tensorCpow,
  tensorCdiv,
  tensorCfmod,
  tensorCremainder,
  tensorAddcmul,
  tensorAddcdiv,
  tensorAddmv,
  tensorAddmm,
  tensorAddr,
  tensorAddbmm,
  tensorBaddbmm,
  tensorMatch,
  tensorNumel,
  tensorMax,
  tensorMin,
  tensorKthvalue,
  tensorMode,
  tensorMedian,
  tensorSum,
  tensorProd,
  tensorCumsum,
  tensorCumprod,
  tensorSign,
  tensorTrace,
  tensorCross,
  tensorCmax,
  tensorCmin,
  tensorCmaxValue,
  tensorCminValue,
  tensorDiag,
  tensorEye,
  tensorRange,
  tensorRandperm,
  tensorReshape,
  tensorSort,
  tensorTopk,
  tensorTril,
  tensorTriu,
  tensorCatArray,
  tensorEqual,
  tensorLtValue,
  tensorLeValue,
  tensorGtValue,
  tensorGeValue,
  tensorNeValue,
  tensorEqValue,
  tensorLtValueT,
  tensorLeValueT,
  tensorGtValueT,
  tensorGeValueT,
  tensorNeValueT,
  tensorEqValueT,
  tensorLtTensor,
  tensorLeTensor,
  tensorGtTensor,
  tensorGeTensor,
  tensorNeTensor,
  tensorEqTensor,
  tensorLtTensorT,
  tensorLeTensorT,
  tensorGtTensorT,
  tensorGeTensorT,
  tensorNeTensorT,
  tensorEqTensorT,
  tensorAbs,
  tensorSigmoid,
  tensorLog,
  tensorLog1p,
  tensorExp,
  tensorCos,
  tensorAcos,
  tensorCosh,
  tensorSin,
  tensorAsin,
  tensorSinh,
  tensorTan,
  tensorAtan,
  tensorAtan2,
  tensorTanh,
  tensorPow,
  tensorTpow,
  tensorSqrt,
  tensorRsqrt,
  tensorCeil,
  tensorFloor,
  tensorRound,
  tensorTrunc,
  tensorFrac,
  tensorLerp,
  tensorMean,
  tensorStd,
  tensorVar,
  tensorNorm,
  tensorRenorm,
  tensorDist,
  tensorHistc,
  tensorBhistc,
  tensorMeanall,
  tensorVarall,
  tensorStdall,
  tensorNormall,
  tensorLinspace,
  tensorLogspace,
  tensorRand,
  tensorRandn,
  tensorLogicalall,
  tensorLogicalany,

  // th_random
  tensorRandom,
  tensorGeometric,
  tensorBernoulli,
  tensorBernoulli_FloatTensor,
  tensorBernoulli_DoubleTensor,
  tensorUniform,
  tensorNormal,
  tensorExponential,
  tensorCauchy,
  tensorLogNormal,
  tensorMultinomial,

  // storage functions
  storageSet,
  storageGet,

  storageConstruct,
  storageConstructWithSize,
  storageConstructWithSize1,
  storageConstructWithSize2,
  storageConstructWithSize3,
  storageConstructWithSize4,

  storageFree,
  storageResize,
  storageFill,

  // communication requests
  sendTensor,
  sendStorage,
};

} // namespace thd
