name: Run linters

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
        description: The runner to use
      docker-image:
        required: true
        type: string
        description: The Docker image to use
      script:
        required: true
        type: string
        description: The linter script to run

jobs:
  lint:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.docker-image }}
    timeout-minutes: 120
    steps:
      - name: Fix Git ownership
        shell: bash
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@main
        with:
          fetch-depth: 0
          submodules: true
          no-sudo: true
          checkout-mode: treeless

      - name: Setup uv
        uses: pytorch/test-infra/.github/actions/setup-uv@main
        with:
          python-version: "3.12"
          activate-environment: true

      - name: Install pip requirements
        shell: bash
        run: |
          set -eux
          uv pip install -r .ci/docker/requirements-ci.txt

      - name: Install system requirements
        shell: bash
        run: |
          set -eux
          # Update repository
          dnf install -y doxygen graphviz nodejs npm

      - name: Install Node.js packages
        shell: bash
        run: |
          set -eux
          npm install -g markdown-toc

      - name: Prepare lintrunner
        shell: bash
        run: |
          set -eux
          lintrunner init

      - name: Run linter
        shell: bash
        env:
          SCRIPT: ${{ inputs.script }}
        run: |
          {
            echo "#!/usr/bin/env bash";
            echo "set -eou pipefail";
            echo "${SCRIPT}";
          } > "${RUNNER_TEMP}/linter_script"

          # Execute the linter script
          bash "${RUNNER_TEMP}/linter_script"
