# Owner(s): ["module: macos"]
name: inductor-perf-nightly-macos

on:
  schedule:
    - cron: 0 7 * * *
  workflow_dispatch:
    inputs:
      training:
        description: Run training (on by default)?
        required: false
        type: boolean
        default: true
      inference:
        description: Run inference (on by default)?
        required: false
        type: boolean
        default: true
      benchmark_configs:
        description: The list of configs used the benchmark
        required: false
        type: string
        default: torchbench_perf_mps
  pull_request:
    paths:
      - .github/workflows/inductor-perf-test-nightly-macos.yml
      - .ci/pytorch/macos-test.sh

concurrency:
  group:  ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions: read-all

jobs:
  check-ci:
    if: github.repository_owner == 'pytorch'
    uses: ./.github/workflows/_check-ci.yml
