# Owner(s): ["module: ci"]
name: Populate ClickHouse Owners

on:
  pull_request:
    paths:
      - .github/workflows/populate-clickhouse-owners.yml
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  populate-owners:
    if: github.repository_owner == 'pytorch'
    runs-on: ubuntu-24.04
    steps:
      - name: Populate owners (placeholder)
        run: 'echo ok'
