# Owner(s): ["module: risc-v"]
name: riscv64

on:
  push:
    tags:
      - ciflow/riscv64/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  get-label-type:
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}
      check_experiments: arc,lf

  pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build:
    if: github.repository_owner == 'pytorch'
    name: pytorch-linux-noble-riscv64-py3_12-gcc14-cross-build
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      build-environment: linux-noble-riscv64-py3.12-gcc14
      docker-image-name: ci-image:pytorch-linux-noble-riscv64-py3.12-gcc14
      ci-docker-hash: ${{ needs.get-label-type.outputs.ci-docker-hash }}
      runner: linux.c7i.2xlarge
      use-arc: ${{ needs.get-label-type.outputs.use-arc == 'true' }}
      python-version: "3.12"
      compiler: gcc14
      cuda-version: cpu
    secrets: inherit
