name: torchtitan-test

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - ciflow/torchtitan/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.ref_type == 'branch' && github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  get-label-type:
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    if: ${{ (github.event_name != 'schedule' || github.repository == 'pytorch/pytorch') && github.repository_owner == 'pytorch' }}
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}
      check_experiments: arc,lf

  build:
    name: torchtitan-x-pytorch-build
    if: github.repository_owner == 'pytorch'
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      build-environment: linux-jammy-cuda13.0-py3-gcc11
      docker-image-name: ci-image:pytorch-linux-jammy-cuda13.0-cudnn9-py3-gcc11
      ci-docker-hash: ${{ needs.get-label-type.outputs.ci-docker-hash }}
      cuda-arch-list: '8.0 8.9 9.0 10.0'
      runner: linux.24xlarge.memory
      # torchtitan_h100_integration disabled pending runner availability
      test-matrix: |
        { include: [
          { config: "torchtitan_features_integration", shard: 1, num_shards: 1, runner: "linux.g5.48xlarge.nvidia.gpu" },
          { config: "torchtitan_models_integration", shard: 1, num_shards: 1, runner: "linux.g5.48xlarge.nvidia.gpu" }
        ]}
      use-arc: ${{ needs.get-label-type.outputs.use-arc == 'true' }}
      python-version: "3.10"
      compiler: gcc11
      cuda-version: "13.0"
    secrets: inherit

  test:
    name: torchtitan-x-pytorch-test
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - build
      - get-label-type
    with:
      build-environment: linux-jammy-cuda13.0-py3-gcc11
      docker-image: ${{ needs.build.outputs.docker-image }}
      test-matrix: ${{ needs.build.outputs.test-matrix }}
      test-matrix-osdc: ${{ needs.build.outputs.test-matrix-osdc }}
      use-arc: ${{ needs.get-label-type.outputs.use-arc == 'true' }}
      python-version: "3.10"
      compiler: gcc11
      cuda-version: "13.0"
    secrets: inherit
