name: TSan

on:
  push:
    tags:
      - ciflow/tsan/*
      - ciflow/trunk/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  get-label-type:
    if: github.repository_owner == 'pytorch'
    name: get-label-type
    uses: pytorch/pytorch/.github/workflows/_runner-determinator.yml@main
    with:
      triggering_actor: ${{ github.triggering_actor }}
      issue_owner: ${{ github.event.pull_request.user.login || github.event.issue.user.login }}
      curr_branch: ${{ github.head_ref || github.ref_name }}
      curr_ref_type: ${{ github.ref_type }}

  linux-jammy-py3_14t-clang18-tsan-build:
    name: linux-jammy-py3.14t-clang18-tsan
    uses: ./.github/workflows/_linux-build.yml
    needs: get-label-type
    with:
      runner_prefix: "${{ needs.get-label-type.outputs.label-type }}"
      build-environment: linux-jammy-py3.14t-clang18-tsan
      docker-image-name: ci-image:pytorch-linux-jammy-py3.14t-clang18
      test-matrix: |
        { include: [
          { config: "tsan", shard: 1, num_shards: 1, runner: "${{ needs.get-label-type.outputs.label-type }}linux.2xlarge" },
        ]}
      use-arc: ${{ needs.get-label-type.outputs.use-arc == 'true' }}
      python-version: "3.14t"
      compiler: clang18
    secrets: inherit

  linux-jammy-py3_14t-clang18-tsan-test:
    name: linux-jammy-py3.14t-clang18-tsan
    uses: ./.github/workflows/_linux-test.yml
    needs:
      - linux-jammy-py3_14t-clang18-tsan-build
      - get-label-type
    with:
      build-environment: linux-jammy-py3.14t-clang18-tsan
      docker-image: ${{ needs.linux-jammy-py3_14t-clang18-tsan-build.outputs.docker-image }}
      test-matrix: ${{ needs.linux-jammy-py3_14t-clang18-tsan-build.outputs.test-matrix }}
      use-arc: ${{ needs.get-label-type.outputs.use-arc == 'true' }}
      python-version: "3.14t"
      compiler: clang18
    secrets: inherit
