# Owner(s): ["module: ci"]
name: Upload test stats while running

on:
  schedule:
    # Every hour
    - cron: '0 * * * *'

concurrency:
  group: upload-test-stats-while-running
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  upload_test_stats_while_running:
    if: github.repository_owner == 'pytorch'
    name: Upload test stats while running
    runs-on: mt-l-x86iamx-8-16
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Setup Linux
        uses: pytorch/pytorch/.github/actions/setup-linux@main
        with:
          use-arc: true
          submodules: false

      - name: Setup uv
        uses: pytorch/test-infra/.github/actions/setup-uv@main
        with:
          python-version: "3.12"
          activate-environment: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: arn:aws:iam::308535385114:role/arc
          aws-region: us-east-1
          role-duration-seconds: 18000

      - name: Install requirements
        run: |
          uv pip install requests==2.32.2 boto3==1.35.42

      - name: Upload test stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 -m tools.stats.upload_test_stats_running_jobs
