name: Windows RTX Nightly

on:
  schedule:
    # Run every day at 00:30 AM UTC
    - cron: '30 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}-${{ github.event_name == 'schedule' }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:

  # Windows CUDA Build & Test - sm_89 (RTX 40xx)
  win_vs2022_cuda12_8_py3_build_sm89:
    if: github.repository_owner == 'pytorch'
    name: win-vs2022-cuda12.8-py3-sm89
    uses: ./.github/workflows/_win-build.yml
    with:
      build-environment: win-vs2022-cuda12.8-py3-sm89
      cuda-version: "12.8"
      python-version: "3.12"
      runner: "rtx-40x0-build"
      aws-role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_s3_and_ecr_read_only
      cuda-arch-list: "8.9"
      runner-machine: "nvidia"
      test-matrix: |
        { include: [
          { config: "default",          shard: 1, num_shards: 5, runner: "rtx-40x0-test" },
          { config: "default",          shard: 2, num_shards: 5, runner: "rtx-40x0-test" },
          { config: "default",          shard: 3, num_shards: 5, runner: "rtx-40x0-test" },
          { config: "default",          shard: 4, num_shards: 5, runner: "rtx-40x0-test" },
          { config: "default",          shard: 5, num_shards: 5, runner: "rtx-40x0-test" }
        ]}
    secrets: inherit

  win_vs2022_cuda12_8_py3_test_sm89:
    name: win-vs2022-cuda12.8-py3-sm89
    needs:
      - win_vs2022_cuda12_8_py3_build_sm89
    uses: ./.github/workflows/_win-rtx-test.yml
    with:
      build-environment: win-vs2022-cuda12.8-py3-sm89
      build-secure-hash: ${{ needs.win_vs2022_cuda12_8_py3_build_sm89.outputs.build-secure-hash }}
      build-artifact-name: ${{ needs.win_vs2022_cuda12_8_py3_build_sm89.outputs.build-artifact-name }}
      cuda-version: "12.8"
      cuda-arch-list: "8.9"
      disable-monitor: true
      aws-role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_s3_and_ecr_read_only
      test-matrix: ${{ needs.win_vs2022_cuda12_8_py3_build_sm89.outputs.test-matrix }}
      timeout-minutes: 240
    secrets: inherit

  # Windows CUDA Build & Test - sm_120 (Blackwell - RTX 5070)
  win_vs2022_cuda12_8_py3_build_sm120:
    if: github.repository_owner == 'pytorch'
    name: win-vs2022-cuda12.8-py3-sm120
    uses: ./.github/workflows/_win-build.yml
    with:
      build-environment: win-vs2022-cuda12.8-py3-sm120
      cuda-version: "12.8"
      runner-machine: "nvidia"
      runner: "rtx-50x0-build"
      aws-role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_s3_and_ecr_read_only
      python-version: "3.12"
      cuda-arch-list: "12.0"
      test-matrix: |
        { include: [
          { config: "default",          shard: 1, num_shards: 5, runner: "rtx-50x0-test" },
          { config: "default",          shard: 2, num_shards: 5, runner: "rtx-50x0-test" },
          { config: "default",          shard: 3, num_shards: 5, runner: "rtx-50x0-test" },
          { config: "default",          shard: 4, num_shards: 5, runner: "rtx-50x0-test" },
          { config: "default",          shard: 5, num_shards: 5, runner: "rtx-50x0-test" },
        ]}
    secrets: inherit

  win_vs2022_cuda12_8_py3_test_sm120:
    name: win-vs2022-cuda12.8-py3-sm120
    needs:
      - win_vs2022_cuda12_8_py3_build_sm120
    uses: ./.github/workflows/_win-rtx-test.yml
    with:
      build-environment: win-vs2022-cuda12.8-py3-sm120
      build-secure-hash: ${{ needs.win_vs2022_cuda12_8_py3_build_sm120.outputs.build-secure-hash }}
      build-artifact-name: ${{ needs.win_vs2022_cuda12_8_py3_build_sm120.outputs.build-artifact-name }}
      cuda-version: "12.8"
      cuda-arch-list: "12.0"
      disable-monitor: true
      aws-role-to-assume: arn:aws:iam::308535385114:role/gha_workflow_s3_and_ecr_read_only
      test-matrix: ${{ needs.win_vs2022_cuda12_8_py3_build_sm120.outputs.test-matrix }}
      timeout-minutes: 240
    secrets: inherit
