IF(NOT GLOO_FOUND)

include(FindPackageHandleStandardArgs)

SET(GLOO_LIBRARIES)
SET(GLOO_INCLUDE_DIR)

FIND_LIBRARY(GLOO_LIBRARIES gloo)
FIND_PATH(GLOO_INCLUDE_DIR gloo/context.h)

IF (GLOO_LIBRARIES)
  SET(GLOO_FOUND TRUE)
ELSE (GLOO_LIBRARIES)
  SET(GLOO_FOUND FALSE)
ENDIF (GLOO_LIBRARIES)

ENDIF(NOT GLOO_FOUND)

